### ISSUE TITLE
horizontal scrolling of breadcrumbs jerks randomly

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10005]
unsure what's happening, but in FF at least the breadcrumbs fight my scrolling and scrolljump

**Comment by jryans** [comment]
I think the core issue here is that scroll wheel fix (https://github.com/matrix-org/matrix-react-sdk/pull/3051) is a regression for those using trackpads (at least in Firefox) since the wheel events will be a succession of very small values which incorrectly triggers the "additional scroll" for mouse wheels to kick in.

**Comment by jryans** [comment]
I see the same behaviour in Chrome as well. The issue only occurs if you have a vertical component to your trackpad scroll.

If you manage to have only horizontal scrolling (hard to do), then it works okay.

**Comment by turt2live** [comment]
The code that tries to detect trackpads doesn't work sometimes because it looks for an absolute deltaX of more than zero before applying amplification - some trackpads/operating systems (MacOS) issue several scroll events which may trip this condition. As a result, one in every third (ish) event is amplified, leading to jerky behaviour.

This leaves us with several options:
1. Accept it as not a bug (do nothing)
2. Fix it for trackpads, but break it for Firefox/smooth scrolling browsers.
3. Don't handle vertical scroll at all.
4. Introduce a setting to turn *on* the scroll amplification.

So far, option 4 seems like the best option and we can word it like "Boost scrolling in breadcrumbs" to put a positive spin on the situation. 

@lampholder what do you think?

**Comment by jryans** [comment]
I am curious what the wheel event's `deltaMode` value is for mouse wheels... For a macOS trackpad, it's 0, which means `delta*` values are in pixels. If mouse wheels with smooth scrolling have `deltaMode` set to non-zero, then maybe that could be used to distinguish them. (I don't think I have a mouse wheel around to test with...)

**Comment by ara4n** [comment]
how about:
 * if you see any horizontal movement at all, assume that the user is on a trackpad, and ignore all vertical scroll events (i.e. the original behaviour)
 * otherwise, treat vertical scrolls as horizontal ones.

**Comment by turt2live** [comment]
That's option 2 from above.

**Comment by turt2live** [comment]
So it turns out I've been misunderstanding @ara4n for the last 11 days. In our retro earlier this was brought up again, and there was more emphasis on the key word I've been missing: ***any***.

There's a potential risk of mouse users being impacted (if they for whatever reason decide to change between horizontal and vertical scroll, like I do), but I think ultimately that's solved by a TTL on the flag. Maybe limit it to, say, 15 minutes?
