### ISSUE TITLE
Redirect into app from auth flows when already logged in

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#10075]
If you're already logged in, then loading the auth flows should redirect back inside the app instead of making it appear that you are logged out.

We should verify that no one is depending on the current behaviour before making a change here.

**Comment by turt2live** [comment]
This is somewhat relied on for 3pid validation. When adding a 3pid or you happen to click on a validation link in your email, we direct people to the auth pages. We should already be very careful about trampling on sessions in those cases as of a recent release.

**Comment by lampholder** [comment]
©bob:matrix.org is logged into riot, but wants to test something with a fresh account. So he opens an incognito browser to register ©test.234234:matrix.org (associated with throwaway@disposable.tld). Then he accidentally opens the email validation link in his main non-incognito browser window. What _can_ we do and what do we _want_ to do?

(I know there's a separate use case involving associating threepids with existing accounts outside of registration, but I'm going to exclude that for the time being).

The registration threepid validation _needs_ to redirect to riot's /register, which then needs to poll the homeserver's /register in order to:
- see if there are any more registration steps required for ©test.234234:matrix.org
- get the user to complete those steps if they're necessary, or issue the final 'complete registration' instruction to the homeserver otherwise

But ©bob:matrix.org already has an active riot session in this browser. What to do? As far as I can tell we only have two stable options:
1. log out ©bob:matrix.org's active session and replace it with ©test.234234:matrix.org
1. refuse to complete ©test.234234:matrix.org's registration (despite the fact that we will have successfully completed the association between ©test.234234:matrix.org and throwaway@disposable.tld) and tell the user to log out first or open the verification link in a different browser

Of those, only option 2. is any good. I _think_ that could work fine, as long as:
- Riot's /register has enough information available to it to discern that the threepid verification wasn't destined for the active session, and
- threepid verification is idempotent (so opening the verif link in another browser does the right thing)

Thoughts?

**Comment by dbkr** [comment]
Have we ruled out special-casing it, ie. saying, "well done for registering ©test.234234:matrix.org but you're already logged in as ©bob:matrix.org, what'll it be?"

**Comment by turt2live** [comment]
(the special casing was what happened pre-registration sprint ftr, to fix https://github.com/vector-im/riot-web/issues/6875)
