### ISSUE TITLE
cursor keys are now trapped by autocomplete selector even if you're not autocompleting

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10116]
if you type :)<kbd>left arrow</kbd> then suddenly the :) gets turned into an emoji picked from autocomplete options, which you then have to disentangle yourself from & cancel.

This is a recent regression, and very annoying, because i do not expect autocompletes to kick in unless i am explicitly autocompleting (by hitting tab or whatever), rather than moving cursor keys to fix typos caused by my broken keyboard.

**Comment by bwindels** [comment]
ftr, this is in the main composer

**Comment by bwindels** [comment]
regression from https://github.com/matrix-org/matrix-react-sdk/pull/2966/files

**Comment by bwindels** [comment]
So, the change that was introduced in the above PR is that the left and right arrows also navigate the completions (when available) instead of the caret. This brought it in line with what that up and down arrow already did before that. So in a multi-line message, you'd already have the problem trying to move the cursor up or down.

This brings up the question, how should autocomplete work?
 - only open when explicitly asked for (tab)?
 - open explicitly and on certain cues (typing `@`, `#`, `:`)?
 	- How about ascii aliases for emojis like xD for 😆?
 - once autocompletion is open, should
 	- left & right arrow navigates completions instead of caret?
 	- up & down arrow navigates completions instead of caret?
 - just for clarity: once escape is pressed, autocomplete should not reappear for the same location in the editor

It makes sense that the left / right arrow being diverted is a lot more bothersome than up and down as that's how you navigate the editor most of the time. I propose I just disable left and right arrows going to autocomplete when it's open to get rid of the annoyance for now.

**Comment by lampholder** [comment]
@bwindels - yes - I reckon we just remove left/right for now.
