### ISSUE TITLE
VoIP: Stop falling back to Google for STUN

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-web#10173]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2532  

Stop using any hardcoded fallback URL in the SDK.

**Comment by jryans** [comment]
We need to decide whether to replace the fallback server with something else (to preserve the same likelihood that VoIP calls can be completed) or remove the fallback entirely and hope for the best.

**Comment by neilisfragile** [comment]
It would be good enough to fall back to Google STUN on fail so long as the user is explicitly prompted.

cc @ara4n

**Comment by dbkr** [comment]
We also decided to use our own stun server as a fallback rather than google's. Remaining questions:

 * Do we want it to be stun.riot.im or do we just want to re-use turn.matrix.org?
 * Where do we persist the user's decision of whether to use the fallback, and how long, therefore, should we remember that decision? For that login session on that device, to account data or somewhere else?

**Comment by jryans** [comment]
Current thinking is:

* Use turn.matrix.org as the server name
* Asking permission for every call to fallback in the case that HS doesn't have a STUN server

This issue may apply both to making and receiving calls.

**Comment by ara4n** [comment]
we need to make clear that falling back to matrix.org is a hail mary which may not work (when giving them the option) and the right fix is for their server to configure turn

**Comment by neilisfragile** [comment]
After a huddle conclusions are:-
 * We use turn.matrix.org
 * We prompt the user on registration/sign in that they do not have a TURN server configured and that they can fall back to the matrix.org one
 * Out of pragmatism (and also as a nag to server admins to fix) store this on the client rather than account data, so each client will prompt independently
 * Need a config option to disable the consent

Separately we will create a tool to help admins trouble shoot their TURN config https://github.com/matrix-org/synapse/issues/1519

**Comment by jryans** [comment]
Just to clarify, we'll be offering `turn.matrix.org` as a general fallback via the STUN protocol only (not the TURN protocol). The STUN protocol is effectively a public IP lookup only, while the TURN protocol means you also relay the data.

**Comment by jryans** [comment]
We have agreed to change the time of the prompt:

* Prompt before placing a call if no TURN from HS
* Prompt after receiving a call if the call fails and no TURN from HS

**Comment by jryans** [comment]
After discussion with @nadonomy, we'll use the following dialog text for the prompt:

>You cannot make calls
>
>Your homeserver (`test.convolv.es`) isn’t configured to make voice or video calls. Ask your homeserver admin to set up a TURN server to enable them.
>
>Alternatively, you can make voice & video calls using our public STUN server (hosted at `turn.matrix.org`), sharing your IP address with us. You can also manage this in Settings.
>
>[Cancel] [Use Public Server]

**Comment by ara4n** [comment]
Not sure the simplification works here - it's not that you can't make calls, but that it will be unreliable.  And this text implies that using the public Matrix server will magically fix, which it probably won't.

Let's simplify things by only showing the warning after a call fails.  We don't care if TURN is misconfigured before a call if that call then goes on to wrk.

How about:

> Call failed due to misconfigured server
>
> Please ask the administrator of (`arasphere.net`) to [configure a TURN server](https://github.com/matrix-org/synapse/blob/master/docs/turn-howto.rst) in order for calls to work reliably.
>
> Alternatively, you can try to use the public server at `turn.matrix.org`, but this will not be as reliable, and it will share your IP address with that server. You can also manage this in Settings.
>
> [OK] [Try using turn.matrix.org]
