### ISSUE TITLE
Clicking the reactions button causes flashing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10222]
The scrollbar on the timeline disappears and comes back, the highlight on the message flashes, and the tooltip itself flashes. fwiw my first instinct is to try and click the button

**Comment by bwindels** [comment]
could just not close the tooltip when clicking?

**Comment by turt2live** [comment]
that would be an ideal solution. I think a lot of the tooltip bugs from my part are because there's an invisible full-page div which is used to close the tooltip (which also means the hover state is lost, hence the flickering from #10179)

**Comment by jryans** [comment]
Right, we could remove click to close. It was added as a conservative escape hatch of sorts.

I believe we still need some kind of transparent `div` watching mouse position since we're keeping the tooltip open when inside a safe area that is larger than the tooltip itself. Open to suggestions for another way to do this that also preserves hover... 😄

**Comment by turt2live** [comment]
can we just listen on `document` instead?

**Comment by jryans** [comment]
Ah yeah, maybe! 😅 I'll give it a try. I probably borrowed too much from other tooltips when making this one...
