### ISSUE TITLE
Soft logout

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10224]
I couldn't find an existing riot web issue for this, but it should be possible to log a user out without obliterating their session.

There's an [MSC Proposal for this](https://github.com/matrix-org/matrix-doc/blob/55ebf7dc3275822ad0126546baef4b1361418baf/proposals/1466-soft-logout.md).

tl;dr you're logged out (can't sync any more or send any messages) but your encryption keys aren't blown away, and you can recover access to your current session by typing in your password.

UX to follow.

**Comment by lampholder** [comment]
As a strawman, how about a UX something like this:

![Soft logout](https://user-images.githubusercontent.com/1922197/60451433-ef0e7000-9c23-11e9-8406-0d7825011b1a.png)

**Comment by turt2live** [comment]
There's the concern of users seeing errors all over the place regarding connectivity (favicon, title, status bar above composer, etc)

**Comment by turt2live** [comment]
There's the concern of users seeing errors all over the place regarding connectivity (favicon, title, status bar above composer, etc)

**Comment by richvdh** [comment]
Note that this needs to work correctly for SSO flows.

**Comment by lampholder** [comment]
Ah yes, it could be fiddly to go through supressing all the usual indicators of Riot panicing about connectivity. Although would it really look that bad I wonder?

**Comment by nadonomy** [comment]
Considering the user can't sync, it might be more graceful to hide the app UI and provide a UI with the only actions a user can take (export encryption keys? 'hard' logout?).

**Comment by richvdh** [comment]
on the impl side: we'll need to preserve device_id; I'm hoping the app will be able to remember its device_id and resubmit it with the re-login.

**Comment by lampholder** [comment]
> Considering the user can't sync, it might be more graceful to hide the app UI and provide a UI with the only actions a user can take (export encryption keys? 'hard' logout?).

It was @ara4n's suggestion was to leave the regular UX visible in the background, I think to highlight how tantalisingly close you are to a fully working riot session again. But I think I agree - coupled with @turt2live's concerns about the connectivity warnings shining through the greyed out timeline it risks looking kinda glitchy.

Do we want users to be able to export their encryption keys in this state?

**Comment by nadonomy** [comment]
> Do we want users to be able to export their encryption keys in this state?

If it's possible, it'd be a shame to not let users salvage their keys if they can. Am I correct in thinking they could do a local export, but not engage with server side backup?

**Comment by turt2live** [comment]
> Am I correct in thinking they could do a local export, but not engage with server side backup?

@nadonomy yes, they can do a local backup (the old style 'export your keys' before signout dialog)

**Comment by nadonomy** [comment]
From Zeplin: https://zpl.io/a89QL5x

(Easily missed) comments from Zeplin:

- 'clear all' should lead the user to a confirmation modal to prevent accidental misclicks
- 'Sign In' should lead the user to the sign in flow, with as much info pre-filled as we can (mxid, server)

**Comment by turt2live** [comment]
I've split this out to several issues to better track progress:
* [Show the page](https://github.com/vector-im/riot-web/issues/10235)
* [Prefill login](https://github.com/vector-im/riot-web/issues/10236)
* [Redirect when soft logged out](https://github.com/vector-im/riot-web/issues/10234)
* [Avoid overwriting sessions](https://github.com/vector-im/riot-web/issues/10237)
* [Test using SSO](https://github.com/vector-im/riot-web/issues/10238)

**Comment by nadonomy** [comment]
We had an internal meeting today with several riot/encryption stakeholders and surmised the following:

* Keys are as vulnerable to 'evil maid' attacks via localStorage infiltration, so gating key export behind auth would provide a false sense of security, so we decided against doing so.
* We re-laid out the sections by user intention ("I don't want to sign in" & "Sign in") rather than by mechanic, as it improves the user experience for non technical users.
* The client knows whether or not (a) the user had server side key backup enabled (b) if they did, whether any local keys aren't backed up. Therefore, we should only show the "I don't want to sign in again" section to users that don't have keys backed up, and not trouble users who do.

The latest changes are reflected in Zeplin here: https://zpl.io/a89QL5x
For posterity, full minutes from the sync are also [here](https://docs.google.com/document/d/1ipFde174IT0Nuw1pMLJ-U3LsoAaCh2wPcLmJVcYkK_E/edit?usp=sharing).

@turt2live I'm adding these notes to https://github.com/vector-im/riot-web/issues/10235, are there any other issues that should be updated based on this?

**Comment by turt2live** [comment]
Thanks @nadonomy - the comments on https://github.com/vector-im/riot-web/issues/10235 should be enough. I've also put a checklist there to track the bits that need to be done.

**Comment by nadonomy** [comment]
@turt2live Zeplin is now updated based on the latest requirements: https://zpl.io/a89QL5x

(will also x-post this to #10235)
