### ISSUE TITLE
Recurring notification for edited message

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10314]
In an encrypted room, with me and Nad, and room notification settings set to 'All Message (Noisy)', Nad send a message, I replied, and then he edited that message.

Here's a screenshot with the 'show hidden events' labs feature turned on:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/1922197/61054063-ac4c5500-a3e6-11e9-8752-6e4c58a6a18c.png">

Every time I refresh the client, that room shows a '1' in a grey circle to tell me I have unread messages. Going to the room shows no new messages.

**Comment by bwindels** [comment]
Does it still do that when you turn "show hidden events" on?
Also, can you rageshake please?

**Comment by jryans** [comment]
(Tom originally had "show hidden events" disabled when he saw the issue, and he only turned it on at my suggestion to help debug the issue. I would suspect that having the option on makes the issue go away as a kind of workaround, since the event becomes visible.)

Since Tom was the last one to send a regular message, I have a suspicion this is a bad interaction in the read receipt advancing code between "ignore your own messages" and "advance into events without tiles".

First we walk up from the last event in the room to find the last displayed event, ignoring your own. In the image above (assuming hidden events were not there), that would be Nad's last message "Blanditiis ...".

We then advance forward for any events without tiles immediately after the identified message. None exist (the edit event is after Tom's message, not Nad's).

So, we have failed to advance Tom's read receipt for Nad's edit in this case. 😭

**Comment by jryans** [comment]
A simple fix would be to include your own messages when advancing read receipts, but it means Riot becomes a lot more chatty, telling the HS to move your read receipt for every message you send...

**Comment by bwindels** [comment]
This should probably go into 1.3.0

**Comment by jryans** [comment]
This landed in Riot 1.3.0-rc.3.
