### ISSUE TITLE
Edit history only shows the most recent copy of a message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10332]
A message edited once has a single tile in the dialog, which is the current version

**Comment by anoadragon453** [comment]
dup https://github.com/matrix-org/synapse/issues/5595

**Comment by turt2live** [comment]
I disagree: I'm not using the server for this as far as I know

**Comment by anoadragon453** [comment]
I believe the problem is that the server currently only sends down the relations, not the original event, so when you query for edits you only get the edits, not the original message body.

Can you test on the `bwindels/include-orig-in-history` branches for `matrix-react-sdk` and `matrix-js-sdk` with Synapse `develop` and see if the problem still persists?

**Comment by anoadragon453** [comment]
> I disagree: I'm not using the server for this as far as I know

The history should be coming from `/_matrix/client/unstable/rooms/{roomID}/relations/{eventID}/m.replace/m.room.message?`.

**Comment by turt2live** [comment]
Fine, I'll close it. I don't have a homeserver which has that endpoint, and I'm not running those branches right now (it's non-trivial for me to switch atm)
