### ISSUE TITLE
Switching rooms doesn't focus composer anymore

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10384]
on develop as of writing. Chrome, windows 10

**Comment by bwindels** [comment]
Ftr, that was sort of intentional with https://github.com/matrix-org/matrix-react-sdk/pull/3224. If you type (and with https://github.com/matrix-org/matrix-react-sdk/pull/3239 paste) anything, it will focus the composer though.

You think it should still focus on room change regardless of the above?

**Comment by turt2live** [comment]
Yes, otherwise I spend my time focusing it because I feel like there's a bug.
