### ISSUE TITLE
irc bridge list is apparently wrong for matrix.org and is missing lots of bridges

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10438]

**Comment by jaywink** [comment]
Ping @Half-Shot - last time I checked we had all the bridges that were running listed in Scalar. Are we missing some? Currently seems to only have `Freenode` and `GIMPnet`.

**Comment by Half-Shot** [comment]
- Snoonet
- Moznet
- OFTC 

are the 3 that I think are missing. I'm still working on espernet.

**Comment by ElonSatoshi** [comment]
Not to mention [all the other networks listed here](https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks).

I'd like to bridge a room of mine to Snoonet. Is there a workaround?

**Comment by jaywink** [comment]
Sorry for the delay. Snoonet (fyi @ElonSatoshi ) and OFTC have now been enabled in Scalar, so will be visible on for example matrix.org and other servers using it.

For Moznet we need to do a little investigative work.

**Comment by Half-Shot** [comment]
Mozilla isn't coming back for the time being. Closing this bug.

**Comment by Half-Shot** [comment]
>Mozilla isn't coming back for the time being. Closing this bug.

I should point out this was related to the provisioning and not the bridge itself. The bridge is operational. 

I am reopening this issue in https://github.com/matrix-org/matrix-appservice-irc/issues/792. The reason we were not bringing provisioning back was due to a decision on my part that the moznet net was being decommisioned in the future. However, it looks like that may not be the case so we will be looking to re-enable provisioning support.

For the time being, moznet is still not going to be included in the list while it's provisioning support is disabled.
