### ISSUE TITLE
Integration manager terms hides terms that need signing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10497]
It looks like it dedupes on name not URL, so it hides some checkboxes

**Comment by turt2live** [comment]
`/terms` response is:
```
{
    "policies": {
        "terms_of_service": {
            "version": "v1",
            "en": {
                "name": "Terms of Service",
                "url": "http://localhost:8082/widgets/terms/terms_of_service/en/v1"
            }
        },
        "upstream_e640b81620d0cd71dd17bd46a209a815_privacy_policy": {
            "en": {
                "name": "Privacy Policy",
                "url": "https://example.org/privacy/v2/en.html"
            },
            "fr": {
                "name": "Politique de confidentialité",
                "url": "https://example.org/privacy/v2/fr.html"
            },
            "version": "v2"
        },
        "upstream_e640b81620d0cd71dd17bd46a209a815_terms_of_service": {
            "en": {
                "name": "Terms of Service",
                "url": "https://example.org/tos/v1/en.html"
            },
            "fr": {
                "name": "Conditions d'utilisation",
                "url": "https://example.org/tos/v1/fr.html"
            },
            "version": "v1"
        }
    }
}
```

**Comment by turt2live** [comment]
actually it's because the URL is http not https, which is silly. We should support both given it's a valid deployment for the terms of service to be on an http URL (ie: internal server, something that doesn't need SSL, etc)

**Comment by jryans** [comment]
I reused exactly the config block above to investigate this...

I was only presented with two URLs to agree:

* https://example.org/privacy/v2/en.html
* http://localhost:8082/widgets/terms/terms_of_service/en/v1

The other URL:

* https://example.org/tos/v1/en.html

was not presented, which sounds like this issue, but this is because I've already agreed this URL (since it's the same as the sample URL I've been using locally before this issue) and it was saved in my account data.

If I clear out my account data, I am presented with 3 URLs to agree to as expected.

@turt2live, do you think a similar thing with account data happened to you as well?

**Comment by turt2live** [comment]
it was a fresh account, so it shouldn't have had anything in account data.

**Comment by jryans** [comment]
I've tried some more testing here, but so far all I can think of is account data causing confusion... The code doesn't appear to deduplicate on title, but instead only URL. The full URL is treated as an opaque string, so http vs. https should not make a difference.

@turt2live, are you able to reproduce this?

**Comment by turt2live** [comment]
Not anymore :(

I suppose it was possible that it was account data I wasn't seeing. I thought I was using a fresh account but I might have missed a step or something.
