### ISSUE TITLE
keep getting invalid file when try to upload file using Media -> Upload

### ISSUE THREAD

**Issue by amiraelsayed** [vector-im/riot-web#10496]
I am trying to upload file using web request Media -> Upload 

POST /_matrix/media/r0/upload

but the file always uploaded and when try to open it , it gives me invalid file 

and give me download link and when  open the file I get some non formatted text

**Comment by turt2live** [comment]
What version homeserver and Riot are you using?

**Comment by amiraelsayed** [comment]
I am using version installed on our server and it work in web but not in mobile, keep giving the problem I sent, I just want to know what is the format of file sent and how can I make it run in postman for example

**Comment by turt2live** [comment]
That sounds like a problem with the mobile app then. If you're having the problem on Android, open an issue at https://github.com/vector-im/riot-android. If the problem is on iOS, open an issue on https://github.com/vector-im/riot-ios

The format of the file should be whatever format the file is. For example, if you upload a PNG image then the format is a PNG image.
