### ISSUE TITLE
Inline terms agreement on change IS and IM

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#10539]
This
![dvvfuOvOVaYFruARsvQBdGzm](https://user-images.githubusercontent.com/986903/62866910-f12b1a80-bd09-11e9-85a0-80e987bdb552.png)

**Comment by turt2live** [comment]
I've bundled IMs into this because it'll be largely copy/paste code.

**Comment by turt2live** [comment]
This is blocked on a decision for how to move forward when there's no terms available.

![image](https://user-images.githubusercontent.com/1190097/62953443-c6dd6980-bdaa-11e9-848e-65aefa4ccf50.png)

In the above, the 'no terms' text says continue if you want to, however provides no way to do that. This raises some questions:
1. Do we even want to allow people to continue?
2. If we do let them continue, is that okay for GDPR?

**Comment by turt2live** [comment]
New design:
![image](https://user-images.githubusercontent.com/1190097/63029134-459adb00-be6d-11e9-9dc6-b96d9431abcb.png)

**Comment by turt2live** [comment]
After an epic battle involving me reevaluating my career path, we're changing the design yet again for this. It turns out that our tooltips are non-interactive and popovers don't do what we want. Instead of suffering in silence, we're just going to use dialogs.

New UX (no mockups):
* User enters a URL into the field
* User submits form
* Checking server tooltip
* Four possible cases:
  1. The settings take effect (service has terms, and they are already signed)
  2. Service has no terms (warning dialog)
  3. Terms agreement dialog (existing)
  4. Connection error tooltip

Reference sample screenshots:
![image](https://user-images.githubusercontent.com/1190097/63111402-d09dd300-bf4a-11e9-8669-7d66cc8271f6.png)
![image](https://user-images.githubusercontent.com/1190097/63111441-e4493980-bf4a-11e9-828f-0f5c990ba9fe.png)
*and above for existing tooltips*

**Comment by turt2live** [comment]
IM: https://github.com/matrix-org/matrix-react-sdk/pull/3316
IS: https://github.com/matrix-org/matrix-react-sdk/pull/3317

**Comment by turt2live** [comment]
Both parts have landed
