### ISSUE TITLE
Riot Web shows translated strings as missing translation (lab settings)

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-web#10586]
Riot Web shows already translated lab settings as missing translations:

![DeepinBildschirmfoto_Bereich auswählen_20190817232608](https://user-images.githubusercontent.com/1236369/63217460-2212b180-c147-11e9-8703-08c037072a29.png)

**Comment by jryans** [comment]
Hmm, very suspicious... I am able to reproduce this on develop for de_DE lang. If I disable cache in the browser DevTools, I have seen the issue go away for a bit, but then it can come back if cache is re-enabled.

The translated strings appear to be available in the current strings file, so at the moment I am not quite sure how this is happening.

**Comment by jryans** [comment]
@zzottel, have you noticed other strings affected this way, or is it just these few in the Labs section of Settings?

**Comment by zzottel** [comment]
I just looked around a bit, but the only place where I can find the problem is lab settings. I'm seeing this in Riot Web 1.3.3, btw, and Firefox 68.0.2/Linux.

**Comment by turt2live** [comment]
this is because of double translation: we were trying to translate the German string to German, which obviously doesn't work in our setup. The "missing translation" bit is saying that the text which follows is not in the i18n strings, which in this case is a dead giveaway that we're double translating: the German string won't be in the strings.
