### ISSUE TITLE
Allow users to disconnect from an integration manager entirely in the same way that we support doing this for identity servers

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10696]

**Comment by turt2live** [comment]
This is tricky because of the 3 levels users can have integration managers at: Riot config, homeserver config, and account data. The button would need to store a flag to ignore the settings.

**Comment by afonari** [comment]
This is important for privacy, please prioritize.

**Comment by turt2live** [comment]
We've spent several hours to try and figure out what this means and it's not as trivial as we want. Removing an integration manager means (to us):
* Hiding the integrations button in the room
* Hiding the sticker picker button (for UX, not because we have to - it's a widget)
* Avoiding the use of a whitelist for widget URLs, therefore exposing the integration manager wrapper in widgets
  * This may require design for a "show more info" button to expose the query string
* Hoping widgets are capable of auth, potentially adding more work for us later: #11085 

Where we store this flag is moderately unknown - account data?

**Comment by turt2live** [comment]
no, because there's 3 levels of integration manager configuration and none of which permit a "none" option. The disconnect button is additionally per-user, so we need to be able to detect that and that's difficult.

**Comment by turt2live** [comment]
also: we've proposed https://github.com/matrix-org/matrix-doc/pull/2315 to solve the disconnection problem.

**Comment by turt2live** [comment]
After some long and plentiful discussions, it's not quite possible for us to offer a "disconnect" in the same way. We are however going to offer a way for users to say they don't want to use an integration manager for *provisioning*, which is to say it won't break the app but also prevent you from doing certain things that involve the integration manager.

See https://github.com/vector-im/riot-web/issues/11354 and referenced issues for details.
