### ISSUE TITLE
option to hide images by default

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10735]

**Comment by aaronraimist** [comment]
Requires: https://github.com/vector-im/riot-web/issues/2466

Related/dup: https://github.com/vector-im/riot-web/issues/4286

**Comment by turt2live** [comment]
Tracking this independently of https://github.com/vector-im/riot-web/issues/2466 and https://github.com/vector-im/riot-web/issues/4286 because both of those issues have a larger and more detailed scope. Very much abusing this issue to track an ugly button to plaster over top of images as a short-term solution.
