### ISSUE TITLE
Spec violation: invalid identity server is seemingly quietly ignored

### ISSUE THREAD

**Issue by joepie91** [vector-im/riot-web#10763]
### Description

According to [the spec](https://matrix.org/docs/spec/client_server/r0.5.0#server-discovery):

> Clients SHOULD validate that the URL points to a valid homeserver before accepting it by connecting to the /_matrix/client/versions endpoint, ensuring that it does not return an error, and parsing and validating that the data conforms with the expected response format. If any step in the validation fails, then FAIL_ERROR. Validation is done as a simple check against configuration errors, in order to ensure that the discovered address points to a valid homeserver.
>
> [...]
>
> If the m.identity_server property is present, extract the base_url value for use as the base URL of the identity server. Validation for this URL is done as in the step above, but using /_matrix/identity/api/v1 as the endpoint to connect to.

In other words, as per the specification, homeserver discovery should fail when the identity server URL exists but does not point at a valid identity server.

Currently, the `privacytools.io` homeserver is misconfigured and [points](https://www.privacytools.io/.well-known/matrix/client) at an [invalid identity server URL](https://chat.privacytools.io/_matrix/identity/api/v1), and given the relatively common use of that homeserver, yet seemingly noone reporting to the `privacytools.io` operators that their system is misconfigured and breaking logins, it would seem that Riot does not implement this validation.

### Steps to reproduce

n/a

### Version information

n/a

**Comment by turt2live** [comment]
The warning is obvious on login that the identity server is invalid, for one:
![image](https://user-images.githubusercontent.com/1190097/64395309-0a786b80-d017-11e9-94ff-b355f570f5fe.png)

As for the spec violation: While reading the spec at face value does indicate that when Riot uses the `.well-known` discovery method defined it should fail to let the user even attempt login. However, due to a bug (https://github.com/vector-im/riot-web/issues/10772) this doesn't happen anyways. The part that makes Riot in compliance is the wording: The spec just says that clients *should* use *a* discovery mechanism. The *should* is a recommendation, not a requirement. Further, the spec doesn't say that clients *must* use the discovery mechanism as defined in the spec, just that one is supposed to be used. 

With all that being said: weaseling our way out of this one over a technicality in wording is pretty annoying and not something we should really be doing - we should be following the spec. So, because I personally think the current spec is irritating, I've opened [MSC2284](https://github.com/matrix-org/matrix-doc/pull/2284) to change the discovery process to allow for clients to have optional identity servers and avoid a situation where the user is locked out of logging in all because a privacy-orientated homeserver wants to disable identity server usage.

**Comment by joepie91** [comment]
Yeah, I agree that the spec is a bit irritating here. I just wasn't sure whether there was an intentional reason for defining this behaviour or not :)

If the intention is to get rid of the homeserver discovery failure, I guess this issue can be closed, unless there's a reason to keep it open?

**Comment by turt2live** [comment]
Homeserver discovery should still be a failure, however identity server stuff shouldn't fail. Keeping this issue open until the MSC is in a more stable state makes sense.

**Comment by jryans** [comment]
The MSC has progressed to FCP and we have implemented it in Riot, so this seems safe to close.
