### ISSUE TITLE
Could not restore session

### ISSUE THREAD

**Issue by Yoric** [vector-im/riot-web#10898]
### Description

Just Restarted Firefox for an update. Riot tab displayed "Could not restore session".

### Steps to reproduce

I don't know if it reproduces.

Log: sent    

### Version information

- **Platform**: in-browser

For the web app:

- **Browser**: Firefox Nightly 71.0a1 (2019-09-16) (64-bit)
- **OS**: macOS
- **URL**: https://mozilla-test.riot.im/#/room/#random:mozilla-test.modular.im

**Comment by Yoric** [comment]
Additional details:

- It becomes impossible to rejoin Riot, whether from this tab or another one.
- **Deactivating Firefox Private Network seems to fix the issue.** I don't know if the problem is on FPN or on Riot.
- That's not related to `type:voip` in any way, so I don't know why this label was added.

**Comment by t3chguy** [comment]
:')

**Comment by jryans** [comment]
Sorry to hear you are having trouble! I added the `voip` label because the log includes:

```
Unable to load session SecurityError
e.exports.createNewMatrixCall@https://mozilla-test.riot.im/bundles/5e6b63d216ee957e7492/bundle.js:24:135321
```

**Comment by turt2live** [comment]
Looking into this - I think I might be a firefox issue/feature.

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/1036 is the fix - the tldr (also available on the PR) is that Firefox can throw SecurityError's on access of the classes for WebRTC, even if WebRTC isn't being invoked. This appears to be valid per the spec, but we fall apart when it happens.

When we create a MatrixClient, we set up as much of the VoIP stuff as we can, which is why it prevents the app from loading.
