### ISSUE TITLE
CIDER: Choosing latin input in Chinese IME on OSX removes previous compositions

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#10913]
@rixtox [reported](https://github.com/vector-im/riot-web/issues/7665#issuecomment-532224332) a remaining issue with IME input on CIDER:

> Here is a normal input sequence:
> ![](https://camo.githubusercontent.com/27c9f2abebd11546eb35e3526325e88e4d939095/68747470733a2f2f6769616e742e6766796361742e636f6d2f49646c65536c69707065727941726d79776f726d2e676966)
> 
> But the behavior in CIDER is:
> ![](https://camo.githubusercontent.com/7a3165c3d6c3967769766f89c6cbe04dee664d6c/68747470733a2f2f6769616e742e6766796361742e636f6d2f4f62657365476c656566756c456e676c697368706f696e7465722e676966)

**Comment by bwindels** [comment]
@rixtox I've just been looking into this and have few follow-up questions. I'd greatly appreciate if you have a moment to do the following:

 - which browser (and version) are you seeing this on?
 - Could you please input the same sequence on this website: https://danburzo.github.io/input-methods/index.html ? 
Use the "Simple DOM contenteditable" field on the left, and make sure the list is empty before you start typing (hit clear log if not).
Once done, can you please post the HTML of the page here? (To do this, save the page, and copy the contents of the html file. Don't use "view source" as that won't include the list).

Let me know if you need any help with this. Thank you!

**Comment by bwindels** [comment]
Fwiw, this is what it looks like on Linux (Firefox 69 or Chromium 75) 
![chinese-ime](https://user-images.githubusercontent.com/274386/65438048-6105e800-de14-11e9-9aad-be730ef0b251.gif)

**Comment by rixtox** [comment]
@bwindels 

Previous test was performed on:
OS: macOS Mojave 10.14.6
Browser: Version 77.0.3865.90 (Official Build) (64-bit)

This time I tried on Safari 13.0 (14608.1.49) and the result is even worse:

![](https://giant.gfycat.com/FavorableBitesizedAndeancondor.gif)

IME interface doesn't even show up, letters are enterred backward, etc.

Here are the logged key events:

![](https://i.imgur.com/TxzxjbV.png)

**Comment by bwindels** [comment]
@rixtox Thanks for the feedback. It looks like your test in Safari was done with the old editor (as you have a markdown button). Could you try again after enabling the new editor and refreshing?

Also, is the list of events for safari or chrome?

Thanks again!

**Comment by rixtox** [comment]
@bwindels 
OK. I thought the settings would sync to new browser logins. So I tested in Safari again, and this time it's better than Chrome, but still not correct:

![](https://giant.gfycat.com/UglyFatherlyHylaeosaurus.gif)

As shown in the expected behavior in text editor, the last enter key input is used as a confirmation of choosing latin inputs for the IME, not a new line input. The cursor should stay behind the newly typed latin word "demo". But CIDER on Safari treated it as a new line input and submited the whole input line. As a result there's no chance for me to enter more characters after the "demo" text.

The list of events from my previous comment was from Chrome.

This time I logged the events on Safari too:
![](https://i.imgur.com/E69hurA.png)

**Comment by bwindels** [comment]
Hi @rixtox , thanks for testing again. We've noticed the same thing in Safari when testing, but I can't see how to fix it for now, so tracking this issue at https://github.com/vector-im/riot-web/issues/10957 for now.

I've just merged https://github.com/matrix-org/matrix-react-sdk/pull/3477 to try to fix the issue you reported in Chrome. If you could try again in Chrome on latest /develop, that would be much appreciated!

**Comment by rixtox** [comment]
@bwindels Chrome is working properly now.
