### ISSUE TITLE
Page title shows outdated channel name

### ISSUE THREAD

**Issue by callahad** [vector-im/riot-web#10940]
### Description

The current channel was added to the document title by matrix-org/matrix-react-sdk#3471, fixing #4454, but the implementation is buggy on my end.

Instead of showing the current channel in the title bar, I see the previous channel.

### Steps to reproduce

1. Sign into https://riot.im/develop/, the title will be correct
2. Click in the sidebar to switch rooms, the title will not change
3. Begin typing a message in the room, the title will update and be correct again

Sometimes the title updates without further interaction, though I'm not sure what causes that.

Clicking a second time on the room name also updates the title.

### Version information

- **Platform**: web (in-browser)

- **Browser**: Firefox Nightly 2019-09-13
- **OS**: NixOS Linux
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
This is weird; I'm failing to repro it on FF Nightly (Sep 23rd) on macOS, nor FF 69.
It looks like updates to the title tag may be throttled somehow?  This is particularly weird as it's not react managing the title tag, but a really simple assignment to `document.title`. This gets called every time the room URL is changed when you click on a different room, so unless it's throwing an exception (which it isn't, according to the rageshake) then as long as the URL bar is updating the title tag should be updating too.

Unless `this.state.currentRoomId` is getting out of sync with invocations to notifyNewScreen()?  Perhaps due to React 16 weirdness?

I've added some temporary debug to develop at https://github.com/matrix-org/matrix-react-sdk/commit/b85dc7b5a887d00971e40b7bf03dda09689d5f85 to try to figure out what's going on - @callahad if you can check the console to see if the "updating subtitle as" lines say they're setting the correct subtitle at the right time or not or not it'd be massively appreciated.

**Comment by ara4n** [comment]
actually, i think i see the bug - it is indeed the react state getting out of sync.

**Comment by ara4n** [comment]
i believe matrix-org/matrix-react-sdk@3ce47a018 should fix this. @callahad please lmk once [CI has done its thing](https://buildkite.com/matrix-dot-org/matrix-react-sdk/builds/2490).

**Comment by callahad** [comment]
Yep, works as expected now!
