### ISSUE TITLE
Notification count in title should be before channel name?

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#10943]
I got a little confused about what the number meant, as it looked to be the number of missed notifications for the channel in the title rather than for the whole account. e.g. instead of `Riot | #riot-dev:matrix.org [5]`  maybe it should be `Riot [5] | #riot-dev:matrix.org`? (Or even include both global and per room counts and have `Riot [5] | #riot-dev:matrix.org [1]`?)

**Comment by erikjohnston** [comment]
Also: If the room name is too long you can't actually see the notification count in the browsers tab title.

**Comment by marckell** [comment]
Same suggestion. It doesn't take too many tabs or too long of a room name to make the count not appear:

![screenshot](https://user-images.githubusercontent.com/7455552/66510377-ca7b2d00-ea89-11e9-86f4-929d2d74b62e.png)

I've enabled browser notifications, but it's not ideal since I'm not always looking at the browser. Glancing at the tab for the count has been very handy in the past.
