### ISSUE TITLE
edits to unsent messages no longer seem to work

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11035]
the edits seem to get silently discarded unless we have a remote echo for the msg

**Comment by lampholder** [comment]
Our best intelligence suggests that this is occuring regularly, and that editing unsent messages is a commonly-used feature. We therefore agreed that this is something we should keep on our top priority issue list (making this note because we've had the conversation a couple of times as to whether this warrants urgent investigation and resolution).

**Comment by bwindels** [comment]
I can't reproduce edits getting permanently lost (which is how I interpret the title), but local echo doesn't work indeed. The edit is only shown when the event for the edit (and not just the original event) has a remote echo. Can you confirm that this is not an issue with local echo and you're actually never seeing the edit show up, even after waiting for a while (depending on server perf)? If you don't, does refreshing make it show up (e.g. did the edit get sent out but we didn't handle the remote echo correctly?)

FWIW, we've never supported local echo for edits to unsent events, as the pending events infrastructure in the js-sdk currently has no easy way to support local echo for relations to unsent events, see also bottom of https://github.com/matrix-org/matrix-react-sdk/pull/3097#issue-287595940.

One thing we could potentially improve without too much work is to show the local echo for the edit once the remote echo for the original event has been received. If local echo is indeed the problem here, that might alleviate things a bit.

**Comment by bwindels** [comment]
Removing fire because of unable to reproduce.

**Comment by ara4n** [comment]
closing in favour of https://github.com/vector-im/riot-web/issues/11834
