### ISSUE TITLE
Click effect on room tags sticks around

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11189]
Eg: clicking on People causes People to be highlighted alongside the room. One should be highlighted, or better yet the tag doesn't stay highlighted

**Comment by jugglinmike** [comment]
It seems the UI in this area has changed in recent months, so I'm wondering if if this issue is still relevant.

In your example, does "People" refer to room members? Currently, when I click on a room member's name, then no highlighting occurs (instead, the member's name is added to the message composer input). When I click on a room member's avatar, then the room member list is replaced with a view dedicated to that member.

**Comment by turt2live** [comment]
I think we fixed this. I was meaning the header, but considering I haven't tried to smash a keyboard over my monitor since October, I think it's fine now.
