### ISSUE TITLE
Animated Profile Pictures

### ISSUE THREAD

**Issue by SethX3** [vector-im/riot-web#11481]
**Is your suggestion related to a problem? Please describe.**
This is not a problem at present.

**Describe the solution you'd like**
I'd like to be able to use a gif as a profile picture and have the animation play.

**Additional context**
Some platforms such as Discord allow for animated profile pictures, it would be nice if Riot would allow this as well.

**Comment by anoadragon453** [comment]
Riot does in fact support this. The problem is that your homeserver's media repo does not support creating animated thumbnails from gifs. matrix.org (and Synapse by default) uses Synapse's media repo, which lacks some features.

If you would like animated avatars, you'll need to use a homeserver that features a media repo that supports animated thumbnails. One such media repo is https://github.com/turt2live/matrix-media-repo/

In the meantime, I suggest making an issue for Synapse's media repo to support animated avatars [here](https://github.com/matrix-org/synapse/issues/) (I couldn't find an existing issue about this).
