### ISSUE TITLE
Grey shields should mean "encrypted but of unknown trust" rather than unencrypted(!)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11547]
<img width="170" alt="Screenshot 2019-11-28 at 10 06 38" src="https://user-images.githubusercontent.com/1294269/69797026-eddb7200-11c6-11ea-94c6-230425d0a83b.png">

The fact that this is an unencrypted message popping up in an encrypted room (in this instance because it precedes encryption being enabled) feels a bit weird - there's something solidly reassuring about a black shield, whereas in practice this msg wasn't encrypted at all!

**Comment by nadonomy** [comment]
Design proposal with rationale detailed in Figma here: [https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=0%3A1](https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=0%3A1)

**Comment by uhoreg** [comment]
@nadonomy is there a different design for events that are *expected* to be unencrypted (such as joins), or should they look like all the other unencrypted events?

**Comment by nadonomy** [comment]
@uhoreg ah good question. I think the most sensible thing to do is to not decorate them with warnings either, with the rationale being:

(a) Users don't care or shouldn't have to care about the distinction between messages and events— the mental model needed for them to make sense of any encryption decoration seems like a net loss
(b) We can ensure the app & decoration is correct by ensuring  micro copy refers to messages being encrypted, rather than events or rooms

**Comment by turt2live** [comment]
I think this is the section @nadonomy is referencing? (the figma is a bit large)
![image](https://user-images.githubusercontent.com/1190097/70083112-07b2f580-15c9-11ea-93be-0e2c9780eab6.png)
