### ISSUE TITLE
Handle errors when uploading key signatures

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11574]
We currently do not check for errors when uploading key signatures (JS SDK method `uploadKeySignatures`). This is probably because the failures are returned inline in the response for each signature, rather than in the top-level HTTP response code.

We should track these errors and communicate failure to the user somehow.

**Comment by nadonomy** [comment]
When does this happen specifically in the user journey? Does it happen when bootstrapping? (as I see it was referenced in #11212). Can it happen in any other instances?

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/75038947-73fa1280-54af-11ea-9a54-81a899065afa.png)

**Comment by nadonomy** [comment]
I think given the failure mode is that users can't complete their goal— out of pragmatism for now I'd throw up an error message in a modal, where they can hit OK and start doing whatever they were attempting again.

If this turns out to be a very common failure mode we could polish this into much nicer contextual error feedback.

**Comment by foldleft** [comment]
Reference: https://github.com/matrix-org/matrix-doc/blob/master/proposals/1756-cross-signing.md
