### ISSUE TITLE
Poor feedback when favouriting rooms

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11654]
Riot Web doesn't really respond when favouriting rooms, presumably while waiting for server latency. We should consider making rooms move to the room list immediately, and then display errors contextually if needed, or less desirably some kind of loading state.

**Comment by turt2live** [comment]
This is due to the UX requirement of not shuffling the room list around when you're interacting with it, and if you're favouriting the room you're reading then the requirement that it can't move either.

We already debounce the server in Riot, but the changes are not rendered for these requirements.

**Comment by turt2live** [comment]
Should be fixed in the new room list. If not, please open a new issue.
