### ISSUE TITLE
Message decoration with shields

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#11880]
Update message decoration in rooms as appropriate.

![2020-01-16 at 10 08](https://user-images.githubusercontent.com/279572/72515739-51d5fa80-3848-11ea-8d05-13d51883036b.png)

**Comment by foldleft** [comment]
I think it's better to not gate this behind cross-signing – if the user has enough context to do a cross-signing check, the messages shouldn't flip states based on whether it's on or off

**Comment by jryans** [comment]
Hmm, I might be missing some details, but in general, we'd like all the iconography and feature as part of cross-signing to feel like they're landing together as a package.

The design above suggests that the reason that the encrypted messages don't have a marker is because of the room decoration, and the room decoration is behind the labs flag, so it suggests this should be as well.

**Comment by foldleft** [comment]
I'd like some clarity on how to handle this temporally.

If a user logs out of riot-web, their device goes away and we can no longer verify their cross-signed messages.  These are now in an `unknown` state.  I suspect this may be something we need to represent in its own way.  We've simply lost historical context.

Secondly, if a user cross-signs their device, the messages sent under that device key become retroactively verified.  That's fairly straightforward in the UI, and I plan to do it. I mention it here just in case :)

So, the question (for @nadonomy, probably?) is, what should happen when a device goes away and a message becomes less verified?  The only place we know that a message was ever verified is in the client.  Either we:

a) Update message states immediately.  If you're in the middle of a conversation with someone and they log out, all of their messages suddenly go to `unknown` state.  The ones sent since you last checked may, or may not, have ever been `verified`.

b) Keep `verified` status in local memory.  Old messages continue to be represented as `verified`, but, if the user ever refreshes the page, the context is lost and they become `unknown`.

I feel there's a tradeoff between annoying and confusing the user.

**Comment by foldleft** [comment]
For the moment, I think my implementation will proceed as follows:

1. Update both ways. If a device goes away, immediately act on that new context.  A refresh shouldn't change what the user sees.
2. Add an internal verification state called `user-verified`.   Messages where we've lost device context have a "unverified but encrypted" shield if we can still verify the user, and a `warning` shield otherwise.
