### ISSUE TITLE
Ask if the other user / device scanned the QR code

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12201]
For self-verif and other user

 - [x] update `ReciprocateQRCode` with spec changes
 - [x] set `reciprocateQREvent` on `ReciprocateQRCode` when ready to receive user interaction, and emit `show_reciprocate_qr` event when setting it.
 - [x] add UI in `VerificationPanel` to display this step.
 - [x] test
 - [x] polish design
 - [x] use correct error code when clicking no

**Comment by jryans** [comment]
Marking needs-design to work out designs for this / decide whether it's actually required security-wise.

**Comment by ara4n** [comment]
So I went through this extensively with @nadonomy.  The conclusions were:

 * Yes, we need this from a security perspective.  Basically: if alice scans bob, bob should only trust alice afterwards if alice's device is actually showing a ✅ otherwise he may end up trusting an attacker.
 * From a design perspective, I don't think we have artwork for this yet, but I strongly suggest we implement it anyway with a placeholder dialog after scanning that says "Does Alice's phone show a tick? Yes/No" - and once we have assets we tweak the wording/graphics appropriately.  If "yes", Bob should trust Alice. If "no", Bob should not trust Alice and should take you to a "you're under attack" warning.

@nadonomy please can we have assets?

**Comment by nadonomy** [comment]
@ara4n @BillCarsonFr @manuroe @jryans I've added a first pass of the scan code confirmation to Figma here:

https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=3915%3A8858

Does this match expectations? If not, best to ping in cross-signing internal for us to hash out the requirements better together.

@ara4n Relatedly, do we need to shield from the same attack when verifying your own devices?

**Comment by jryans** [comment]
Thanks, design looks reasonable to me!

**Comment by nadonomy** [comment]
> Thanks, design looks reasonable to me!

Great! I had a sync with @BillCarsonFr & @manuroe to validate mobile and it matched our expectations there too, so believe we should be all good.

> @ara4n Relatedly, do we need to shield from the same attack when verifying your own devices?

On this, I've added a footnote to the iOS comps with a simple copy variation for us to use in this context.

**Comment by bwindels** [comment]
Spec https://github.com/matrix-org/matrix-doc/pull/1544
