### ISSUE TITLE
Shortcuts: Cmd/Ctrl-. to toggle the right panel

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12248]
We should consider adding Cmd/Ctrl-. as a shortcut to toggle the right panel, matching popular apps like Slack.

**Comment by madduck** [comment]
Please make it configurable.

**Comment by nadonomy** [comment]
> We should consider adding Cmd/Ctrl-. as a shortcut to toggle the right panel, matching popular apps like Slack.

SGTM! In the long term, I think there's some things to untangle re whether this shortcut should also collapse the left panel, but I'd advocate for us to defer that until later.

**Comment by t3chguy** [comment]
How does one *toggle* the right panel, closing it is obvious but then should we re-open whatever state was last open? What if that state was mid-way through verification which has since timed out and whatnot? Should it just be the latest of the 3 top-level options (member list, file list, notif list)

**Comment by jryans** [comment]
> Should it just be the latest of the 3 top-level options (member list, file list, notif list)

Hmm, yes, I suspect this would be the natural approach to start with.
