### ISSUE TITLE
Linux 19.10 audio device bug

### ISSUE THREAD

**Issue by TheChiefMeat** [vector-im/riot-web#12243]
### Description

The linux client on 19.10 Ubuntu-based OS's doesn't seem to respect the selected audio input and output devices.

### Steps to reproduce

Install qjackctl.
Create two virtual outputs.
Select one virtual output in the Ubuntu sound settings.
Select the other virtual output in the riot client.
Start a call.
(possible step needed) go back into the sound settings for the OS. At this point riot will start broadcasting through the OS's selected audio device instead.

It is expected that the audio for riot is sent to the selected virtual output, but instead the audio comes through the other virtual output.

riot-web version: 1.5.8
olm version: 3.1.3
linux: Pop_OS 19.10

I couldn't replicate this bug in Ubuntu 18.04 or Zorin 15.1.
![audio](https://user-images.githubusercontent.com/17432768/73799262-5e95a080-47ad-11ea-87f7-cacd36838c6a.png)
![riot-audio](https://user-images.githubusercontent.com/17432768/73799264-5fc6cd80-47ad-11ea-8a80-1006e61c7ead.png)

Edit: I found that by installing `pulseaudio-volume-control,` and then setting riot (which for me appears as "chromium" to the correct output device, it works fine, but if you go into the OS's sound/volume settings, the riot client will reset back to the OS's default audio device, instead of respecting the audio device set in the riot client (this bug/issue is also true for other chromium based clients like Discord)).

**Comment by jryans** [comment]
Thanks for the feedback on this. From your additional comments, it sounds like this applies to anything based on Electron / Chromium, so unfortunately I don't think Riot can do anything here.

If there is something we can do, please reopen.

**Comment by ve7it** [comment]
I can confirm this issue occurs with arch linux as well. Every time I start my system, I have to go into the riot setting for audio/video and reset all 3 devices. They consistently reset to "default" or "default device". Since setting these items is allowed in riot-web, why are they not being remembered? Is there an error in in the settings database/ini file/jason file? I have not found where these settings should be loaded from and saved to. Perhaps a corrupt config file or a permissions problem, or are they never being saved to non volatile storage?
cheers
