### ISSUE TITLE
Shortcuts: Go to the first unread message in the current channel

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#12249]
It would nice to have a quick way from the keyboard to jump to the first unread message.

**Comment by pwr22** [comment]
I'd also be interested in this and potentially could take a look at implementing it if wanted?

**Comment by nadonomy** [comment]
Are there any popular/widespread keyboard shortcuts for this in other apps that would make the most sense to adopt? It'd be ideal to leverage existing semantics so users can translate their muscle memory and affordance from elsewhere.

**Comment by pwr22** [comment]
That's what I'm wondering too - I don't think slack has one but I don't use it much and my google-fu might be weak.

**Comment by bwinton** [comment]
Slack's behaviour (which I might argue makes a lot of sense 😉) is to automatically go to the first unread message when joining a channel, and then using `Esc` to mark all messages as read, and jump to the bottom.

That behaviour would also fix a related, uh, issue(?) I've seen, where I use the button to jump to the first unread message, then scroll quickly to the bottom to attempt to mark all the messages as read, but because I'm scrolling so quickly, some of the messages in the middle don't get marked as read, so the button shows up again…

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/77857547-110a4280-71f6-11ea-820d-5b89b4feebda.png)
Discord ^

**Comment by t3chguy** [comment]
@bwinton thats https://github.com/vector-im/riot-web/issues/11235
