### ISSUE TITLE
Connectivity to the server has been lost

### ISSUE THREAD

**Issue by supagu** [vector-im/riot-web#12293]
### Description

For about a week now the riot users in my house have been unable to access riot via the household internet. However when using mobile data it works fine. For both android and web version.

We have no issue access matrix via the python api on the same network.

I assume there is some ip blocking happening thats only just started in the last week or so. I think this because I have been having similar issues with other websites which ask for captcha verification.

```
Connectivity to the server has been lost.
Sent messages will be stored until your connection has returned.
```

### Steps to reproduce

Open riot, login, attempt to continue a conversation

### Version information

- **Platform**: web (in-browser) or desktop?
both web app and android
android bug posted here: https://github.com/vector-im/riot-android/issues/3421

For the web app:

- **Browser**: firefox, falkon
- **OS**: manjaro linux
- **URL**: riot.im/app /

**Comment by aaronraimist** [comment]
Riot connects directly from your computer to your server, I don't think it is blocking your IP address. Riot also only asks for a captcha during registration, and only if your homeserver is configured to require a captcha.

What do the logs in the browser console say?

**Comment by supagu** [comment]
hrmm it is working again today!

**Comment by eMPee584** [comment]
What just helped me debug this (for anyone also landing here via web search) is to open your browser's development tools (F12) and investigate any errors on the **network** tab. We had `nginx` throwing a 502 on all the paths handled by workers because we had set it up in a hurry with the non-persistent container-IP in the nginx config instead of a proper hostname/resolver solution (which we had had troubles with at that time..). An automatic reboot triggered tonight and of course changed that ephemeral container IP, which took me a while to figure out and `:%s/172.18.0.4/172.18.0.6/gc` hotfix ... :sweat_smile:
