### ISSUE TITLE
peeking as a guest prompts you to sign up at first... 

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12307]
previously it just showed a blank timeline while it sorted out peeking ,rather than a 'to view you must sign up' msg

**Comment by flyinghuman** [comment]
### Steps to reproduce

1. make a room public and access the shareable link
2. "Join the conversation with an account" pops up, so that you cannot see the public available chat
3. Click on + Communities
4. Click another time on # Communities to close it
5. you are redirected to standard-login page
6. now use the browser back button
7. you see the public chat with content and only a small reminder on bottom to login if you want to join the conversation with an account

Describe how what happens differs from what you expected:

The expected behavior would be Number 7 straight from beginning.

### Version information
- **Platform**: web
- **Browser**: Chrome, Firefox latest release
- **OS**: Windows
- **URL**: If a private server, what version of riot-web: 1.6.0

OKAY:
![okay](https://user-images.githubusercontent.com/3713548/81808143-91270600-951f-11ea-9675-cf2557429853.JPG)

Not Okay:
![not_okay](https://user-images.githubusercontent.com/3713548/81807785-ffb79400-951e-11ea-8ce8-b83fe91f6e65.JPG)

**Comment by t3chguy** [comment]
So the flow here is

1. Resolve room alias (takes a long time for some reason)
1. Wait for a ready matrixClient
1. Try to peek (shows peeking spinner)
1. Show timeline if successful.

The peeking state didn't show until stage 3, moving it to stage 1 eagerly is an improvement.
![image](https://user-images.githubusercontent.com/2403652/82325052-81516b00-99d2-11ea-8b2b-47ddfabe6167.png)
