### ISSUE TITLE
ManageEventIndexDialog: "Indexed rooms" wording

### ISSUE THREAD

**Issue by stoically** [vector-im/riot-web#12334]
Issue type: ui/ux suggestion

Currently the `ManageEventIndexDialog` says ["Indexed rooms: $processing of $total"](https://github.com/matrix-org/matrix-react-sdk/blob/c3f4eaf4e551cb4e22f5314d2be2736153b7c564/src/async-components/views/dialogs/eventindex/ManageEventIndexDialog.js#L147), personally I find that confusing as it kinda suggests that, if no rooms are currently processed, that no rooms are indexed at all (e.g. "Indexed rooms: 0 of 10"). Maybe two lines saying something like

- Monitoring $total rooms in total
- Currently working in $processing rooms

communicates more clearly what actually happens.

**Comment by jryans** [comment]
Sounds like a reasonable improvement, I agree it's confusing as written. Feel free to submit a PR if you'd like to! 😄

**Comment by poljar** [comment]
Wouldn't the second line a bit overlap with the info we have presented in the last line? We present first how many rooms are being indexed and after that which one is indexed, and if we're idle it's a bit silly.

Picture follows.

![image](https://user-images.githubusercontent.com/552026/74520923-cf109000-4f18-11ea-9390-241da8c2f908.png)

**Comment by jryans** [comment]
In my opinion the current "X out of Y" presentation is quite confusing, because the "good" / "idle" state will apparently say "0 out of 10 rooms", which is hard to read at a glance, because you typically expect the "idle" state would be 100% complete (10 out of 10), but that's not actually what these numbers mean.

I actually like the look from @poljar's image above, as I think it's easier to understand at a glance. @poljar, can you also capture what it looks like with some rooms actively being indexed?

**Comment by poljar** [comment]
I aggree that it's confusing, I just find it redundant to state twice that it's not doing anything.

The case where it's doing something looks good. Picture follows, now with funny cats in the background.
![image](https://user-images.githubusercontent.com/552026/74523672-d9815880-4f1d-11ea-8bd8-d4d733ed89f8.png)

**Comment by stoically** [comment]
I'd agree that merging the last two lines in this case might be better. Maybe just `Downloading messages in N rooms` and omitting the room name?

**Comment by stoically** [comment]
Or combining it into something like `Downloading messages from N rooms, currently in $room`.

**Comment by nadonomy** [comment]
Apologies I'm late on this, but.. to untangle a few things:

> Currently the ManageEventIndexDialog says "Indexed rooms: $processing of $total", personally I find that confusing as it kinda suggests that, if no rooms are currently processed, that no rooms are indexed at all (e.g. "Indexed rooms: 0 of 10"). 

Isn't this true?

**Comment by nadonomy** [comment]
We should really be striving to exercise clarity through brevity, and this copy should be as verbose as possible. By using whole sentences instead of simply stated information declared with colons we force the eye to read the whole thing to parse rather than being able to glance.

I think the problem here is the logic rather than the copy. If instead of "Indexed rooms: $processing of $total" we displayed "Indexed rooms: $processed of $total" then the user would see that number tick up and eventually complete to e.g. 10 of 10, which solves the core issue.

**Comment by poljar** [comment]
Just to double check, we are all aware that the number of $processed rooms will not just tick up?

The number of processed rooms will start at 0, grow to the number of encrypted rooms, but at any point in time a gap in a timeline can appear. In this case the room will be crawled again (not to the start of the timeline though).

**Comment by nadonomy** [comment]
I think if it's always "Indexed rooms: '$processed of $total" then that's totally fine, if you see that $processed reduces to less than $total you can infer that it's processing, and see it go back up again.

**Comment by poljar** [comment]
Updated the PR. Pictures follow.

Working:
![image](https://user-images.githubusercontent.com/552026/76095613-e21cfa00-5fc4-11ea-85b0-5d1adb334027.png)

Idle:
![image](https://user-images.githubusercontent.com/552026/76095588-d3364780-5fc4-11ea-8d68-9bca9cbb101d.png)

**Comment by nadonomy** [comment]
@poljar much clearer, thanks!
