### ISSUE TITLE
When Tom tries to verify me, it takes ~30s to display my DM with him, during which time there is zero feedback

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12478]
I click on 'accept' on the toaster and nothing happens.  In practice the verification does eventually appear in my existing DM with him, but it looks as if I'm rejoining the room or something which takes tens of seconds, during which time there is zero UI feedback. We should at least switch to the right DM immediately.

**Comment by bwindels** [comment]
rageshake: https://github.com/matrix-org/riot-web-rageshakes/issues/2302

**Comment by bwindels** [comment]
Need to have a closer look, but looks like sending the `ready` is taking long because of key downloading/megolm things. We should probably indeed switch the order of `await request.accept()` and navigating to the room & right panel in `VerificationRequestToast.accept` and make sure we have a spinner there while we're sending our acceptation (that's probably not a word?).
