### ISSUE TITLE
New invite dialog flashes up (correct) results and then replaces them with incorrect ones.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12488]
The fact we're flashing up results which then vanish is bad in the first place - it's even worse that the results being flashed up are correct, but then get replaced with broken ones. e.g:

https://matrix.org/_matrix/media/r0/download/matrix.org/WmoJiwRdwQSXCoVqHhEjCPTB

**Comment by turt2live** [comment]
This is extremely likely to be https://github.com/vector-im/riot-web/issues/12143

**Comment by ara4n** [comment]
#12143 seems to describe a different problem - that synapse doesn't handle partial mxids sensibly?

Whereas this is:
  * [ ] we flash up WIP results which then vanish, which is bad UX. Surely we should suppress WIP results rather than whisk them away from under the mouse cursor.
 * [ ] the results we replace with are bad, but beyond being partial mxids: `neilalexander` is not a partial mxid.

**Comment by turt2live** [comment]
They're the same premise, but extremely badly documented as such: https://github.com/vector-im/riot-web/issues/12143 has the underlying cause of Synapse's directory results being not great and taking precedence over the dialog's own calculation. The flashing UX is a function of the request to the server that we can't really avoid, but we can improve the suggestions to the user by scoring both the dialog's own suggestions and the user directory results. This *should* result in less jumping/flashing because `neilalexander` would ideally show up as the first result with other neilalexander-looking types in the 2nd and beyond results.
