### ISSUE TITLE
new X button to dismiss read marker is hard to see on dark theme

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#12640]
the circle is fine, but the 'X' is a darker grey that isn't as visible

**Comment by aaronraimist** [comment]
<img width="66" alt="" src="https://user-images.githubusercontent.com/5855073/76132916-01bf1d00-5fdb-11ea-8722-7490a119ba0c.png">

**Comment by turt2live** [comment]
The top circle was never that bad :(

**Comment by anoadragon453** [comment]
![image](https://user-images.githubusercontent.com/1342360/76153305-0f9b9d80-60c2-11ea-9761-17abb1a1bceb.png)

This is what I see.

**Comment by anoadragon453** [comment]
@aaronraimist Are you using a non-standard theme? If so, maybe we need a new class for the top-arrow button.

**Comment by turt2live** [comment]
if it is a custom theme, a new issue would be best. We're trying to avoid having a thousand classes/variables though.

**Comment by aaronraimist** [comment]
No that is the standard dark theme. The arrow being missing is not not 100% reproducible. Sometimes it is there, sometimes it loads in after a few seconds, sometimes it never loads and can only be fixed by a page refresh. I was actually just trying to show how the bottom button was hard to see. The arrow being gone from the top circle has happened to me for a while, not a super recent regression.

**Comment by jryans** [comment]
Let's focus this issue on just the bottom X then and track the rest separately.
