### ISSUE TITLE
uBlock Origin on FF stops the jump-to-bottom button appearing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12718]

**Comment by Caspy7** [comment]
The culprit is the "Fanboy's Annoyance" blocklist under the "Annoyances" category, found in the filter lists tab of uBlock Origin preferences.

The workaround is to disable cosmetic filtering for the site (I'm using chat.mozilla.org but perhaps other riot instances are effected). 

The fix is probably to attempt to contact whoever maintains that list.

**Comment by Timvde** [comment]
After some investigation by Caspy7 and me, we found out that:

1) The culprit filter list is "Fanboy’s Annoyance"
2) The culprit filter rule is `##div[title="Scroll to bottom of page"]`

**Comment by Caspy7** [comment]
For illustrative purposes, I'm attaching a screenshot of the button to click to workaround it.
![image](https://user-images.githubusercontent.com/3854676/76574310-e4ca9400-6489-11ea-9e25-8111388e3bda.png)
Click the uBlock Origin button in your toolbar, on the bottom row of buttons in the middle there is an "eye" button, click that (while viewing the site).
