### ISSUE TITLE
Alt+Up shortcut change is surprising to existing users

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12819]

**Comment by t3chguy** [comment]
See the keyboard shortcuts dialog, it is now control alt up. Alt up is the slack shortcut for go one room up.

**Comment by t3chguy** [comment]
(this was signed off on by Ryan and Matthew)

**Comment by turt2live** [comment]
I'm not sure that the best decision was made here to be honest... the shortcut might now be consistent with Slack, but it's completely disorienting for existing users. Can we consider at least a tooltip that says "Hey, looks like you're trying to access your composer history - we've changed this to Ctrl+Alt+Up"?

**Comment by jryans** [comment]
Hmm, but how would we know you are "trying" to access composer history as opposed to moving rooms in order to present such a message...?

**Comment by t3chguy** [comment]
/me definitely thinks this is not of scale `release-blocker`

**Comment by turt2live** [comment]
> Hmm, but how would we know you are "trying" to access composer history as opposed to moving rooms in order to present such a message...?

`if (numPrevSessions > 1 && firstTimeUsingShortcutThatWeKnowOf) { warn() }`

We can get the number of previous sessions through metrics like rageshakes or stored syncs. In a future update (1.6?) we could remove the check altogether as we would have caught most people.

**Comment by t3chguy** [comment]
if we're doing heuristics then it should check if the user has seen the keyboards popup, as in that case they do not need the message

**Comment by turt2live** [comment]
That would falsely catch the people who would expect it to do room list things after never using the app before?

**Comment by t3chguy** [comment]
`numPrevSessions > 1` would count them out though no?

**Comment by turt2live** [comment]
Ah, I thought you meant instead of what I proposed. It'd come down to design for whether or not we show the dialog or just tell people it is different.

**Comment by jryans** [comment]
I do agree that it's not nice to suddenly change existing shortcuts like this, and ideally we might have some messaging to guide people through the change.

However, at the current time, I don't think we have bandwidth to design and implement such guidance with everything else already in flight. 😞 Since we happen to also be shipping the new shortcuts dialog in the same release, I am hopeful that will aid in clearing up some confusion.

If we consider shortcut changes in the future, I'd like to have more tools to work with, such as:

* Anonymous metrics of how often a given a shortcut is used
* [In-product release notes / what's new for releases](https://github.com/vector-im/riot-web/issues/9899)
