### ISSUE TITLE
Verifying my new /develop from an old Nightly failed on Nightly but not /develop

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13009]
Long story short, I got logged out of /develop and needed to log back in. I started verifying myself from an old Nightly build for Windows, verified the emoji, and then got 'cancelled' on Nightly but a green checkmark on /develop.

Logs attached.

**Comment by turt2live** [comment]
slightly different failure mode for Nightly -> develop again (verifying from right panel). Nightly said I cancelled, but develop was sat staring at this:
![image](https://user-images.githubusercontent.com/1190097/78290977-d8ae8100-74e1-11ea-8d8c-a353d3a40e9f.png)

**Comment by jryans** [comment]
The Windows nightly is (unfortunately) several weeks old at this point, so in some ways I am not surprised, as we've landed many fixes in this area.

Looking at the logs, it appears JS SDK device list handling blew up on a failed signature, which I believe is fixed by https://github.com/matrix-org/matrix-js-sdk/pull/1269, so I don't think we need to track this further for now.
