### ISSUE TITLE
Send a reply lingers as a placeholder after sending a reply

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13063]

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/4331
Originally fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3990

Not sure why https://github.com/matrix-org/matrix-react-sdk/pull/4331/files#diff-334804109a89457b8cc14800ce92e4c0L97 switched from DidUpdate (which is safe) to WillUpdate (which is unsafe)
