### ISSUE TITLE
Rename defaultCountryCode config setting to default_country_code …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13088]
Maybe the `defaultCountryCode` config setting should be renamed to `default_country_code` to match other config setting names, like for example `default_federate`, and `default_theme` …

**Comment by fooness** [comment]
Same would maybe be possible for `showLabsSettings`, `welcomeBackgroundUrl`, `authHeaderLogoUrl`, `authFooterLinks`, `roomDirectory`, `embeddedPages`, `welcomeUrl`, `homeUrl`, `settingDefaults`, `preferredDomain` …

**Comment by turt2live** [comment]
We're actually going the direction of `camelCase` settings, and don't currently have a plan to migrate any of them to something else (mostly because it's complicated). 

It's largely an aesthetic concern with the config, but we would accept PRs which make it right and backwards compatible. Please double check with us in #riot-dev:matrix.org first to make sure we're on the same page though.
