### ISSUE TITLE
Leaving Riot

### ISSUE THREAD

**Issue by KOYK** [vector-im/riot-web#13154]
Hi I came from discord hoping that riot will be a safe place and secure for my privacy, But unfortunately the inability to set up a private server for my family and friends and the inability to have an easy environment and easy accesses to basic features like group calling, streaming game related videos. It really makes it hard to consider it a discord private alternative.

But let me put it on a list.

- Running your own jitsi server doesnt work with Riot/Matrix, especially not when using the Modular/Scalar widgets. You are forced to used the integrated jitsi which makes a lot of problems: starting peoples webcam's by default, low video streaming bandwidth, inability to share screens, etc.

- Why doesn't simple VoIP conferencing work with TURN? 1:1 works, but even with widgets disabled, group calls immmediately become Jitsi calls.

These are the only things that are missing for our community to move from discord on to Matrix

**Comment by t3chguy** [comment]
> But unfortunately the inability to set up a private server for my family and friends

It is very easy to set up a private *server*, unless you mean what Discord calls a "server" which is not an actual server and internally they actually call a "Guild"

> Running your own jitsi server doesnt work with Riot/Matrix

Yes, it does. https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi

> Why doesn't simple VoIP conferencing work with TURN? 1:1 works, but even with widgets disabled, group calls immmediately become Jitsi calls.

Because full-mesh VOIP consumes a *LOT* of upload bandwidth which yields a poor experience even in developed countries like the UK on their average ADSL2+ internet connections.

**Comment by jryans** [comment]
Sorry to hear you're leaving and thanks for the feedback. As mentioned above, some portions of this already have solutions. For any that do not, let's please file separate issues for each as needed.
