### ISSUE TITLE
review 'end-to-end encryption information' dialog

### ISSUE THREAD

**Issue by foldleft** [vector-im/riot-web#13161]
in encrypted rooms, you can look at end-to-end encrypted information with the dropdown menu.  from there you can verify a user, but the dialog to do so pops under the information dialog.  It also looks like it might fire off the old verification flow – we should check this is cross-signing safe

**Comment by jryans** [comment]
Ah yes, you are correct that it has not been updated for cross-signing. https://github.com/vector-im/riot-web/issues/11752 tracks either updating it or removing it, with a stronger desire to remove, so I'll close this and track the overall issue there.

Since we're about to release and this is an actively confusing dialog, I think I may send a PR to at least hide the dialog menu option for now.
