### ISSUE TITLE
Cross-signing verification did not start

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13244]
I started verification from my side in an encrypted room with many people in it. The other user received a DM (I was not switched to it), accepted, and saw nothing. My end was stuck waiting for them to accept.

**Comment by turt2live** [comment]
I had to cancel the verification from my side, which the other party saw as me wanting to verify, but declining. After starting the verification again it was fine - seems like it's just an issue with creating the room.

**Comment by bwindels** [comment]
I can see two verification requests in the logs of the initiator:

The first one is a to_device request going to `@travis:vector.modular.im`, only to device `HNBIOCFEQN`. The receiver side logs show it's device id to be `LGJAMMYQCC`, so that would explain why no dialog was seen on the client. Unsure why the device you were using wasn't yet known by your client. Could it have been federation lag of a newly created device @turt2live?

Just before the request I see that there were no cross-signing keys found: `2020-04-17T18:22:09.165Z I got cross-signing keys for @travis:vector.modular.im: {}`, so that explains why to_device was picked and looks like https://github.com/vector-im/riot-web/issues/12973.

The second one is a DM request, going to room `!EXaNxBZGGxpsjphPHz:t2l.io` which I assume is the DM room created with the same user.

**Comment by bwindels** [comment]
I guess everything from `vector.modular.im` might have been lagging a bit to arrive at `t2l.io`, e.g. cross-signing keys and device updates?

**Comment by bwindels** [comment]
The thing I can't explain so far is why it created a DM before starting the first to_device request. Could you give me the room id of this DM @turt2live? It is not `!EXaNxBZGGxpsjphPHz:t2l.io`, is it?

**Comment by turt2live** [comment]
The room was indeed `!EXaNxBZGGxpsjphPHz:t2l.io`, sorry.

Looks like this might have been federation lag as I can't reproduce it on a test server. Over federation is a bit harder to test as all of my servers are overwhelmed a bit.

**Comment by turt2live** [comment]
@bwindels ^

**Comment by bwindels** [comment]
I can only see traces of `!EXaNxBZGGxpsjphPHz:t2l.io` after sending the first to_device request fwiw, so curious why that room got created ... Which side is the creator @turt2live ?

**Comment by turt2live** [comment]
t2l.io, my real side.

**Comment by bwindels** [comment]
Ok, will check if we're perhaps creating DMs even when starting a to_device verification.

**Comment by turt2live** [comment]
worth noting that I also didn't see the to_device verification come in.

**Comment by bwindels** [comment]
> worth noting that I also didn't see the to_device verification come in.

This is because it wasn't sent to the device you rageshaked from. I was assuming because it was a new device and the device update was slow because of federation lag?

**Comment by turt2live** [comment]
That device also didn't see it, but it was alive. Definitely sounds like federation lag then. Is there anything that needs actioning besides making Synapse go faster?

**Comment by bwindels** [comment]
I would just check that we don't create DMs for to_device requests, will have a look tomorrow.

**Comment by bwindels** [comment]
Could not spot anywhere where it would create a DM when doing to_device verification ... not sure what you saw :man_shrugging: Are you ok to close this then?

**Comment by turt2live** [comment]
Yea, let's close this.
