### ISSUE TITLE
Kosovo +383 country code in registration page not showing

### ISSUE THREAD

**Issue by betimi91** [vector-im/riot-web#13273]
We have implemented Matrix/RIOT for our university which soon can be 21k users in total but in registration page of RIOT client in desktop/ios/android and web Kosovo country code XK and phone prefix +383 is not showing there.

Is it possible to add it as soon as possible because I think this prevents users to find each other in phone app in android/ios and I have started to receive many complains for it.

You can find our country code and flag here https://en.wikipedia.org/wiki/List_of_country_calling_codes and in many other websites and its supported in gmail,yahoo, whatsapp,viber,telegram etc its supported almost everywhere.

**Comment by t3chguy** [comment]
Any reason why its not on sites like https://www.nationsonline.org/oneworld/country_code_list.htm ?

**Comment by t3chguy** [comment]
Hmm, https://phonenum.info/en/country-code/ lists Kosovo as +381
So it seems like Kosovo has four prefixes where we only support one: https://github.com/annexare/Countries/blob/master/data/countries.json#L2794

**Comment by t3chguy** [comment]
Might be resolvable by switching to https://www.npmjs.com/package/libphonenumber-js or https://www.npmjs.com/package/google-libphonenumber - https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L29301

**Comment by t3chguy** [comment]
Okay, just as I almost finished this I realise that the Matrix API wants a country code, e.g `XK` but doing that here would fail as `XK` is not https://en.wikipedia.org/wiki/ISO_3166-1 recognized which is what the Matrix Spec uses.

**Comment by t3chguy** [comment]
So this turned out to be a much bigger issue due to the situation with ISO 3166-1 and Kosovo:

> The code XK is being used by the European Commission,[24] the IMF, and SWIFT,[25] CLDR and other organizations as a temporary country code for Kosovo.[26]

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

The Matrix spec uses the above mentioned ISO https://matrix.org/docs/spec/client_server/r0.6.0#phone-number

Do you actually have a Matrix server capable of sending +383 XK MSISDN 3PID verifications? 
matrix.org using https://www.openmarket.com/docs/Content/globalcoverage/country/kosovo.htm likely does not.

Do you have access to an iOS device running Riot.im which does actually list Kosovo and are you able to confirm the text verification from that works for you @betimi91? If it works then I will work to get it added into riot-web.

**Comment by t3chguy** [comment]
Considering iOS shows this and libphonenumber considers it valid, adding it in the linked PR.

**Comment by betimi91** [comment]
Hey @t3chguy  I am sorry that I haven't been here to comment in this case for few days - yes Kosovo XK and country code +383 is valid you will find plenty of information in internet because we used for long time Monaco +377 but there were policitical issues in the past so you will find outdated info and updated info now the reality is Kosovo is independent and have its own country code +383 and now its also in Appstore IOS etc.
