### ISSUE TITLE
slash command completion should rank literal command match above description match

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#13415]
Typing `/dis` <tab> gives you `/nick` instead of `/discardsession`, presumably because `/nick` was the first match due to matching 'display name' in the description of the command

**Comment by jugglinmike** [comment]
Turns out it's specifically due to the word "display" in the description of the *arguments* to `/nick`, since that match comes at string position 0, just like the match against `/discardsession`.

I've submitted a patch which takes the order of the input keys into account:

https://github.com/matrix-org/matrix-react-sdk/pull/4784
