### ISSUE TITLE
"Review where you're logged in" copy conveys the wrong urgency

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13417]
I think we need to tweak the "Review where you're logged in" copy to be "Warning: You have unverified sessions!" Later/Review or something similar - as "Review where you're logged in" sounds like a casual security checkup (e.g. "is your 2fa still accurate?" rather than a "oh !@£*, someone just guessed your account password")

Currently:

<img width="256" alt="Screenshot 2020-04-28 at 13 23 35" src="https://user-images.githubusercontent.com/1294269/80487054-1a511100-8954-11ea-8102-5c14d12b7141.png">

**Comment by nadonomy** [comment]
@jryans feel free to close this issue if it's made redundant by the new logic which can show distinct toasts for new vs historical sessions.

**Comment by jryans** [comment]
@nadonomy I assume we'll still be showing this as the aggregate toast for any older, pre-existing devices even after today's change captured in https://github.com/vector-im/riot-web/issues/13422.

**Comment by jryans** [comment]
Currently I've marked this post-release, please advise if needed before.

**Comment by nadonomy** [comment]
Yep, my understanding from the sync today is:

- This toast will still persist to prompt users to review historical sessions, where it's conveying the correct amount of urgency
- Now we've determined we can display a distinct toast for _new_ logins then the increased urgency is reflected there instead

So I believe in either the case of pre or post release this issue is now redundant. @ara4n if you had a different understanding feel free to re-open with extra clarification.
