### ISSUE TITLE
Regression in room filter input animation

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13475]
~Fields appear to be more jittery, and toggle switches jump instead of slide~

---

After [further discussion below](https://github.com/vector-im/riot-web/issues/13475#issuecomment-623537120), it appears the core issue being reported here is @ara4n's mention of the room filter input.

**Comment by jryans** [comment]
@turt2live As best as I can tell, these seem to be separate things, so it may be best to have separate issues. I created https://github.com/vector-im/riot-web/issues/13491 for the toggle switches.

As for the fields, can you capture what you are seeing in a video? Here's what I see on develop:

![field-anim-jump](https://user-images.githubusercontent.com/279572/80965577-a8bd0b00-8e0a-11ea-919f-b62a70b5ef32.gif)

There's definitely a small jittery jump when focusing away and the text moves back down into the field, though using riots.im, I see the same behaviour on 1.5.0, so I'm curious what you are seeing.

**Comment by turt2live** [comment]
I'm not really seeing the jittery fields any worse than yourself. Matthew reports that they are worse than before.

Both areas look to be because of CSS changes on develop.

**Comment by ara4n** [comment]
The problem i spotted wasn't the fields but the tweening of the Filter box:

as per https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/MqVeZcaYBtInxWuAdFUnAWRK

**Comment by JorikSchellekens** [comment]
I'm looking into this

**Comment by jryans** [comment]
This seems to only affect very large accounts so far, so I don't believe it rises to the level of release blocker. We should still try to investigate if possible.

**Comment by JorikSchellekens** [comment]
I'm not getting anywhere with this. Managed to recreate by using a large account and throttling the cpu x6. Unasigning myself in the hope for someone with fresh ideas.

**Comment by ara4n** [comment]
i have an inexplicable profiler trace showing the jank is not due to js or relayout but “other cpu”. i’ll try disabling seshat and stuff to see if i can pin it down, and try it with a small accf etc

**Comment by foldleft** [comment]
Not much luck reproing yet.

My suspicion is that something expensive happens when the search field is clicked, but it's hard to say.

Just in case it's animation, I made this little snippet that'll expand/collapse the widget purely by flicking the display state back and forth.

```
let s = (e) => e[Object.keys(e).find((k)=>k.startsWith("__reactInternalI"))]; let n = s(document.querySelector(".mx_LeftPanel_container")).return.stateNode; n.setState({searchExpanded: !n.state.searchExpanded})
```

Matthew – I expect this to not show jank. Could you let me know how it behaves?

**Comment by foldleft** [comment]
I noticed ~30 listeners were getting attached when I expanded the component. I suspect that (contrary to how the code looks) we're replacing the full view of rooms with the search view prematurely

**Comment by foldleft** [comment]
I'm not sure if it's related but `Layout.update` seems to fire a good number of times when loading the app, and I wonder if it'd benefit from a little debounce

**Comment by foldleft** [comment]
It seems that `RoomList` runs `componentDidUpdate` for each mouseover/out, whereas `LeftPanel` does for activating the search, presumably because it hides the `Explore` input, and this also causes `RoomList` to update.

I'm not sure this is the culprit yet, but it looks hinkey.

I also deliberately caused it to slow down by adding a 200ms `while` loop to `Layout.update` to see if that was the culprit; _chrome's performance tool did not catch this_ but rather saw `Layout.update` as running 4-5 times, causing the _outer_ function to take that exact `200ms` extra.  This means the tooling is suspect, so that's fun.

**Comment by ara4n** [comment]
trying this again now, it seems to have fixed itself (at least in Nightly, which is where I think i saw it before), as per https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/EYjVyFWQaXJURNNGkUCmVZPu.
