### ISSUE TITLE
apt-upgrade from 1.5.15 to 1.6.0 completely removes riot-web

### ISSUE THREAD

**Issue by jacotec** [vector-im/riot-web#13533]
### Description

Updating riot-web via official repo on Ubuntu 18.04LTS has completely removed riot-web from the server

### Steps to reproduce

- Riot-Web 1.5.15 installed via official repo
- apt update
- apt list --upgradable shows Riot-Web 1.6.0 as an update
- apt dist-upgrade

These usual steps have **completely removed** riot-web from the server, only the *.json file and my own welcomt html file are left in /opt/Riot/resources/webapp.

Server message:

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  riot-web : Depends: riot-desktop but it is not going to be installed
> 

A dependency of riot-desktop is fully stupid for a headless server ...

Version 1.6.0 is listed as upgradable from 1.5.15:

> root@jaychat:~# apt list --upgradable -a
> Listing... Done
> riot-web/unknown 1.6.0 amd64 [upgradable from: 1.5.15]
> riot-web/now 1.5.15 amd64 [installed,upgradable to: 1.6.0]

**Comment by t3chguy** [comment]
the `riot-web` package was previously the name of the electron app. The app has finally been renamed to riot-desktop. `riot-web` in future will be used for the static webapp. 

That issue is https://github.com/vector-im/riot-web/issues/2777

**Comment by jacotec** [comment]
@t3chguy Sorry, but I have no clue what this means. The package "riot-web" gives me what is needed to host riot-web on my server, so users can access it by the browser.

So what do I need to do or change in detail to apt-update that to version 1.6.0? And what is a "static webapp"? (Isn't it the webapp what I was always using?!?)

**Comment by t3chguy** [comment]
`riot-desktop` is exactly the same as `riot-web` was last week. It was just renamed because `riot-web` was the electron app all along, which is why issue #2777 exists.

What you were using (riot-web package) was the electron app (if you looked at its dependencies, you probably installed x11 and electron), which just contained the webapp's source code and you were unsupportedly using that.

**Comment by jacotec** [comment]
Hi @t3chguy ,
OK, clear in theory but not practical. After riot-web was removed, an "apt install riot-desktop" does not give me anything which works. There are some ".asar" files installed in /opt/Riot/resources, but /opt/Riot/resources/webapp stays empty except my .json config file and nothing works. Calling my domain shows just the directory listing with my config files.

So snapshot back to 1.5.15 again ... Is there a doc how to update this?

**Comment by t3chguy** [comment]
riot-web (and riot-desktop) do not support downgrades due to the one-way encryption database upgrades which happen from time to time, if you wish to downgrade manually you are unsupported.

The riot-desktop app is now sourced from https://github.com/vector-im/riot-desktop which now uses asars for their benefits, the plan was always this. Abusing the electron app for webservers was never a supported use-case.

You *could* unpack the asar archive, but again, this is not a supported configuration.
If you *desire* apt to manage your webserver riot-web installation, that is #2777
You were previously abusing the riot electron app for how it was packaged internally.

For installation to a webserver, use the official instructions.
https://github.com/vector-im/riot-web#getting-started

**Comment by jacotec** [comment]
Ah, OK ... got it!
Just downloads the riot-web package from Releases and untar it to /opt/Riot/resources/webapp. Seems to work :-)

Thank you!

**Comment by andreasnuesslein** [comment]
> Abusing the electron app for webservers was never a supported use-case.

To be fair: it was rather hard to perceive this, based on the old package name. To know that when installing `riot-web` (which did work just nicely as a "web" version of riot) you were actually installing the riot-desktop version and abusing it.

**Comment by t3chguy** [comment]
Agreed

**Comment by jacotec** [comment]
It was written that way in a doc two years ago when I introduced Matrix/Riot, that's why I did it that way 😉

Now I know the right way.
