### ISSUE TITLE
Use recovery keys rather than recovery pass phrases

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/riot-web#13825]
Place holder issue - more context to follow but in short we want to reduce sign up friction caused by asking a user to provide two passwords.

Current preference is for option B
https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=5050%3A31796

**Comment by t3chguy** [comment]
Covers https://github.com/vector-im/riot-web/issues/13766 too

**Comment by dbkr** [comment]
Questions on the design:
 * What state is the client in before a recovery key is created? Is this the same as if you click 'skip' currently (ie. you can't verify and get prompted to set up if you try to)?
 * The copy for web focuses on 'losing this device', although on web it's probably more likely that you'll be logged out - this could be misleading? (It also says 'may' which is not really true - if you lose your device, your data is gone for sure).
 * The designs here encompass quite a lot of things technically

**Comment by dbkr** [comment]
Why did you close this, github?

**Comment by dbkr** [comment]
Also, the option to back up message key is gone: do we always back up now?

**Comment by dbkr** [comment]
Another one: we currently have the "keep it safe" and "you're done!" screens after setting up: are these going away?

**Comment by ara4n** [comment]
My questions:
 * Why do we need the "Complete security" page at all?  It just seems to add more steps.  Shouldn't we jump straight into "We've set up encryption - hey, here's your recovery key"?
 * In Proposal B, I wonder if we can avoid having the "complete security" toast - after all, if this is a casual user joining a public chatroom as a guest, why do they care about DM security?
    * On the flip side, users currently don't appear as verifiable until they've set up security.  Should we change this so we can try to verify anyone (even if they have no cross-signing keys), in the hope that it triggers them to set up cross-signing?

Some answers:
> Also, the option to back up message keys is gone: do we always back up now?

We still need to give the option.  We are not forcing people to back up message keys.

> Another one: we currently have the "keep it safe" and "you're done!" screens after setting up: are these going away?

These feel redundant to me?  We are trying to simplify rather than have redundant dialogs, imo.

Some thoughts:
 * Tracking the questions & answers in this bug rather than in a google doc is going to be painful.

**Comment by squidink7** [comment]
If this gets implemented will the annoyingly long cross signing setup be fixed? anything more than entering a username, password and email address is too overwhelming to most users and choosing a second password just seems daft. It would be really nice if the whole "key setup" happened in the background without any user input. however storing keys on the server has significantly improved the user experience imo, so if you could find a way for the account password to grant access to a user's account and the message keys that would be the best for a user friendliness point of view.

**Comment by jryans** [comment]
@squidink7 We're broadly aware there are pain points with the current process, but please describe your needs in a fresh issue so we can discuss it separately from this work.

**Comment by dbkr** [comment]
We reverted the PR, so re-opening

**Comment by fbruetting** [comment]
I watched the demo from friday – very nice! However, I’d like to add that when I think about my friends, I’m pretty sure that a lot of non-technical users would be confused by getting displayed a recovery key after they have set a recovery passphrase. Would it maybe be a good idea to

a) either replace that recovery key field by a button like “Generate an *additional (alternative)* recovery key” which then would not show that key before being pressed,
b) or add some informational text above, that the displayed recovery key acts as an alternative to the recovery passphrase, which the user has set in the step before?

Then users would better understand of what that key is about – because currently there is absolutely no context to that key (see below).

I’d like to mention this, because I’m sure pretty much none of my non-technical friends understands this (and even the technical ones are partly confused), because they may not have dealt with such things ever before, or just rarely occasionally. It’s very important to make everything as clear as possible in an easy language – especially right at the time of registration. I’m also sure that most friends of mine skipped this dialog back in the time, and then later got/get surprised by not being able to recover encrypted content. You really have to take care about people, which don’t care at all – because these people will definitively block others of using Matrix or at least get annoyed. (Believe me, that’s my current problem in our organization.)

![Bildschirmfoto von 2020-06-28 21-24-03](https://user-images.githubusercontent.com/10520767/85956382-d7c4a880-b985-11ea-8187-fe4801f4d402.png)

**Comment by jryans** [comment]
> It’s very important to make everything as clear as possible in an easy language – especially right at the time of registration.

We plan to soonish move this setup later in the process after registration: https://github.com/vector-im/riot-web/issues/13895
