### ISSUE TITLE
Seshat yields different results for different persons in same room

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/riot-web#13866]
### Description

Was discussing a certain message with another user of the same encrypted room.
I searched for it, but couldn't find it via the most likely keyword - only different (older) messages with the same keyword came up. Also tried things like different capitalization to no avail.
The other person meanwhile searched using the same keyword and instantly found it.
Now that we know more content I could find the message in question via another search term.

I don't think this is how search should work and UX left me very confused.

### Steps to reproduce

Not sure - search for the same encrypted message from different riot instances/matrix accounts?

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.6.2

**Comment by poljar** [comment]
I think that might be because your older messages got a better score and your friend might not have the older messages in a decryptable state.

This is done because no pagination for search results existed so the 10 results you get are the ones with the best score. How the score is calculated  can be found [here](https://fulmicoton.com/posts/behold-tantivy/)

Pagination is being added currently and the ordering will properly be done by recency.

**Comment by HarHarLinks** [comment]
sounds like this is already being taken care of somewhere else. thanks for clearing it up.

feel free to close, or keep open to track my idea of expected behaviour.

**Comment by t3chguy** [comment]
Sounds like it'll be resolved by the more predictable recency sorting.
