### ISSUE TITLE
New Emoji picker in 1.6.3: Serious display issues on MacOS Safari

### ISSUE THREAD

**Issue by jacotec** [vector-im/riot-web#13927]
### Description

Thanks for bringing the phantastic Emoji picker to Riot-Web! 👍🏻

However, it has serious issues on Mac OS Safari

### Steps to reproduce

See below, there are numerous "black blocks" between Emojis

![image](https://user-images.githubusercontent.com/3321655/83780169-19b34500-a68d-11ea-9e58-e536382ed47f.png)

The same issue exists in the reactions Emoji picker!

### Version information

- **Platform**: web (in-browser) or desktop?

web

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?

Safari 13.1.1

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?

MacOS Catalina

- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

Private server, Riot-Web 1.6.3

**Comment by t3chguy** [comment]
Did this happen to you prior to 1.6.3 in the Reactions picker?

![image](https://user-images.githubusercontent.com/2403652/83780615-51b68a00-a685-11ea-81d9-ab963fd9b09a.png)

**Comment by jacotec** [comment]
Honestly I did not use the reactions picker that much on my MacBook, so I don't know if the RP had this problem before.

Also no special settings regarding the font anywhere ... at which place should I look for the font? Is that something which needs to be installed aditionally on my Matrix/Riot server?

**Comment by jacotec** [comment]
Interesting is that one as well ... missing completely in Safari, it's there in Firefox on the same MacBook:

![image](https://user-images.githubusercontent.com/3321655/83793396-c517c600-a69c-11ea-81d6-01bf55779197.png)

**Comment by aaronraimist** [comment]
Most likely a dup of https://github.com/vector-im/riot-web/issues/9895

**Comment by jacotec** [comment]
Looks pretty similar (white boxed in dark mode --> black boxes in light mode?!?)

**Comment by ara4n** [comment]
The problem here isn't that it's not using twemoji, but https://github.com/vector-im/riot-web/issues/9895 - the variation-16 selector is being rendered as a black box on the COLR font in Safari rather than actually being applied.

One (kludgy) workaround would be to make the default glyph shape a zero-width diagonal line rather than a solid box, which I can do in the emoji 13 update, so you can't see the variation-16 selector failing to be applied.

The better solution would be to figure out how to make safari apply the selector.  However, I think this may just be a bug in Safari.

For context: here's a ♥ without a variant selector, and here's a ♥️ with a variant selector (mainly to see how they get mangled)

https://unicode.org/emoji/charts/emoji-variants.html for more info about variation-16.
