### ISSUE TITLE
New room list does not function well when all rooms are shown (large accounts)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14539]
https://github.com/vector-im/riot-web/issues/14035#issuecomment-659262624

**Comment by jcgruenhage** [comment]
I've switched to the new room list, my account is okay on my workstation (I didn't notice issues there), but it turned element on my Pinebook Pro from "okay" to "infuriatingly slow".

In the configuration I'd want to use ideally (all rooms, top 10 of other categories), it takes 8 seconds to switch a room, 2 seconds to even highlight it when hovering over it with the mouse. Composing messages is a pain to, since the composer lags between a few hundred ms to a few s behind what I'm actually typing. It's slowing down my laptop enough, that I actually closed element to submit this comment...

Even with everything reduced to top 5, the performance is bad, it takes 3.5s to switch rooms. With everything fully collapsed, it takes 1.5s, which is annoying, but bearable.

**Comment by Ai-rin** [comment]
I experience composer lag too, after Riot became Element. Could it be due to new roomlist? I don't see a way to disable it now.

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/88209373-da768e80-cc0f-11ea-8a45-6d798ee42693.png)

Test case: 3000 rooms shown, receive an event

Looks like we might be sending too much to React to figure out. The room list only takes 4.22ms to figure out what it needs to look like, but then spends well over a second making that change happen (the screenshot shows ~779ms of this). This is likely because we're not scoping the list updates to a particular tag, and thus re-render the entire list. We probably do not need to be remounting everything.
