### ISSUE TITLE
Search room filter: (design only): needs some work

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1754]
Search room filter: (design only): needs some work, changing way search works as per comments on Zeplin screen
- DESCOPED for dev in this sprint

**Comment by ara4n** [comment]
Just to capture the new Search behaviour we agreed on yesterday before I forget:

* Typing in the 'search rooms' field filters the RoomList (LeftPanel)
* It also pulls in results from the Room Directory itself as a sublist
* It also pulls in potential 1:1s which don't exist yet (i.e. people) as a sublist.
* Cursor up/down lets you jump into the results and hit return to navigate to one of the results - thereby giving a fast room switcher functionality.
* Hitting enter whilst the input box itself is focused or pressing an explicit 'search' button brings up (in future?) a full MiddlePanel spotlight-style search view with detailed results.

**Comment by bradlegge** [comment]
Screen URL:
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=57472978a218f613300f762a

**Comment by ara4n** [comment]
See also #1853 (which is basically a dup)

**Comment by JasonLocklin** [comment]
There is an opportunity to add some "power user" features here without increasing UI complexity at all. So I'll make a few possible other "wishlist" type suggestions:

-  !active: Show only channels with activity/unread messages. There may be other "room state" queries I'm not thinking about.
- !network freenode: Show only channels bridged with freenode network.
- GroupName - when groups are implemented, obviously, searching group name should filter based on it.
- ContactName - In addition to the 1:1 chats above, typing the complete contact name could display all channels you are mutually in with that contact.
- !topic string: include channel topics in search filter.
- tags: tagging rooms with arbitrary labels for personal reference (instead of only Favorite and low priority), combined with filter might be very useful in the future.
- Issue #2557

Also note that currently, selecting a room from the filter clears the filter and list. I'm not sure this is user-expected behavior. Say I'm troubleshooting a X issue, and filter my channels to show X-related channels. I think being able to work from that restricted list until I'm done with my job makes sense. Of course, that conflicts with the "quick room switcher" use case. Again, perhaps a syntax flag might make the filter "sticky" for power users.

**Comment by grahamperrin** [comment]
Around a week ago I began wishing for support for `either|or` queries.

**Comment by grahamperrin** [comment]
> … Show only channels bridged with …

💯 

Here, for example, I imagined that simply seeking _moznet_ would present all Moznet rooms that I have joined: 

![2017-10-21 12 05 27 riot 3](https://user-images.githubusercontent.com/192271/31851250-0dca4c00-b65a-11e7-8656-5d2cb225a93b.png)

Re: [Room filtering in dir should search names, topics as well as aliases · Issue #974 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/974) maybe the scope of 974 can be expanded to include some of what's envisaged here in 1754.

**Comment by t3chguy** [comment]
@nadonomy might be worthwhile you looking through this to see if any of these things are still desirable in new design docs. Closing for now, re-open if viably needed.
