### ISSUE TITLE
Chat text input (RTE) and input markdown panel (design only)

### ISSUE THREAD

**Issue by bradlegge** [vector-im/riot-web#1763]
Chat text input (RTE) and input markdown panel: needs discussion before design and dev completion

**Dependancy/question**: differences in opinion on what is required here, needs a separate discussion on how to handle rich text formatting. Some use cases would help covering developers and non developers

**Comment by ara4n** [comment]
The plan we converged on yesterday was:

* Have a UI control of some kind on the RHS of the MessageComposer (as proposed in trevor's design) that a) tells you whether you are currently inputing MD or RTE content b) lets users display a formatting toolbar to give a set of buttons to help with formatting if they're not comfortable with shortcuts like MD syntax or cmd-B style keyboard shortcuts.

* When the formatting toolbar is displayed, the buttons would show labels that provide hints for the MD syntax (if in MD mode), or just simple format labels if in RTE mode.

The implementation here has already been done by @aviraldg as part of his GSoC work, and actually implementing the design will be on Aviral's side too.  All we need here is the design assets from Trevor so that the UI/UX is consistent with the rest of the app.  The current proposal is a great starting point.

**Comment by bradlegge** [comment]
Screen URL:

https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=577e8a9f8b6361014a95da4f
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=577e8a9b9de95f617d1818d0

**Comment by bradlegge** [comment]
Thanks Matthew, I have made it a design ticket only for this sprint and assigned to Trevor

**Comment by ara4n** [comment]
Another thought here is that we could warn the user that they are in MD mode only if they start entering text which can be interpreted as MD - thus giving them the option to switch to WYSIWYG and turn off MD if they didn't mean to be in MD.

For instance, we just had a mess with `That seemed to be the case when I joined #freenode_chicken:matrix.org not not #freenode_#guile:matrix.org.` where the two underscores were incorrectly processed as MD italics.  Ideally i'd have had the little 'Aa' formatting button somehow remind me that I was in MD mode, and should switch to WYSIWYG and try again to avoid everything getting mangled.  (The 'syntax highlighting' of the italics on the MD source could help remind me that things are about to go wrong')

**Comment by antikewl** [comment]
Updated/improved UI here:
Collapsed text input box. MD indicator in text field. https://zpl.io/ZUczow
Text input box, formatting drawer open, MD enabled. https://zpl.io/1CIyGi
Text input box, formatting drawer open, MD disabled. https://zpl.io/Z1femhH
