### ISSUE TITLE
RTE: Toggling markdown ON does not preserve all formatting in a stable way

### ISSUE THREAD

**Issue by jansol** [vector-im/riot-web#1944]
Currently when writing a code block and adding a new line, it keeps the code styling but starts a new block, which is practically never the wanted behaviour. Typing up a multiline block in MD mode works but switching to RTE nonchalantly discards any newlines.

**Comment by lukebarnard1** [comment]
So the bulk of this has been fixed, but swapping from RTE to markdown mode does not preserve the code block as expected, the backticks are not inserted.

**Comment by lukebarnard1** [comment]
- [ ] code blocks are not given backticks
- [ ] strikeout is converted to the old `~~bla bla~~`
- [ ] strange new lines at the top of bullets/numbered lists

**Comment by t3chguy** [comment]
- [ ] underline gets wrapped in `++{TEXT}++`

**Comment by lukebarnard1** [comment]
So this is due to the composer using `draft-js-export-markdown` to convert from `ContentState` to markdown plaintext.

The following conversions are currently done:

 \- | from ContentState (draft-js) | from plaintext markdown
-|-|-
to ContentState | - | `commonmark`
to plaintext markdown | `draft-js-export-markdown`* | -
to `formatted_body` | `draft-js-export-html` | `commonmark`
to `body` (no styles used) | `contentState.getPlainText()` | -

*this is the problem, we shouldn't be using two different HTML<->markdown engines. We need to use a library that can convert `ContentState` to markdown. Perhaps `commonmark` provides such a thing.

**Comment by lukebarnard1** [comment]
Demoting to p2 as whilst it's slightly annoying, it shouldn't affect normal usage too much.

**Comment by lukebarnard1** [comment]
- [ ] Escaping does strange things in code blocks/spans https://github.com/vector-im/riot-web/issues/4574

**Comment by t3chguy** [comment]
RTE was replaced by CIDER

**Comment by t3chguy** [comment]
Travis pointed out we still have Slate :(

**Comment by aaronraimist** [comment]
> Travis pointed out we still have Slate :(

We don't have Slate anymore
