### ISSUE TITLE
Ability to export/import current E2E state as a passphrased blob

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2108]
This would be useful for backup purposes (e.g. being able to resurrect my identity key & room key data after moving browser sessions) as well as a temporary mitigation for not being able to share room key data with my new devices in a room in order to share historical data.

**Comment by ara4n** [comment]
We should probably never store/restore the identity keypair itself, given the act of restoring this onto a new browser should presumably be seen as a new device for the purposes of verification etc.

**Comment by apexo** [comment]
Should we use some key-derivation function (e.g. PBKDF2/bcyrpt/scrypt/argon2) to make brute-forcing the blob harder?

The "identity keypair" is in session.e2e.account?

**Comment by ara4n** [comment]
@apexo: yup, something like bcrypt sounds sensible.

and yup, `sessione.e2e.account` looks like the identity key details.

**Comment by eternaleye** [comment]
@ara4n:

Please, please do not use bcrypt. The reason it was ever used is that Blowfish's key setup was - at the time - considered hard to accelerate efficiently, and the world has changed since then. Bruce Schneier, who created Blowfish, said in 2007 that he was ["amazed it was still being used"](https://www.computerworld.com.au/article/46254/bruce_almighty_schneier_preaches_security_linux_faithful/%3Fpp=3).

In addition, there's a significant amount of ongoing research regarding memory-hard functions (an [incredibly important paper](https://eprint.iacr.org/2016/875) on upper-bounds and optimal security was just published _today_, and includes new attacks on Argon2i).

Scrypt operates on data in secret-dependent ways (and thus potentially has side-channel problems that are especially relevant if running it on the client device), and while Argon2 has a mode that does not (Argon2i), when submitted to the IRTF CFRG, there was significant concern over both its newness and its security bounds.

I strongly suggest going with PBKDF2, as it's well-understood, widely-deployed, supported by almost everything, and not the subject of active research.

**Comment by apexo** [comment]
The problem with PBKDF2 is that hashing is serial: it can only every utilize a single thread. If you want to limit the latency that is required to verify a hash, you can only throw so many iterations at it.

An attacker, however, is not limited by latency. He can employ a vast array of efficient (=slower) computing units that specialize on hashing. So even if one hash takes longer, it doesn't matter much, since he can compute thousands or even millions of hashes in parallel.

scrypt and Argon2 don't suffer as much, because they also require a lot of memory, which limits parallelism attacks. Argon2 improves upon that by incorporating parallelism: generating a single hash can use multiple threads, which gives attackers less of an advantage.

Example for PBKDF2: on some random CPU (i7-4600U), openssl barely manages 2 million iterations per second (SHA1 HMAC). Specialized SHA2 hashing ASICs (for BTC mining, obviously, https://en.bitcoin.it/wiki/Mining_hardware_comparison) could test ~6 million of those 2-million-iteration-PBKDF2-hashes per second for 200µJ per try (yes, SHA1 != SHA2, and those ASICs can probably be not be used for that tasks, but depending on who your adversary is, ASICs are not a big hurdle). At 10ct/kWh, with 100$ you can expect to break a passphrase with 44 bits of entropy.

**Comment by eternaleye** [comment]
@apexo: Please see the "incredibly important paper" I linked: scrypt, being data-dependent, has known issues when used on the same device as a potential attacker could perform side-channel attacks (i.e. the client machine, as would be the case here), and Argon2's security parameter has been _repeatedly_ eroded by a large margin in the past few months.

The former is not quite suited for the use case, and the latter is not ready.

**Comment by richvdh** [comment]
I've proposed a format for this (including proposals for encryption) at https://docs.google.com/document/d/1UjWpNMfof3ynFbEOtHWGmqxy_WrFZEojrGWUq_os0G8. I'd be grateful for comments from interested parties.

**Comment by richvdh** [comment]
Now in develop.

**Comment by vext01** [comment]
Thanks richvdh!

**Comment by richvdh** [comment]
I should probably be clear that https://github.com/matrix-org/matrix-react-sdk/issues/647 only imports and exports group session data; the ability to log in on a new device and have your contacts trust you without a new verification step remains an open problem.

**Comment by tjgillies** [comment]
> remains an open problem.

I thought not trusting new devices was a feature?
