### ISSUE TITLE
Avatar setting chokes if filename includes question mark

### ISSUE THREAD

**Issue by eternaleye** [vector-im/riot-web#2344]
@solson:matrix.org set their avatar shortly after creating their account, but is still an S

**Comment by solson** [comment]
Specifically, if I click on myself in a user list, and then click on my avatar there, it shows up correctly in the full-screen overlay that comes up, but everywhere else in the UI it's just the default "S".

**Comment by solson** [comment]
I found out what the problem was. I uploaded a file with a name like `avatar.png?size=200` which I downloaded from gravatar. Then I noticed when downloading the avatar from Riot that it still had that tacked on. I reuploaded from a source file called simply `avatar.png` and it entirely solved the problem.

So somewhere, Riot is having trouble with weird filenames. It should probably just ensure it renames a PNG upload to have a correct .png extension.

**Comment by turt2live** [comment]
I'm inclined to believe @jryans for this one
