### ISSUE TITLE
support drag and drop out of the DM sublist

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2365]

**Comment by uhoreg** [comment]
Probably not worth creating another issue for this, so I'm leaving it as a comment here since it's related: as noted at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14855249871111514zbTKJ:matrix.org, dragging a room that's marked as "Direct Chat" from "Favourites" to "Rooms" makes it appear in "People" instead.  It should probably un-mark the room as "Direct Chat" so that it it will appear in "Rooms".

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/8614
