### ISSUE TITLE
make it clearer that GIFs are rolloverable

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2416]

**Comment by kethinov** [comment]
Might also be worth considering animating them by default with an option to disable that to preserve the current behavior. Most people I chat with expect that when they paste a gif it will auto animate and are surprised when it doesn't. Few even knew you could even see the animation without downloading the image due to the non-obviousness of the hover-to-animate feature.

Either way, regardless of how everyone feels about defaults, at least having an option to animate without hover seems useful, even if it's not on by default.

**Comment by turt2live** [comment]
@kethinov The option does exist, just default off:
![image](https://user-images.githubusercontent.com/1190097/26890159-d641ac58-4b6d-11e7-883c-622834c70282.png)

**Comment by kethinov** [comment]
Ah nice, thanks for pointing that out.

**Comment by turt2live** [comment]
There's a badge on them now
