### ISSUE TITLE
Improve resistance to window.opener attacks

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2439]
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1476021010918459qulDK:matrix.org

**Comment by ara4n** [comment]
Apparently inspiration can be sought from https://www.namepros.com/js/namepros/links.js?4
and https://github.com/danielstjules/blankshield/blob/master/blankshield.js.  The idea is to implement `rel="noopener"` behaviour on a broader range of browsers.

This is basically the same as #1971, which i'll close as a dup as we have more detail here.

**Comment by rugk** [comment]
See https://mathiasbynens.github.io/rel-noopener/ for a demonstration.

As it seems you already use rel=noopener (for chat links, at least). Can you verify it is actually used everywhere?
If that's the case, it is okay to close this IMHO. Firefox supports `rel=noopener` (without `noreferrer` that was required before) since Firefox 52.
There is nothing else you can do.

**Comment by turt2live** [comment]
In practice I believe we have noopener on everything.
