### ISSUE TITLE
[e2e] Messages sent by a user from 2 differents clients aren't decryptable

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#2676]
To reproduce:
1. Alice create a room and enable encryption on client 1
2. Alice sent msg 1.
3. Alice logs on client 2 while still being on client 1
4.  Alice sent msg 3 on client 2.

msg 3 isn't decryptable on client 1. All the folowing messages sent on a client won't be decryptable on the other client.

**Comment by richvdh** [comment]
yes it seems like we don't download our own device list!

**Comment by richvdh** [comment]
Background: when we send the first message from a new client we download device lists for any users we don't already have a cached device list for; but our own device is added directly to the store, rather than being downloaded, which confuses that logic into thinking that we already have a device list for ourselves.

**Comment by ara4n** [comment]
RICH DID THIS
