### ISSUE TITLE
[e2e] "TypeError: NetworkError when attempting to fetch resource." when trying to decrypt attachment

### ISSUE THREAD

**Issue by Takios** [vector-im/riot-web#2687]
Hello,

decrypting attachments in a private (1on1) room does not work. The GUI gives the following error:

`Error decrypting attachment`

Using the FF debugger, I can see the following message:

`Unable to decrypt attachment: TypeError: NetworkError when attempting to fetch resource.`

I'm using my own homeserver. Attachments in unencrypted channels work fine.
There are no relevant messages in the homeserver log from what I can see. I omitted INFO messages though because they are way too verbose to sift through if you don't know what you're looking for.
If you need more information, I'll be happy to provide them.

Greetings

**Comment by richvdh** [comment]
First thing to check is that you have synapse 0.18.4 or later, which is required for this to work.

Otherwise, "NetworkError when attempting to fetch resource." suggests that a request to the homeserver which failed. If you could use the debugger to establish the details of the call which failed, that would help.

**Comment by ara4n** [comment]
i'm going to assume that this was too old a homeserver, unless @takios says otherwise, and close it.
