### ISSUE TITLE
Windows shortcut

### ISSUE THREAD

**Issue by RadialAdmin** [vector-im/riot-web#2775]
Windows shortcut linked to C:\Users\User\AppData\Local\riot\Riot.exe instead C:\Users\User\AppData\Local\riot\app-0.9.2\Riot.exe

**Comment by ara4n** [comment]
fixed by 4de042bf587f42a9f91df4db22c536a6f8a6c0b6

Not entirely sure why this worked, but \riot has an Update.exe and \riot\app-0.9.x does too.  I just told it to run the one in the subfolder in the hope that it might the link to the right place, rather than the broken parent folder location.

@RadialAdmin thanks for the report!

**Comment by ara4n** [comment]
(this was released in 0.9.5 an hour or so ago)
