### ISSUE TITLE
GA not enabled on electron

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2787]
This is a huge deal in terms of damaging our stats

**Comment by ara4n** [comment]
...however, it's also evil for desktop apps to phone home with stats without prompting.  Either we prompt (both on web & desktop), or we just ditch GA and infer health of Riot by looking at activity on matrix.org HS.

**Comment by 4nd3r** [comment]
not phoning home, but to 3rd party service. and for internal networks, this is absolute no.

**Comment by ara4n** [comment]
totally agreed. hence saying we should prompt on both web & desktop. (and switch to somethig better than GA, eg piwik, for which there is another bug).

**Comment by ara4n** [comment]
(in practice making stats opt-in is a bit of a disaster though in terms of the metric we need, though, which is how many active users of the app there are, given that directly impacts our funding to work on it :|)

**Comment by 4nd3r** [comment]
github download statistics? debian repository statistics? previewable stats (number of accounts in HS, used features eg LDAP login, etc) submission for synapse (and riot-web #2777) which trigger on package upgrades? i would be totally okay with this way meaning i can verify what information will be sent and when.

**Comment by tuxayo** [comment]
> opt-in is a bit of a disaster though in terms of the metric we need, though, which is how many active users of the app there are

Isn't monitoring matrix.org HS enough to know this?

**Comment by kythyria** [comment]
> Isn't monitoring matrix.org HS enough to know this?

Not necessarily. An active user might never touch matrix.org at all if they're not in any rooms replicated there.

**Comment by rtanalytics** [comment]
What is the bug with Piwik, Matthew?

**Comment by jfrederickson** [comment]
Assuming he was referring to #2077

**Comment by tuxayo** [comment]
@kythyria You mean that due to the federated nature of Matrix, monitoring matrix.org will miss many users if other nodes are used massively?

**Comment by carlos22** [comment]
> (in practice making stats opt-in is a bit of a disaster though in terms of the metric we need, though, which is how many active users of the app there are, given that directly impacts our funding to work on it :|)

That is a drastic statement and means it is more important for you to know how many users you have and what they are doing, then respecting their privacy. I get the point, but you should really consider not doing analytics at all! Because if you want this thing to succeed you need to offer more than just another slack/telegram whatever. We have a lot of messengers that have their problems in terms of privacy, data-collection and openness. Please do not enter that road.

But maybe that dream of such a project is impossible with venture capital backing...

**Comment by tuxayo** [comment]
> That is a drastic statement and means it is more important for you to know how many users you have and what they are doing, then respecting their privacy.

If that directly affects whether or not they can work on Matrix/Riot so yes the developers **must** value this more than anything else.
But considering there work on end-to-end encryption and the worries about the privacy consequences of GA, they definitely care about privacy.

That's doesn't diminish the importance of the issue: how to reliably get the number of active users of a federate network in a privacy friendly way?

Switching from Google Analytic to something else would already be a huge improvement.

> But maybe that dream of such a project is impossible with venture capital backing...

Amdocs doesn't seem to be venture capital backed so that is not the issue here. Well it's still a publicly traded company.

**Comment by ara4n** [comment]
the conclusion here is that we're certainly not enabling GA on electron by default, and we're going to make it opt-in on both electron & web, which is #2075.  So closing this a dup.

**Comment by ara4n** [comment]
oh, and for the record, we're not so concerned about somehow instrumenting the whole size of the matrix network - just wanting to estimate how many Riot DAU there are based on the number we can see from the server logs on matrix.org, and the overall size of the matrix.org ecosystem as seen by the number of Matrix servers visible from matrix.org & synapse's opt-in phone-home stats.  So there really is no need to be using GA; the only reason we're doing is historical and not having to 'round to removing it yet, as fixing bugs in the app takes priority over maintenance of the analytics lib.

**Comment by tuxayo** [comment]
Thanks a lot for taking the time to respond to all these concerns, it good to have devs that care for their most privacy conscious users.
