### ISSUE TITLE
expose webrtc settings for riot/desktop

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2822]
so people can select which mic they're using

**Comment by alexmat2on** [comment]
To add on to this: also the ability to select which camera to use (if people have a built-in webcam and an external one, or have two built-in webcams like me).

**Comment by maxidor** [comment]
Any timeline when this would be solved?

**Comment by t3chguy** [comment]
@maxidor soon ™
got the concept working and tested today, just need to pretty it up and test some more :)

**Comment by maxidor** [comment]
Great! thanks for the update @t3chguy.

**Comment by ggppjj** [comment]
If I could chime in, it would be wonderful if there were an option to select no input source as well if possible. I have a friend that, for various reasons, does not want to use the camera or microphone that he refuses to admit he has at all, and I'm sure there are others that would benefit from the option. Just something to consider!

**Comment by t3chguy** [comment]
I'm not entirely sure what you mean. Default is essentially none. If none is provided it's up to the browser or the system.

**Comment by ggppjj** [comment]
Well, what I had meant was a way to specifically choose not to use an otherwise enabled camera and/or microphone by selecting an option. Either that, or a way to join calls muted, but that would seem outside the scope of this issue. So having default for the system default, and another option that was "Do Not Use" for just not using either the camera or microphone at all without having to disable them systemwide in the case of built-in devices.

**Comment by ara4n** [comment]
Yeah, i see the use here. I'll file it as a separate bug to avoid it getting lost in this one.
