### ISSUE TITLE
disable editing on IRC (it duplicates the entire message)

### ISSUE THREAD

**Issue by chovy** [vector-im/riot-web#2839]
disable editing on IRC (it duplicates the entire message)

**Comment by richvdh** [comment]
we haven't implemented message editing.

**Comment by anthonyettinger** [comment]
this is when connecting to gitter I believe.

**Comment by richvdh** [comment]
Oh right. @leonerd: something to do with the gitter bridge?

**Comment by leonerd** [comment]
Possible.

Since Gitter allows message editing anyway, we have to handle it one way or another. Since Matrix natively does not (yet) have editing, how the Gitter bridge does this currently is to try to detect what changes have been made to the text, chopping off a common prefix and suffix string between the two versions, and posting an "Edited ..." message containing the difference. However, that appears on messages inbound from Gitter into Matrix.

I suspect what @chovy might be confused by is that some messaging systems (e.g. Telegram and Gitter) use up-arrow to fetch the most recent message for editing, whereas Riot's interface does history replay for posting a second time. Users familiar with up-edit-enter to post an update to the previous message might get confused by this UX and end up posting duplicates.
