### ISSUE TITLE
Can't connect to homeserver - please check your connectivity and ensure your homeserver's SSL certificate is trusted.

### ISSUE THREAD

**Issue by SiNaPsEr0x** [vector-im/riot-web#2840]
can ADD certificate into path of app?

![schermata 2016-12-27 alle 14 18 00](https://cloud.githubusercontent.com/assets/5438823/21501208/4650d458-cc46-11e6-9387-a2f1dbbc78b8.png)

**Comment by yifanlu** [comment]
I got the same issue using the desktop app for OSX. The web client works fine (no certificate issues). My home server uses let's encrypt.

**Comment by SiNaPsEr0x** [comment]
Resolve to add certificate to system in keychains system and restart

**Comment by yifanlu** [comment]
I don't want to have to do that each time my letsencrypt certificate expires. The CA is trusted so I don't see why the client doesn't see that.

**Comment by richvdh** [comment]
SSL certificate trust is up to the browser, not the webapp. Make sure you can connect directly to the homeserver.

This error can also be shown if there is a non-ssl connectivity error. Again: make sure that you can connect to the homeserver.

**Comment by yifanlu** [comment]
> The web client works fine (no certificate issues). My home server uses let's encrypt.

It works fine from Safari and Chrome for me.

**Comment by richvdh** [comment]
@yifanlu: any errors in the console in the developer tools?

**Comment by yifanlu** [comment]
Only some 404 errors on the default matrix web client by visiting the home server URL directly. No errors trying to log in from riot.im

**Comment by richvdh** [comment]
I meant in the desktop client.

This isn't a great place to handle support queries; I suggest asking in #riot instead.

**Comment by yifanlu** [comment]
Thanks. I've asked in #riot but haven't gotten any response. However, I don't think this is a support query--it is a bug report for the desktop Riot client. I'm not sure if the right protocol is to continuing commenting on this closed issue or to open a new one (I don't know if OP had the same problem as me).

The output from the dev console is
```
index.js:218 GET https://myserverurl:8448/_matrix/client/r0/login net::ERR_INSECURE_RESPONSE
```

Since Chrome and Safari both work, there is some reason that the Riot app isn't seeing the root CA. Maybe Electron uses its own set of CAs?

**Comment by richvdh** [comment]
#riot does tend to be a bit quiet at 03:00 UTC. I did reply later, but you don't seem to have checked back. 

The original report here was pretty unclear, which is the main reason I closed it; you could open a new issue if you like, but I'm yet to be convinced there is a bug in riot-web.

As I understand it, Chrome (and Electron) use the system CA trust list. I'm pretty sure this works, because the cert on my own HS is signed with a custom CA. I have imported that CA into the system list, but have not done anything specific for the Electron app.

You mentioned you are using letsencrypt; I would expect that to work fine. Are you sure you are including the intermediate certificates in the browser response?

It might help if you could tell us what your server URL is so we can investigate.

**Comment by shula** [comment]
i have the same issue without "letsencrypt" (i don't even know what it is).
same symptoms as above: All of my webbrowsers (ff/chrome/opera) can connect freely, but the desktop app can't.
I even disabled temporarily my firewall - didn't solve it.
i'm using Windows 7.

**Comment by aaronraimist** [comment]
@shula this is an issue with your server, not Riot. What server are you trying to connect to? (probably best to respond to me in [#synapse:matrix.org](
https://matrix.to/#/#synapse:matrix.org) rather than clutter this issue.

cc @alexis-thual
