### ISSUE TITLE
if you expand a set of joins/parts, then scroll back down to the bottom, it unexpands as soon as you hit the bottom

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#2916]

**Comment by ara4n** [comment]
sounds related to #2752

**Comment by lukebarnard1** [comment]
I've realised that this is because the MELS uses the first member event ID as its key. This means that it will become an entirely new MELS when events are unpaginated from it.

To fix this, it will require a key that does not change when events are taken off from the front, so it probably can't be an event ID.

**Comment by ara4n** [comment]
. o O ( MELS1, MELS2, MELS3 ;)

**Comment by lukebarnard1** [comment]
@ara4n yep, I was thinking the same. /me shall implement.
