### ISSUE TITLE
Team-based registration

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2940]
This is quite closely related to #2430.  For various Riot uses we want the ability for users to optionally select a team when they join up - e.g. to declare affiliation to a particular university or something.

This means having a dropdown on the registration page, enabled from config.json, that says: "For specific rooms & features, select from the list below".

The list would be something like:
 * Cambridge
 * Oxford
 * Other
 * none

Selecting a team from the list would prepopulate up the email field with a given template of email address in order to force you to prove your membership of the team based on email address.  For instance, if you select Cambridge, it'd force your email to be "...@cam.ac.uk" (with the suffix being not editable).

If folks select Other, i suggest we show a link saying "If your $team is not listed, click here to email support@riot.im to get it added".

Having selected a team, you get dumped into the custom Welcome Page described in #2430.

**Comment by lukebarnard1** [comment]
http://github.com/matrix-org/matrix-react-sdk/pull/620 needs altering so that the configuration for teams is acquired from a configured http://github.com/matrix-org/riot-team-server.

1. User registers successfully 
2. (Optional) RTS is hit to track the referral. This will provide user with the team_token
3. Team token is used to get team configuration for auto-joining/welcome page
