### ISSUE TITLE
Desktop app lacks installation instructions

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#2952]
We just link to the deb repo, with few clues about what to do with it. rtivers provided steps for synaptic users at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14844819341590538xhZmK:matrix.org, but maybe it would be better to link to the deb and have that configure the repo in the same way that Chrome, Dropbox and others do?

**Comment by uhoreg** [comment]
Another user wrote these instructions as well: http://data.agaric.com/how-install-riot-desktop-matrix-client-debian-based-systems

**Comment by uhoreg** [comment]
Also, a note about the instructions at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14844819341590538xhZmK:matrix.org: the apt-key command should use the full 16-character long key ID instead of the 8-character short key ID, since the short key is vulnerable to collisions.

Another possible set of instructions is:

```
$ curl https://riot.im/packages/debian/repo-key.asc | sudo apt-key add -
$ sudo apt-add-repository https://riot.im/packages/debian/
$ sudo apt update
```

which might be easier even for GUI users since the GUI instructions require you to open the terminal anyways.

**Comment by carlos22** [comment]
Related: https://github.com/vector-im/riot-web/pull/2809/commits/2b70cb436eb52f450a063a36dbb2b98d22d9d733
The apt-add-repository is only installed on ubuntu desktop variants. But it can be installed in debian since Jessie with `sudo apt-get install software-properties-common`. The main advantage is that you don't need to know and edit the distribution code name.

**Comment by taw00** [comment]
FYI, your issue title should probably read "Desktop app for debian users lacks installation instructions"
Because then you go on about .deb's.

Anyway, if on Fedora or RHEL the installation instructions are literally 3 lines:
https://github.com/taw00/riot-rpm/blob/master/README.md

But that is not the same as comprehensive nicely written out installation documentation for all platforms located on the riot.im website.

**Comment by uhoreg** [comment]
This seems to be a dup of #2845.

**Comment by richvdh** [comment]
Indeed it does.
