### ISSUE TITLE
HiDPI support?

### ISSUE THREAD

**Issue by ArchangeGabriel** [vector-im/riot-web#3132]
The desktop app based on electron is apparently not scaled. Since I’m new to electron, not sure whether this is a more general issue of it or something that should be fixed on riot side.

**Comment by alexmat2on** [comment]
I have a HiDPI computer; the electron package scales perfectly by itself, on both Windows and Linux.

**Comment by ArchangeGabriel** [comment]
@alexmat2on Interesting. What setup on Linux (DE/env vars related to HiDPI/same for xorg conf files)?

**Comment by alexmat2on** [comment]
Oh boy, it's been a while since I set this all up, so I can't gurantee that I'd remember everything. 

The gist of it is that I run `xrandr --dpi 192` on startup (this gets most of everything), in my ~/.Xresources file I have `Xft.dpi: 180` (for fonts and system text), and I also have the `GDK_DPI_SCALE=1` environment variable set. Not sure if that's doing anything or not...

**Comment by ara4n** [comment]
riot-web is all designed for HiDPI - all the artwork is vector SVGs and will scale as well as the browser can manage.  If electron isn't working correctly on your system it's likely problems with the X11 config, as per @alexmat2on's advice.

**Comment by ArchangeGabriel** [comment]
OK, so the problem is apparently with electron, but I was able to work around by passing `--force-device-scale-factor=2` as argument. Thanks to [nvllsvm](https://aur.archlinux.org/account/nvllsvm) for the advice.
