### ISSUE TITLE
Possible to use it anonymous with Tor?

### ISSUE THREAD

**Issue by Mattel88** [vector-im/riot-web#3235]
Matrix looks like a good solution but is it possible to connect over Tor or is anything planning for that?

**Comment by richvdh** [comment]
yes, people use riot-web via Tor just fine.

**Comment by hThoreau** [comment]
Hi,

Since yesterday, when [Riot suffered a DDoS attack](https://twitter.com/matrixdotorg/status/974582628585279488), I'm unable to log in using riot-web on tor. Even after the situation has been announced as being [resolved](https://twitter.com/matrixdotorg/status/975025266996207617). I'm getting an error message sggesting that I've been blocked: "Error: Problem communication with the given homeserver. (HTTP 403)"

I'm using Riot version 0.13.5, obtained through the F-Droid repository. the repository `https://riot.im/packages/debian stretch/main amd64 Packages`.
