### ISSUE TITLE
Room notification badges flash on and off as you read messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3257]
Sounds like a regression of https://github.com/vector-im/riot-web/issues/967 perhaps caused by @lukebarnard1's new StatusBar stuff?

**Comment by lukebarnard1** [comment]
I'll need a bit more information to investigate. I'm not sure why the status bar would have anything to do with it.

**Comment by ara4n** [comment]
This is probably caused by the server idea of unread status getting out of sync with the client's idea, and the two racing together.  There was a big bug about this (which is basically a design flaw in the protocol), but I can't find it.  @dbkr do you remember where it went?

**Comment by dbkr** [comment]
Having just talked through this with luke, I've realised what the problem is: we are doing 'local echo' of the notification counts when setting them to 0, but when the server is being slow, the next time a sync returns it will still have the unread count saying you have unread notifs because it hasn't caught up yet. We can fight it and set it back to zero, but this will keep happening until the server actually catches up.

Fixing this is nontrivial because it essentially requires us to be smarter about our notification count 'local echo', ie. somehow deciding when to ignore a badge count from the server.
