### ISSUE TITLE
link to community-written guides somewhere

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3308]
Since Riot doesn't have any official documentation yet, it would be helpful to link to guides written by the community, such as https://gitlab.com/maxigaz/how-to-riot and https://forum.disroot.org/t/matrix-riots-usage-basics/947 somewhere in the riot.im site

**Comment by joelostblom** [comment]
I was just going to ask about the availability of user documentation! I am promoting using Riot in a class instead of Slack as our GitHub chat client, and was looking for some write-ups either on Riot itself or in comparison with similar apps (for different use cases). I think it would definitely be helpful to include links to those documents in the README. Thanks for bringing them to my attention!

**Comment by tessgadwa** [comment]
Yes! Perhaps it is time to add the ubiquitous question mark icon somewhere to the UI. (Recommend top right, as this is fairly standard.)

These guides would work as interim content.

**Comment by uhoreg** [comment]
possibly https://opensource.com/article/17/5/introducing-riot-IRC too

**Comment by uhoreg** [comment]
also https://www.uhoreg.ca/blog/20170910-2110

**Comment by benparsons** [comment]
@uhoreg awesome idea. I added all except https://gitlab.com/maxigaz/how-to-riot as it seems dated now.

Any other suggestions like this can go to /matrix-org/matrix.org
