### ISSUE TITLE
/join command should default to current bridge

### ISSUE THREAD

**Issue by aruiz** [vector-im/riot-web#3358]
For the sake of simpleness, it would be nice to default /j #channel to the same bridge that the current window is on. For example, /j #gtk+ inside a chat window that belongs to the GIMPNET irc bridge, should default to that bridge.

**Comment by ara4n** [comment]
we don't really have the concept of "the current bridge" as rooms can and are often bridged many different places. so the best we can do here is to provide good autocomplete options so that `/j #gtk+<tab>` will automagically bring up /join #_gimpnet_gtk+:matrix.org`.  This is handled as part ofo https://github.com/vector-im/riot-web/issues/1763.
