### ISSUE TITLE
Dark theme: you can't see the quote mark in the dark theme, so for unrenderable URL previews it looks like a oddly-large gap.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3393]
surely they should take up zero height if they don't load

**Comment by lampholder** [comment]
Have you got a screenshot/good example? URLs that don't resolve to real domains/pages don't seem to be taking up any height for me on develop or stable.

**Comment by ara4n** [comment]
...........actually this isn't a regression, it's always been like this. but on the dark theme you can't see the quote mark so it looks like entirely whitespace.

<img width="835" alt="screen shot 2017-03-09 at 14 49 49" src="https://cloud.githubusercontent.com/assets/1294269/23755294/bb33142e-04d7-11e7-9ed7-9dd8472fc041.png">

**Comment by lampholder** [comment]
Two/three possible fixes:
 - change the styling on the dark-theme quote (easy)
 - render a 'this URL can't be previewed' note rather than an empty quote (also easy, slightly more time-consuming)
 - in the case of the specific example, make the URL preview thing able to preview JSON (marginally less easy, again more time-consuming, actually quite useful)

**Comment by lukebarnard1** [comment]
Kind of fixed by https://github.com/matrix-org/matrix-react-sdk/pull/870#event-1072789491
