### ISSUE TITLE
Invite UI: always show entry for unknown user

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#3404]
### Description

I'm unable to add in a room a newly created user, using his matrixid: @riotuser:matrix.org

### Steps to reproduce

- In a room, click on invite a user
- Enters the matrix id of an existing user (mine was just created)
- Press Enter

EDIT: this doesn't work especially with @riotuserup:matrix.org
Riot select the first item of the list but this is not the one I want
Riot hide the "send invites" button and proposes me a list of users looking like the matrixid
![invite withoud send](https://cloud.githubusercontent.com/assets/22364949/23798845/9fd10090-05a6-11e7-8143-4ab413ddd584.jpg)

- **Browser**: Chrome Version 56.0.2924.87 (64-bit)
- **OS**: Windows Seven 64
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
1. Not being able to invite a new user: this is because the list of available users is actually a client-side list of all users in all rooms that you are in. It's not a server-side search.
2. Only being able to select the first user: the UI is possibly slightly confusing here, but you can click on the items in the list to add users. Once you're finished adding users (potentially only one user), you can click "Send invites".
3. "Send invites" is hidden:  it reappears once you've clicked on an item or hit <kbd>Enter</kbd>

![gifrecord_2017-03-13_165254](https://cloud.githubusercontent.com/assets/6750344/23865452/afbf3f3a-080d-11e7-8347-a990cb2360fc.gif)

**Comment by jeangb** [comment]
@lukebarnard1 Hi, thank you for the details.
So it's not possible to invite a user using his matrixid if I never have been in a room with him ?

**Comment by jeangb** [comment]
I think this is a regression because I'm able to add an unknown user by his matrixid in /app, but I can't do it with /develop.

With /app when I finish entering the full matrixid, riot stops to propose me a list of known user and only show me an item that I can click on with the matrixid I entered. This unfortunately doesn't work with /develop

**Comment by lukebarnard1** [comment]
> With /app when I finish entering the full matrixid, riot stops to propose me a list of known user and only show me an item that I can click on with the matrixid I entered. This unfortunately doesn't work with /develop

Ah. I do remember this feature...

I've tested on /develop, and it gave me an entry:
![2017-03-14-093420_692x326_scrot](https://cloud.githubusercontent.com/assets/6750344/23894314/8525dd9c-0899-11e7-9e25-ccd4aae6e3b2.png)

I could then create a new DM room with them invited.

**Comment by jeangb** [comment]
I didn't see that ! so the matrix id needs to be long enough to reproduce the bug on develop.

I know that I abuse by creating a lot of "riotuserXX", but yes, I think we should have an option to send an invite to an unknown user, because right now I can't send an invite to @riotuserup:matrix.org on /develop.

**Comment by lampholder** [comment]
This has been fixed by.
