### ISSUE TITLE
Incorporate ux feedback from @neutral:matrix.org

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3420]
https://public.etherpad-mozilla.org/p/riot_complaints

**Comment by AmandineLP** [comment]
I opened/referenced appropriate issues:
 Lack of true "reply-to/quote" feature
the quote-feature already there, or do you want to enhance it to also store the reference for jumping? <-- yes, like in telegram :/ It shows the original author + allows you to click to jump to the message for further context +1 - also it would be nice if it alerted like telegram - https://github.com/vector-im/riot-web/issues/2409
- iOS: Tap message to access message context menu is non-standard UI. Long-press is more expected - https://github.com/vector-im/riot-ios/issues/1093
 iOS: tapping a link should open it in a browser, instead I have to long press it to bring up the menu to open the link, or 3d touch it and press hard enough to open the preview (https://github.com/vector-im/riot-ios/issues/1094)
Basically, the above behavior is expected to be switched for most users
- iOS: Lack of sharing intents (resulting in kludgy "share this picture" UX) (https://github.com/vector-im/riot-ios/issues/514)
- Lack of last-read-point synchronization (which is a much bigger core matrix problem we know) (https://github.com/vector-im/riot-ios/issues/395)
- iOS: App scrolling is not smooth (resulting in scroll jumps/general "bad" feeling while scrolling through history) - https://github.com/vector-im/riot-ios/issues/1097 
- iOS: can't drag down photos to close them, have to click the back arrow instead (which is also buggy when playing videos) - https://github.com/vector-im/riot-ios/issues/1095
- web: can't paste images from clipboard - this is fixed on dev - I love you, but doesn't seem to work on /develop :( - hold on let me try an actually supported browser... - not working in chrome on linux - Try enabling Rich Text Edition in Settings/Labs
- android: Keyword-changing for notifications (just possible on web currently)
keyword-changing per room - https://github.com/vector-im/riot-android/issues/472
- iOS: tapping on any whitespace in the chat should close the keyboard (https://github.com/vector-im/riot-ios/issues/1096), as well as dragging the chat down (like iMessage) -> this works on latest iOS app
- iOS (and android?) need user auto complete, some chat programs even change the keyboard so that there is an @ key available that brings up the user list *
 * currently only way to do this is by tapping a user which enters their nickname in the entry box, unintuitive and hard to use if they didn't recently say anything - https://github.com/vector-im/riot-ios/issues/1098
- iOS: Cant save videos that have been shared - Long tap on the video works. Please can you rageshake?
- web: I realize edge isn't a supported browser but it would be nice, and I've noticed that images don't scale correctly

**Comment by lampholder** [comment]
@AmandineLP is the only issue from above that's not been triaged into its own issue the lack of Edge support?

Can this be closed?

**Comment by lampholder** [comment]
Closing because I think all of the relevant information has been captured. @AmandineLP please reopen if you disagree.
