### ISSUE TITLE
Check for updates feature for electron app

### ISSUE THREAD

**Issue by kethinov** [vector-im/riot-web#3485]
Would be nice if the app automatically checked for updates and had the standard menu item option for checking for updates so users don't have to follow the project on github or twitter to know when new releases are available.

**Comment by richvdh** [comment]
I thought it did

@dbkr ?

**Comment by kethinov** [comment]
Oh if it does already that's great!

I do notice there doesn't appear to be a way to manually check though (to verify you have the latest client) without diffing the version number against the releases page.

**Comment by lampholder** [comment]
Triaged as a:
 - bug (because it's a bug)
 - P2 (because not picking up changes is something we should definitely fix soon if it's really happening)
 - major (because the whole 'feature' of detecting updates is broken)

From the conversation it _sounds_ like maybe everything's fine, but waiting on @dbkr to verify that this is a feature that should exist before then spending any time checking if there's been a regression.

**Comment by kethinov** [comment]
I got an auto update notification from 0.9.8 to 0.9.9 and it seemed to work okay.

There doesn't seem to be a way to manually check if you're up to date, but auto updating does seem to work.

**Comment by lampholder** [comment]
Hooray :)
