### ISSUE TITLE
Read indicator shows date on wrong messages after midnight passes

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/riot-web#3523]
### Description

After midnight passes, messages read today will be marked "Seen by @example:matrix.org at *date*, *time*", yet messages read yesterday will be marked "Seen by @example:matrix.org at *time*".

### Steps to reproduce

- Start Riot before midnight
- Wait until midnight passes
- Wait until someone reads a message
- Check message indicator for a message before and after midnight

![riotyesterday](https://cloud.githubusercontent.com/assets/1885159/24381290/e240f8d4-134f-11e7-9de4-d6cf9a98f6c3.jpg)
![riottoday](https://cloud.githubusercontent.com/assets/1885159/24381291/e6d991c6-134f-11e7-9f79-c5b43b048fee.jpg)
On these screenshots, please notice the "Seen by" tooltip and the system time in the bottom right corner.

### Version information

- **Platform**: desktop
- **OS**: Fedora
- **Version**: 0.9.7

**Comment by lampholder** [comment]
Could we fix this by updating to "Seen by @example:matrix.org at date, time" across the board?

**Comment by lukebarnard1** [comment]
This was deliberate from @Kegsay as of https://github.com/matrix-org/matrix-react-sdk/pull/586

The date is shown only if the receipt has a timestamp that is _on or after_ the day of the event timestamp. It feels like this should be based on "today" instead of the timestamp of the event. As in, show the date if the date is different to today's date.
