### ISSUE TITLE
Indexeddb only persists history ~5 minutes after initial sync completes

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3527]
I launched riot.im/develop for the first time on a new session.  I waited forever for the initial sync to complete.  I then refreshed the page after a few minutes of use.  It resynced from scratch all over again.  Surely the second our initial sync completes we should be persisting it to indexeddb?

**Comment by lampholder** [comment]
MAJOR because it sounds like we're not reaping the full benefit of the indexdb in this particular case.

Assigning to @dbkr to consider along with the other bits he's looking at for the next riot web release; I think this might turn out to be release-blocking, though that depends on the specifics around it.

**Comment by lampholder** [comment]
@dbkr did you manage to look at this alongside the other indexdb stuff you were looking at?

**Comment by lampholder** [comment]
Let's make it so it saves after the first sync.
