### ISSUE TITLE
'Add phone number' option on the Settings page is in the email section.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#3531]
It should be in the phone section :)

**Comment by GeneralMeow** [comment]
Could you point me to the right file for this?

**Comment by ara4n** [comment]
Sure - it's https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/UserSettings.js#L849

However, I think the bug is a little confusing here - it's true that if you don't have a phone number already, it looks like the phone number is in an email section:

<img width="434" alt="screen shot 2017-04-20 at 01 19 42" src="https://cloud.githubusercontent.com/assets/1294269/25207555/7db34bea-2567-11e7-8503-72e4577e5095.png">

However, if you do have a phone number already, it becomes clearer that these aren't section headings but just labels on the text boxes:

<img width="439" alt="screen shot 2017-04-20 at 01 17 51" src="https://cloud.githubusercontent.com/assets/1294269/25207571/92c08c82-2567-11e7-9833-79cd634bc869.png">

A good solution would be to just group the emails into one section and the phone numbers into a following section though, and then things would be somewhat clearer.

**Comment by ara4n** [comment]
i went for adding in the labels rather than fixing the grouping.
