### ISSUE TITLE
On desktop version, indicate that you have a new message on the tray icon

### ISSUE THREAD

**Issue by exap** [vector-im/riot-web#3554]
The tray icon should be adjusted if there is a new message.

**Comment by lampholder** [comment]
This would be a nice feature to add.

**Comment by lalomartins** [comment]
I had this on my version of the tray patch, but then a better implementation was merged, and now I miss the feature 😺 I guess I'll reimplement it, it was no rocket science.

If anyone wants to try first, here's the corresponding commit: https://github.com/lalomartins/riot-web/commit/f71359a18fbbf7c80e9e2394992cfa0ac01c5870 — note you can't just apply it directly, since the underlying code is quite different.

**Comment by t3chguy** [comment]
@lalomartins thanks for this, I'll cherry-pick your commit and make a very abstract merge so your contribution will be in the history

**Comment by lalomartins** [comment]
Basically, the changes to tray.js have to be rewritten from scratch, with mine as a reference. The rest may or may not apply (the icons obviously will). I did try to cherry-pick it on Tuesday but it blew up in my face, and unfortunately I had a busy week.

If you can't get it to work, I may find time today, though. Let me know.

**Comment by t3chguy** [comment]
Cherry picked and merged, just figuring out `Unhandled exception TypeError: Error processing argument at index 0, conversion failure from 9` errors

**Comment by t3chguy** [comment]
@lalomartins done and it works, just gonna tidy it up now

**Comment by t3chguy** [comment]
@lalomartins sadly had to implement it completely differently as generation of static assets like those logos has to be scripted. The way I did it, it simply mimics the favicon and so even has the number of notifications :)

**Comment by lalomartins** [comment]
This makes me about as sad as my icon implementation not being used in the first place. Namely, not even a little bit. I get an implementation that solves my need and as a bonus I get one that does it *better*, and on top of that my effort wasn't lost it because at least it helped you figure things out. Wins all around.

Thanks! I'll be watching the new PR.

**Comment by t3chguy** [comment]
closed via #3909
