### ISSUE TITLE
The 'World Readable' label in the room directory is confusing

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3562]
Especially for people unfamiliar with Unix permissions.  Something like 'Publicly Readable' might be clearer.

**Comment by lampholder** [comment]
I agree 100% that 'World Readable' is confusing.

As I understand it, the concept we're trying to convey is that 'anybody in the world can read this room, without actually having to join it'. Which is distinct from 'anyone can join this room'.

The importance of this distinction is not clear, especially to a new user - to the uninitiated, 'reading' is likely synonymous with 'joining and reading'.

I wonder if the concept and its implications are actually too nuanced for a text label - if we had a more abstract representation for these instead, the hover text could reveal a more complete description of what's going on.

Perhaps preferably, we could drop 'World Readable' (since users discover how they're going to read the content when they click the room anyway), and we could replace 'Guests can Join' with a 'Guests _can't_ join' if the current user is a guest (I can't see why a registered user would care particularly about a room's guest policy, at least often enough to warrant this status being afforded such prominence in the directory).

**Comment by aaronraimist** [comment]
This is gone right? https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/RoomDetailRow.js doesn't seem to get used anywhere

**Comment by jryans** [comment]
> This is gone right? https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/RoomDetailRow.js doesn't seem to get used anywhere

It is still used in the communities room list, but not the general room directory, so seems fine for this to remain closed.
