### ISSUE TITLE
following links of form https://matrix.to/#/@user:matrix.org remove you from current room

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3586]
it's great they show MemberInfo and all, but they shouldn't hijack you out of your current room, surely

**Comment by lampholder** [comment]
This certainly is annoying. What would be better?

I'd suggest:
#### If you click on a https://matrix.to/#/@user:matrix.org link and @user:matrix.org _is_ in your current room
- Just render that user's memberinfo in the right hand pane same as always.

#### If you click on a https://matrix.to/#/@user:matrix.org link and @user:matrix.org is _not_ in your current room
- Render the user's memberinfo in the right hand pane, but customise the UX so that it makes more sense.
- Right now, the pane shows this:
![screen shot 2017-04-20 at 18 16 55](https://cloud.githubusercontent.com/assets/1922197/25243724/f6640366-25f5-11e7-98ef-bc5bc3023129.png)
- We should modify this so that:
    - It doesn't have a spurious 'Level' field (if the user isn't in your current room they don't have a level)
    - It does have a '(+) Invite @user:matrix.org to #matrix:matrix.org' button

**Comment by lampholder** [comment]
![member_info](https://cloud.githubusercontent.com/assets/1922197/25244737/d6612fea-25f9-11e7-8db8-c13376c6f4e6.png)

We could solve the specific problem by using the above mockup, but I feel like this panel is ripe for a general (though not presently high priority) overhaul.

I guess we should just see how close to a more general overhaul we are when we eventually do pick up this bug and make our decision as to our course of action then.

**Comment by lampholder** [comment]
Also related: https://github.com/vector-im/riot-web/issues/655

**Comment by ara4n** [comment]
bumping priority now we have mentions

**Comment by lukebarnard1** [comment]
This has been [fixed for mentions](https://github.com/matrix-org/matrix-react-sdk/pull/1297/), but not for user matrix.to links in general

**Comment by t3chguy** [comment]
wrong button :((
