### ISSUE TITLE
the timeline jumps enormously on back pagination.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3662]
if i scroll back to the top of a room, and the server is slow to respond to the /messages request, i see the spinner at the top. once the request completes, i get jumped to an entirely different part of the timeline. this used to work.

**Comment by turt2live** [comment]
I can't reproduce this on riot.im/develop Chrome 57, Windows.

**Comment by lampholder** [comment]
@turt2live have you failed to reproduce in the same conditions - i.e. have you seen back pagination move to the _right_ part of the timeline even when the server is slow to respond?

I haven't (yet) been able to reproduce because I haven't encountered any slow response times.

I've p2'ed this for now; we can reevaluate as we gather more evidence for this.

**Comment by ara4n** [comment]
i've seen this about 10 times since i filed it.  (that said, the regression has been around for ages - this is basically the same as #2138 and in turn #2646.

**Comment by ara4n** [comment]
i'll close this in favour of #2646 and try to get a video.

**Comment by turt2live** [comment]
ftr I used Chrome's throttling option to mimic a slow connection. I then used varying combinations of mashing/holding page up and scrolling to try and get it to misbehave without luck. It simply popped the content in above the topmost message, without moving the view. I did encounter this before, as noted in #3576
