### ISSUE TITLE
It's still quite easy for the (...) to get stuck on RoomTiles

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3672]
like so: cursor had long since moved away :(

<img width="249" alt="screen shot 2017-04-20 at 14 26 27" src="https://cloud.githubusercontent.com/assets/1294269/25233068/6cc23fb2-25d5-11e7-8384-c55190925375.png">

**Comment by lampholder** [comment]
Looks very glitchy.

**Comment by lukebarnard1** [comment]
We could just do this with CSS? 
```
.RoomTile:hover .badge {
 display: yes please;
}
```

**Comment by lampholder** [comment]
Oh my, CSS certainly seems like a sensible way to solve this problem 😃

**Comment by ara4n** [comment]
i think the reason to avoid CSS was to avoid bloating the DOM too much, and because we want it to keep hanging around whilst you navigate the context menu.

**Comment by nightpool** [comment]
![menus](https://cloud.githubusercontent.com/assets/233815/25592877/6778de7e-2e88-11e7-8e8a-243de8c7b7b9.gif)

**Comment by lukebarnard1** [comment]
`RoomList` could contain an index that represents the currently hovered `RoomTile`.

**Comment by jfrederickson** [comment]
I think when I usually see this behavior, it's after quickly mousing away when switching rooms as @nightpool observed.

This is also very easy to trigger for room members by quickly mousing over them - wasn't able to find another issue for that so I'm putting this here since it's similar behavior:

<img width="240" alt="screen shot 2017-05-10 at 8 09 56 am" src="https://cloud.githubusercontent.com/assets/1923178/25897981/1d7ef0ac-3558-11e7-94c6-e481b7a14c08.png">

**Comment by ara4n** [comment]
promoting this to major as the glitchiness is horrid

**Comment by uhoreg** [comment]
dup of #2420
