### ISSUE TITLE
client gets stuck with invites even after they get rejected

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3743]
if we can't reach a remote server when rejecting an invite, we just flag it as rejected locally. But it looks like we forget to update the client (via /sync).

Workaround is to flush the cache in the client.

**Comment by richvdh** [comment]
this is a synapse bug really

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/issues/2181

**Comment by rschulman** [comment]
I have an instance of what I presume is this. Stuck invite, can't join or reject it. Its just sitting in my room list and making Riot display a notification bubble constantly. I run my own homeserver. Any way to kill it?

**Comment by t3chguy** [comment]
@rschulman after you reject it (and fail), clear client cache
there is a known bug where Synapse doesn't inform you about the reject in the Sync stream

**Comment by aaronraimist** [comment]
While we wait for this to be fixed in Synapse, Riot should just remove that room from its own database when I click reject. This is what Quaternion does and it means that at least you don't have to clear cache on all of your devices, you just have to click reject on all of your devices.

**Comment by t3chguy** [comment]
I'll look into this shortly

**Comment by scottwallacesh** [comment]
Any progress?

**Comment by t3chguy** [comment]
As for the workaround at this level, its too ambiguous in the case of what happens when a real re-invite comes through. This issue is blocked on Synapse fixing their issue.

**Comment by benbucksch** [comment]
### Description
I logged in to my account after a months long absence. After logging in, I see an invitation from somebody. But I cannot dismiss it. Every action says that the room has been deleted. But the invitation does not go away, no matter what I do.

### Steps to reproduce
I received a chat invitation from @mwyraz:matrix.org . I have no idea whether that's a spammer or a legitimate open-source developer who wanted to contact me. I have no idea when the invitation happened.

### Actual results:
* I see 3 buttons:
  * [Start chatting]
  * [Reject & Ignore user]
  * [Reject] / [Ablehnen]
* After I click on them, all of them show that the action failed, because:
  * the room is unknown
  * the server is unknown
  * or the action just stalls without result
* What makes this bug serious is that none of the actions result in the invitation being removed. No matter what I do, the invitation stays. I cannot remove it.
* The invitation shown very prominently both at the start page (literally "front and center") and prominently at the top right, above the room list. Very annoying.

### Expected result:
* Invitation does not show, if the room has been removed. OR:
* Invitation is removed, after I click on one of the options and the system notices that the room has been removed. At least at this point, the invitation should be removed.
* The invitation should definitely be removed, if I click "Reject". But that does not happen.

### Screenshots:
After I log in:
![image](https://user-images.githubusercontent.com/1907525/75038030-c4746e80-54b5-11ea-8ee2-2d4877874d05.png)

After I click [Reject], the UI stalls (forever, so I need to refresh the browser page):
![image](https://user-images.githubusercontent.com/1907525/75038045-c8a08c00-54b5-11ea-81b7-a5bc1eaad96c.png)

After I click [Start chatting], I get "No known servers":
![image](https://user-images.githubusercontent.com/1907525/75038055-ce966d00-54b5-11ea-884f-19d99d85ed01.png)

After I click [Reject and Ignore], I get "Unknown room":
![image](https://user-images.githubusercontent.com/1907525/75038062-d35b2100-54b5-11ea-9098-0960127b3711.png)

### Version information
* Platform: web (in-browser)
For the web app:
* Browser: Firefox trunk
* OS: Ubuntu
* URL: riot.im/app

In my user settings, tab Security and Privacy, I found an option "Reject all 1 invitations". That button has no effect, either. It refreshes, but stays with 1 invitation.
![image](https://user-images.githubusercontent.com/1907525/75037997-b7577f80-54b5-11ea-9438-326997405611.png)

### Importance
This is a pretty serious issue. And a bug that shows "front and center" for new users.
 
Can this be fixed, please? If this needs to be fixed upstream, then please submit a patch there.

**Comment by t3chguy** [comment]
@benbucksch the upstream issue you want to track is https://github.com/matrix-org/synapse/issues/2181

**Comment by aviau** [comment]
Also getting this issue on riot.im:

![Screenshot from 2020-04-05 23-56-51](https://user-images.githubusercontent.com/2706882/78521815-299bcf00-7799-11ea-9154-fa4e4ad67217.png)
![Screenshot from 2020-04-05 23-56-57](https://user-images.githubusercontent.com/2706882/78521816-299bcf00-7799-11ea-8a10-35fa9312c5ed.png)


The body of the network response:
```{"errcode":"M_FORBIDDEN","error":"No create event in auth events"}```

**Comment by t3chguy** [comment]
@aviau clear client cache in settings after hitting Reject. This is a Synapse bug.

**Comment by Dragnucs** [comment]
@t3chguy where do you clear this cache from the web client at riot.im/app?

**Comment by t3chguy** [comment]
Settings > Help & About

**Comment by tomusdrw** [comment]
This bug is really annoying and can one's life miserable if you get spammed by room invites (just saying). Any progress or estimates when it would be addressed?

**Comment by t3chguy** [comment]
As per above, the issue is upstream: https://github.com/matrix-org/synapse/issues/2181

**Comment by richvdh** [comment]
fixed by https://github.com/matrix-org/synapse/pull/7804

**Comment by justdave** [comment]
Was still seeing this in Element/android... here's my workaround to get rid of it.

In my case, I had both the invite message that wouldn't go away and a working DM window with the same person.

In Riot/web (or desktop):
1. go to the working DM window (or any window if you didn't have a working one with that person)
1. type `/devtools` and hit Enter
1. in the popup, click on `Explore Account Data`
1. click on `m.direct`
1. scroll to the bottom and click `Edit`
1. find the person in question in the list. In my case, they had two room hashes listed under them. If you never had a real DM window with that person there'll only be one.
1. If you never had a working DM window with that person, just remove their entry.
1. If you did (like I did), look at the top right corner for the room ID (since you were in the working one when you ran devtools). Do NOT remove that one, but remove the other from that person's list.
1. Click `Send` at the bottom.

Make sure you keep valid JSON syntax when editing it (beware of commas, etc).
