### ISSUE TITLE
Room Directory 'all-network' never shows anything but the HS

### ISSUE THREAD

**Issue by pik** [vector-im/riot-web#3769]
The room directory when selecting 'all-network' only shows rooms local to the HS, not even rooms joined on other servers. 

develop @ 67efb8bde264e3ea0823e40558d29dd89120c0c9

![screenshot from 2017-04-29 09-34-31](https://cloud.githubusercontent.com/assets/10236920/25556270/4ee663e2-2cbf-11e7-81ff-32d872953219.png)
![screenshot from 2017-04-29 09-34-47](https://cloud.githubusercontent.com/assets/10236920/25556273/528d19d2-2cbf-11e7-9ea7-c798046cbb53.png)

**Comment by lampholder** [comment]
If your homeserver is like mine, your dropdown will look something like this:
![image](https://cloud.githubusercontent.com/assets/1922197/25705936/de956022-30d6-11e7-8a4a-b646f11495b1.png)

It's not super obvious, but the `[m] Matrix` is a subcategory of lant.uk - clicking it shows all the matrix rooms on that homeserver (rather than all matrix rooms everywhere). If I had bridges set up on my homeserver (and those bridges were configured correctly) I'd see those bridges as subcategories of `[m] Matrix`.

So I think you _should_  be seeing a big list of all the rooms on your local homeserver (including rooms federated across your homeserver and other homeservers) - does that match what you're seeing?

**Comment by pik** [comment]
> It's not super obvious, but the [m] Matrix is a subcategory of lant.uk - clicking it shows all the matrix rooms on that homeserver (rather than all matrix rooms everywhere). 

I'm not sure what you are talking about, where are you seeing the option for all the Matrix rooms everywhere? 

> clicking it shows all the matrix rooms on that homeserver (rather than all matrix rooms everywhere). 

It explicitly does not, you can see that my client is in the Riot room - but the Riot room does not appear in the directory.
