### ISSUE TITLE
"Guess DMs" button in UserSettings

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#3803]
To help people without any DMs but who have moved over from another matrix client to Riot or who have lost their DM tags.

Continuation of https://github.com/matrix-org/matrix-react-sdk/pull/829

**Comment by lampholder** [comment]
I think I'm uncomfortable with this because I still have unresolved DM vs room/multiplayer DM issues :\

If we're committed to DMs-as-rooms-with-a-DM-tag-and-any-number-of-participants, then having a feature like this makes sense (to help users transition to Riot from another matrix client; obviously it shouldn't be necessary for people who've used Riot from the start)

**Comment by lukebarnard1** [comment]
> I still have unresolved DM vs room/multiplayer DM issues :\

What are these issues, @lampholder?

**Comment by ara4n** [comment]
presumably it's the "DMs should be 1:1" mindset, which misses the various scenarios where it's really really useful to be able to have multiplayer DMs (i.e. inviting bots into them; inviting PAs; inviting 2ndary accounts for the same user; etc).

Right now it *is* necessary for people who used Riot from the start, because https://github.com/vector-im/riot-web/issues/3331 means that loads of people spontaneously lost all their DM tags.  I'm going to up the priority, if nothing else to stop @AmandineLP killing me

**Comment by lampholder** [comment]
>presumably it's the "DMs should be 1:1" mindset, which misses the various scenarios where it's really really useful to be able to have multiplayer DMs (i.e. inviting bots into them; inviting PAs; inviting 2ndary accounts for the same user; etc).

I don't _miss_ the various scenarios where it's useful, I just identify that there's a usability tradeoff to supporting said scenarios which I'm not (yet) convinced is worth making.

**Comment by martindale** [comment]
Is there a solution which prevents this kind of non-determinism?  I really don't like the word "guess" near my code.

**Comment by turt2live** [comment]
In practice we've empirically been fine without this, so closing. Our DMs are also pretty good at figuring it out these days.
