### ISSUE TITLE
inviting someone already in room fails blindly

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#3968]
no way of knowing what happened without looking at the error in network tab of dev tools

**Comment by lampholder** [comment]
I'm not sure what the best fix to this would look like - our options seem to be:
- something in the message pane (an event maybe saying 'X was not invited because they are already present in the room'), or
- a modal popup saying something similar

Both seem quite... big for something you could safely ignore. Thoughts?

**Comment by t3chguy** [comment]
Agreed, did confuse me for a good 60 seconds before I figured out the person was already in the room

**Comment by turt2live** [comment]
worth noting that this doesn't apply if someone uses the `/invite` command rather than the dialog.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2317
