### ISSUE TITLE
Is nodejs a new dependency for riot-desktop?

### ISSUE THREAD

**Issue by ArchangeGabriel** [vector-im/riot-web#3980]
Hi there,

I’m ArchLinux packager for Riot, and I had some troubles building v0.9.10 because https://github.com/vector-im/riot-web/commit/76008e8abd3e89eda16d39260e93e570d44cff7f + https://github.com/vector-im/riot-web/commit/3fb54029d7dff8b66f48d6a50ce4ac92ed268373 added node_modules to riot-desktop (took me a while to figure that and what to do, since we don’t use electron-builder).

Unless I’m wrong, this means that riot-desktop now requires nodejs to run. Is that correct?

I’ve launched riot-desktop without issue on my system without node, so I’m not sure about it. But our checker reported this:
```
riot-desktop E: Dependency nodejs detected and not included (programs ['node'] needed in scripts ['usr/lib/riot/electron_app/node_modules/mkdirp/bin/cmd.js'])
```

Since this is a 20 MiB dependency (plus eventual dependency tree), I’d like to be sure it’s useful.

Thanks!

**Comment by t3chguy** [comment]
I guess that is an implicit effect if you are not using electron-builder
This was required to be able to add native dependencies, in this case, electron-window-state which allows the app to remember and restore its position and size on-screen so that each time you open it it's not back in the default location.

So its not a new dependency as such, its just one if you don't use electron-builder (which is otherwise a dependency for the desktop app)

**Comment by t3chguy** [comment]
though annoyingly, it seems like the only reason it needs it is because mkdirp also has a command line integration. I may be able to strip this out but does not mean that this issue would not crop back up sooner or later

**Comment by ArchangeGabriel** [comment]
It definitively keeps the previous position. So I’ll safely ignore this then. Thanks!
