### ISSUE TITLE
riotbot chat sometimes is not a direct chat

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#3987]
when starting a direct chat as a guest, if I click on create a direct chat, I get dumped in a room with riotbot but the room is not marked as direct chat but is listed in Rooms. If the user creates a room the chat with riotbot is marked as 1:1 (even if it ugly-ly jumps from the Rooms section to People section)

**Comment by lampholder** [comment]
@AmandineLP are you saying that riotbot does different things if, as an unregistered guest user, you click on 'create a direct chat' vs 'create a room'?

If so I'd suspect this is racey behaviour not directly related to riotbot (though is still a problem that needs resolving).

**Comment by AmandineLP** [comment]
yup this is what I observed.

**Comment by lampholder** [comment]
I tested this and got a different result:
- clicked 'create a direct chat'
- landed on the welcome page
- a direct chat had been establish with riot-bot, but that chat session didn't have focus

So potentially something has changed since Amandine's test, but more likely I think the DM/non-DMness or the riot-bot chat is due to a race.

**Comment by lampholder** [comment]
Aaaand I think this is pretty glitchy, but I might suggest we consider launching ILAG with this still unresolved, since most new users won't know the difference between a DM and a room.

**Comment by lukebarnard1** [comment]
Hm I'm not convinced this one will be fixed because the breaking changes would have been after this being reported.
