### ISSUE TITLE
Copying-and-pasting a link from HTML into the RTE causes whatever you type after it to be linked as well

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3990]
### Description

When you copy and paste text from an HTML \<A\> element into the RTE and then type something, whatever you type will be inside the \<A\> element as well.  In addition, the text does not look like a link in the RTE, so there's no way of knowing that it's going to happen until you send the message.

### Steps to reproduce

- copy text from an HTML link (e.g. I've often copied from GitHub issues)
- paste into RTE
- note that it looks like normal text (and in fact doing "inspect element" on the text does not even show that it is an \<A\> element)
  below is a screenshot of me pasting the "vector-im" link at the top of this page into the RTE, along with the "inspect element"
  ![image](https://cloud.githubusercontent.com/assets/1012976/26317339/1ebb91dc-3ee5-11e7-8f7b-5b5d9c05afa2.png)
- type something
  ![image](https://cloud.githubusercontent.com/assets/1012976/26317344/251487b4-3ee5-11e7-91e7-b3d84d30647c.png)
- hit enter
- see that the link that you pasted, as well as the text that you typed afterward is all part of the link
  ![image](https://cloud.githubusercontent.com/assets/1012976/26317350/2d130b20-3ee5-11e7-9e44-f606073dc896.png)

Describe how what happens differs from what you expected.

I would expect that the text that you type would not be part of the link, and I would expect that either links would look like links in the RTE, or else it would strip out the \<A\> tag.

Log: not sent

### Version information

- **Platform**: screenshot is from web, but I've also seen it in desktop

For the web app:

- **Browser**: Chrome 56.0.2924.87
- **OS**: Debian
- **URL**: riot.im/app (0.9.10)

For the desktop app:

- **OS**: Debian
- **Version**: 0.9.9

**Comment by lampholder** [comment]
I was able to reproduce this with:
- new composer on
- markdown off

And I confused the hell out of myself with this one due to github's underline-on-hover link styling :P

The markdownless RTE also tries to reproduce the styling of the copied text, so, if you had your mouse over the github link when you copied it, your link will be underlined in the editor. If your mouse was somewhere else at copytime, it won't. 

I think for this I think we want:
- at the very least for the link text to be posted as a link and your subsequent comments not to form part of that link
- as a stretch goal, links should be styled in the RTE as blue and underlined (exactly as they will ultimately be styled within the message pane)

**Comment by lukebarnard1** [comment]
My guess is that draft-js is storing an `Entity` for the pasted range, which inevitably ends up being everything you type immediately after it.
