### ISSUE TITLE
Riot gets stuck endlessly refreshing/reloading long messages

### ISSUE THREAD

**Issue by rihardsk** [vector-im/riot-web#4009]
### Description

When I paste in a long message, Riot proceeds to endlessly stutter showing and hiding the round message loading progress indicator, and when trying to scroll away it jumps to the end of the message. It seems that the stuttering doesn't occur if I manage to scroll to the middle of the message. Scrolling to the beginning of the message makes the stuttering reappear and Riot jumps to the end again.

### Steps to reproduce

- prepare a text consisting of 350 lines of the letter `a` or any other text
- paste it into Riot

Afterwards the app starts to endlessly refresh the chat pane. The threshold for the bug to appear is around 350 lines. Nothing bad happens with 340 lines or less.

Log: sent

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Chrome 58.0.3029.110
- **OS**: Windows
- **URL**: riot.im/app

For the desktop app:

- **OS**: Windows
- **Version**: 0.9.10

Not sure but this might be related to #3787 as the behavior seems to be similar.

**Comment by ollieh** [comment]
I think what is happening is the scroll panel will try and load more things if there is less than its height's worth of content in the direction it is scrolling. I think the threshold for the problem is 3x(the height of the scroll panel), which results in it trying to forward-fill, not finding any content, then forward-until, so it scrolls to the last message _which scrolls to the beginning of the message_ causing it to try and backward-fill, and then the subsequent backward-unfill removes the message, causing there to be no content and it trying to forward fill again.
