### ISSUE TITLE
riot-bot says "ask me a question" but can't give answers

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4028]
### Description

riot-bot claims it can answer questions, but fails to actually give replies:

> By the way, you can restart the tutorial at any time by typing 'restart', or type 'help' for more details. **You can also ask me a question and I'll try to help if I can**, or type 'joke' and I'll tell you a joke to brighten up your day! :D

(emphasis mine)

![image](https://cloud.githubusercontent.com/assets/1190097/26455566/dd9fcbe2-4127-11e7-9290-9c015e7e1747.png)

### Steps to reproduce

- Ask riot-bot a question

I'd expect the bot to attempt an answer, or at least tell me to see the FAQ sooner.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/experimental

**Comment by rxl881** [comment]
Currently Riot-bot is only able answer questions from the list of FAQs on the riot website - https://about.riot.im/need-help/.

Typing "faqs" (or "faq") to riot-bot will return a list of FAQs that it currently knows about. It is able to fuzzy-match user questions to FAQ titles, so interactions such as the following will work: 

![screen shot 2017-05-30 at 11 44 51](https://cloud.githubusercontent.com/assets/6763606/26579843/8a2f19c2-452d-11e7-8fe2-e8fae9d279eb.png)

Obviously we want to improve riot-bot's comprehension and responses as much as possible, over time, and this will probably include improving it's responses when it is unable to answer a question. However, in this instance I think that the first port of call should be adding more FAQs to the website, in order to boost the bot's repertoire.

@AmandineLP, @BenfLewis0, @lampholder - Is there an existing mechanism for people to request FAQs for addition to the website (e.g. "how can I encrypt a room?", "how can I invite someone by email address?", "how do I join a room?")

**Comment by lampholder** [comment]
@rxl881 There's no mechanism afaik - riot-bot would be a nice way to capture unanswered/unanswerable questions.

Could we get riot-bot to direct all unanswerable questions (.*\?) to a separate chat room for us to mine for future FAQs?

Depending on the volume of queries that can't be handled automatically we could even pass them on to a human operator during working hours to puppet a response...

**Comment by rxl881** [comment]
@lampholder - This is already being done (sort of). I'll come and chat IRL, rather than putting the details in here.

**Comment by turt2live** [comment]
I'm not sure what the status of this issue is anymore, but the primary issue is fixed: riot-bot doesn't ask to be asked a question any more.

Improved FAQ for the win, but that feels like a different issue.
