### ISSUE TITLE
Pictures in encrypted rooms makes firefox unresponsive

### ISSUE THREAD

**Issue by aurabindo** [vector-im/riot-web#4029]
### Description

When I upload pictures to an encrypted room, it makes firefox very slow, but has no noticeable effect when uploading to unencrypted rooms.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 53
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by ilvez** [comment]
I've encountered this problem on other platforms (Debian unstable, Windows) too and various Firefox versions. Since Firefox is currently running in single thread (or at least JS engine seems to), then it affects not only Riot but whole FX usage (in other tabs) and makes it quite impossible to use.

Problem disappears when picture is naturally scrolled away from visible area.

**Comment by ara4n** [comment]
dup #2866 almost certainly
