### ISSUE TITLE
[slack/riot-web integration] turning on encryption stop sending messages from riot to slack

### ISSUE THREAD

**Issue by arthurlutz** [vector-im/riot-web#4066]
### Description

When using slack/riot integration the messages goes both ways. But when you enable e2e encryption in the riot room, messages written in riot (with green lock) are not bridged to slack. Messages written on slack are still bridged to riot (and are unencrypted - which should be configurable ? should I file another issue for that ?)

### Version information

- **Platform**: both web and desktop

**Comment by t3chguy** [comment]
Currently no bridges support e2e. Since slack does not support megolm it would not really be e2e anymore anyway as the bridge would have to decrypt everything and then most definitely rendering the point of e2e moot in most cases. There have been discussions but it would need very explicit confirmation from both sides of the bridge that e2e would no longer hold etc

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/2277

**Comment by lampholder** [comment]
Yes, #2277 is the (only) way to address this. I'm going to declare this not entirely fairly as a dup and close and we should drive/track progress on #2277.
