### ISSUE TITLE
Login "my" has moved into the dropdown -> "my Matrix ID"

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4075]
![2017-05-30-121658_369x99_scrot](https://cloud.githubusercontent.com/assets/6750344/26580887/fb086ef6-4531-11e7-8599-7d98773927bc.png)

**Comment by t3chguy** [comment]
My guess is that this is an i18n thing due to different languages needing different contexts?

**Comment by t3chguy** [comment]
although looking at the German translation this seems to not be the case

**Comment by lukebarnard1** [comment]
I would be surprised though. We're talking about different contexts depending on whether you're referring to essentially different objects : "Matrix ID", "Email", "Phone number".

**Comment by t3chguy** [comment]
in Polish for example it might change my to `mój` or `moje` depending on the selection in the dropdown, though `mój` would be acceptable for `moje` case too

**Comment by t3chguy** [comment]
I guess if the language needs the my to be part of the dropdown then so be it, but at least for English it could be chucked out of the dropdown and be down to the language

**Comment by t3chguy** [comment]
@lampholder I think due to https://github.com/matrix-org/matrix-react-sdk/pull/962#issuecomment-304871482 this will be unsolvable

**Comment by lukebarnard1** [comment]
Fundamentally, by putting "Sentence ... [end of sentence v]", we have assume the order of the UI will be correct for all languages. This is not possible.

An i18n-able alternative could be

`Sign in method: [ method 1 ... v ]` 

or worse

`[ Sign in with email  v ]`, `[ Sign in with my Matrix ID v ]`

**Comment by lampholder** [comment]
It looks like we've solved this for now by dropping the 'my' from the whole sentence, which works for me.

Separately, I really like the sentence-with-object-dropdown paradigm, since (I think) it is so intuitive. I hadn't considered the complexity this brings through other languages' placing their objects elsewhere in the sentence.

Modifying our UX across the board to support `(words words words?)OBJECT(words words words)?` sounds like a pain - I wonder if it would be possible to use the sentence-with-substitutable-object paradigm for languages where that fits, and fall back on a `key: value` (e.g. `Auth mechanism: (email|phone|username)`) for other languages. Do all languages support `key: value` in the same order?

Ugh what about RTL languages?

**Comment by lukebarnard1** [comment]
>Ugh what about RTL languages?

Exactly, there are untold issues with baking assumptions on languages into the UI. However, we do now support injecting JSX into translations:

So `"Sign in with <methodDropdown>"` becomes `"bla bla <methodDropdown> words words"` in another language.

but we'd have to do some mangling to make our dropdown work as an inline thing.

**Comment by turt2live** [comment]
It's been moved out
