### ISSUE TITLE
ILAG: .mx_emptySublistTip seems horizontally misaligned

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4106]
![2017-05-31-093157_230x213_scrot](https://cloud.githubusercontent.com/assets/6750344/26622979/1f4aefe8-45e4-11e7-9e4d-b96d5816c5e9.png)

**Comment by lampholder** [comment]
Are you referring to the left margin being ~4px narrower than the right margin? I don't actually find that aesthetically too unpleasant, but either way I think this _can_ wait until the first iteration is in the wild (though I appreciate it probably takes seconds to fix).

**Comment by ara4n** [comment]
This is a feature rather than a bug.  It just so happens that the word-wrap on each line happens to wrap leaving a ~10px gap on each line, plus or minus a few px.  Different languages will wrap differently, with different spacing.  And if/when we let LeftPanel's width be changeable that will change too.  So I don't see this as a problem.
