### ISSUE TITLE
ILAG: Can't scroll the welcome page on macbook with trackpad

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4154]
There's a div on the welcome page: `<div class=" mx_HomePage gm-prevented">`
He has a css property: `overflow-y: hidden;` (from theme-light.css)

This css property makes my mac unable to scroll with the trackpad in FF and Chrome.

There's another css property `-webkit-overflow-scrolling: touch;` (from bundle.css) which looks like it should be doing something helpful in this area, but is struckthrough as invalid in the dev tools inspector by FF and Chrome.

Scrolling seems to work fine with a mousewheel on my ubuntu machine.

**Comment by lampholder** [comment]
@ara4n - do you know about this thing?

**Comment by ara4n** [comment]
yup ;) gm-prevented means that the fake-CSS-scrollbars (GeminiScrollbar) have been suppressed because the OS has native pretty scrollbars (i.e. MacOS's default behaviour).  As a result, we're seeing that the CSS is broken when Gemini is disabled, probably because I forgot to set `overflow-y: scroll` on mx_HomePage or something.

**Comment by ara4n** [comment]
fixed.
