### ISSUE TITLE
The fact that you can't create IRC bridged rooms from the room directory is confusing for IRC users

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4171]
If you enter #anewroomname into the Room Directory search field, folks might expect it to autocreate the room.  Instead apparently it says 'You are not invited to this room' which is completely confusing

**Comment by infrascripting** [comment]
Not sure if related, but...

Per agaffney in #freenode_#ansible:matrix.org, there was a `CLEAR USERS` sent by an user with compromised credentials, and kicked a lot of matrix users from the room. Now, when I try to `/join #freenode_#ansible:matrix.org` per the [Matrix Blog](https://matrix.org/blog/2015/06/22/the-matrix-org-irc-bridge-now-bridges-all-of-freenode/), I get the same *You are not invited to this room* error.

Due to the extenuating circumstances, this may be a different issue.

**Comment by infrascripting** [comment]
@t3chguy That worked! `@appservice-irc:matrix.org` invited me to the room.

Apologies for derailing the Issue.

**Comment by benjaoming** [comment]
Sorry, that does not work. For the "#ansible" channel in particular, I get invited to a weird empty room from previous similar tests.

The IRC channel mode is `+nrt`.

![image](https://user-images.githubusercontent.com/374612/50060505-4ae83e80-0195-11e9-9e89-793d31f79805.png)

**Comment by aaronraimist** [comment]
Seems to work now
