### ISSUE TITLE
Bad fallback for icons in Tor Browser with security level "high"

### ISSUE THREAD

**Issue by ollieparanoid** [vector-im/riot-web#4179]
### Description
In the tor browser, icons are not shown with the security level "high" (because they are SVGs?). Then it looks like in the screenshot below.

Ideas:
* The alt text for "scroll to bottom" could be changed to "V"
* The "unencrypted..." text could be shortened to "unencrypted" and displayed in one line

![riot_tor_browser](https://cloud.githubusercontent.com/assets/6033024/26757122/0f43d6a8-48a2-11e7-9d9d-be04ad7a3af6.png)

### Steps to reproduce

* Install tor browser
* set the security level to high
* open up a hosted riot instance

### Version information
* **Browser**: Tor Browser 6.5.2 (based on Mozilla Firefox 45.9.0)
* **URL**: https://chat.disroot.org/

**Comment by t3chguy** [comment]
alt text also has a use for screen readers, so V would make very little sense

**Comment by ollieparanoid** [comment]
Then I'd suggest putting it in one line.

**Comment by t3chguy** [comment]
It is normally, the bug is likely due to how outdated your Firefox is
Modern FF is 53
I know its Tor but the underlying FF version is what matters

**Comment by ollieparanoid** [comment]
Ah, so it will be all fixed, when Tor Browser adopts the new Firefox version?
Does this also fix the "unencrypted" text?

**Comment by ara4n** [comment]
I suspect the actual problem here is nothing to do with FF version, but that Tor Browser disables SVG when you dial up the paranoia mode (or perhaps our TintableSVG thing, which uses the object tag to embed SVGs so we can programatically change their CSS).  The right solution is to detect working SVG and Object support in modernizr, and then failback to PNG for people who can't handle SVGs.

This is fairly low priority though.  Removing the Alt txt would break accessibility for other folks.

**Comment by ollieparanoid** [comment]
Thanks for the quick feedback to both of you!
I'd suggest not to remove the alt text, but to make sure it fits in one line and does not get wrapped, if that is possible.

And it looks like Tor Browser will soon be based on the new Firefox ESR, which is 52.

**Comment by lampholder** [comment]
This certainly doesn't seem to be a problem any more - if you dial security up to 'safest' on tor, javascript no longer works (and any impact on icon rendering is moot). It all appears to work correctly on 'safer'.
