### ISSUE TITLE
Add ouput devices setting

### ISSUE THREAD

**Issue by kuon** [vector-im/riot-web#4203]
Current version allow only to set the microphone device. I think it would make sense to add a setting for the output device and optionally the ringing device.

## Version

Homeserver is https://matrix.org
Identity Server is https://vector.im
matrix-react-sdk version: 0.9.1
riot-web version: 0.10.1
olm version: 2.2.1

**Comment by t3chguy** [comment]
Ringing device we won't have control over, that'll just be whatever audio device the browser is outputting to, voip we should be able to direct to a specific output

**Comment by kuon** [comment]
The voice output device is already a big step.

**Comment by benrob0329** [comment]
We really need this, VoIP is unusable for some people without it.

**Comment by krodelabestiole** [comment]
Apparently it has been implemented by the W3C for WebRTC :
https://w3c.github.io/mediacapture-output/
https://bugs.chromium.org/p/webrtc/issues/detail?id=2243

I don't know how well implemented this functionality is on browsers and electron though...

**Comment by t3chguy** [comment]
It's definitely possible just missing someone to work on implementing it in react-sdk and js-sdk

**Comment by krodelabestiole** [comment]
From my understanding we now have one audio output we can choose. Thanks !

Would it be possible to have two : one for the ringing and one for the communication.
(for people who use headphones e.g.)

@t3chguy could you please reopen (since _devices_ is plural in _Add ouput devices_) or should I open a new issue ?

**Comment by t3chguy** [comment]
I don't know how feasibly that can be done given that it's just a Web browser under the hood which doesn't have such controls

**Comment by krodelabestiole** [comment]
it depends on electron I guess (or any browser for the web app)

but if you can't route 2 different signals on two different outputs at the same time, due to the technology riot is based on, first we could push a feature request to these techno, and then there is still the workaround to switch on two different outputs depending on if a conversation is currently occurring or no... I guess... no ?
