### ISSUE TITLE
ILAG flow glitches (peeking whilst registering)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4206]
- [x] Go to https://lant.uk/riot/new-guest-access/; Peek in #riot; click 'create room'; choose a mxid; cancel create room request - infinispin (goes away after refresh)
- [x] Go to https://lant.uk/riot/new-guest-access/; Peek in #riot; click 'create room'; choose a mxid; create a room - room created, no riotbot, infinite spinner at bottom of room (riot bot is there after a refresh)
- [x] ~Go to https://lant.uk/riot/new-guest-access/; Click 'login'; click 'back' - you can't go back (probably the same as the issue matthew filed, I just hadn't noticed the big obvious 'login' button is a think users might click and then want a way back from before)~ (see https://github.com/vector-im/riot-web/issues/4061)

**Comment by lukebarnard1** [comment]
1. Is the same-old peeking whilst registering bug. The infinispin happens because the room is being peeked whilst a new user is registered.
1. Practically the same bug except the _new_ room is peeked when it really really shouldn't be - you created the room are joined automatically server-side.
1. Is https://github.com/vector-im/riot-web/issues/4061

**Comment by lukebarnard1** [comment]
I think this is all symptomatic of Riot treating a room that is currently being peeked as a fully-fledged room. Perhaps we need to determine whether a room is being peeked by inspecting it instead of relying on the app state to tell us how we can use it.

**Comment by lukebarnard1** [comment]
In fact, it seems the peeking logic was getting a new room every time it polled for new events. The fix is simply to use the `peekRoom` created by the peeking itself for the duration.
