### ISSUE TITLE
Leaving settings when not joined to any rooms should display the home page

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#4244]
welcome page > user settings . click X > directory
should be back to welcome page

**Comment by lukebarnard1** [comment]
This behaviour has changed such that, when the user settings are closed the user is shown the room they were last in, even if they have forgotten it at that point.

That suggests that the current room being looked at is not reset when `view_next_room` is dispatched but `view_home_page` is dispatched instead of showing an historical/forgotten room .

**Comment by turt2live** [comment]
Riot appears to be landing on the homepage now.
