### ISSUE TITLE
Starting to type should automatically focus the input box

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-web#435]
Request in title - this allows the user to just begin typing rather than having to click in the input box beforehand.

**Comment by ara4n** [comment]
I'd kinda prefer that we autofocused the input box reliably in general, rather than stealing all text inputs into an autofocus...  Jon: is there a reason that reliable autofocusing wouldn't be sufficient?

**Comment by jfrederickson** [comment]
That would work, though at that point you also couldn't scroll through history with the arrow keys/pgup/pgdn. If that would be a much cleaner solution technically, it may be worth the tradeoff. (Not sure how many other people do so and/or whether there are any accessibility concerns related to this.)

**Comment by pvagner** [comment]
I think this is very difficult question however my issue is an opposite. Currently when pressing tab key I will end up focusing an input box. This effectively disables focusing links in the output area for example in order to be able to navigate to links and other controls associated with messages. As a keyboard only user this is already complicated for me.

**Comment by t3chguy** [comment]
bumping to p2 as thats what #3841 was triaged as

**Comment by aaronraimist** [comment]
This appears to work now
