### ISSUE TITLE
Image scraped for Riot URL preview is an SVG

### ISSUE THREAD

**Issue by almereyda** [vector-im/riot-web#4350]
Showing to our users the switch from Vector to Riot (yes, late), we see that Riot does not like to embed itself:

![bildschirmfoto vom 2017-06-19 04-16-38](https://user-images.githubusercontent.com/1645308/27267113-6fda1c7e-54a6-11e7-9830-7b91915aa03d.png)

This most likely is due to missing proper metadata descriptions which could be fetched by `synapse`'s URL preview service instead.

**Comment by lukebarnard1** [comment]
Somehow this might be _actually_ be because we're getting 500 when getting the generated thumbnail. When you change `https://ldbco.de:8448/_matrix/media/v1/thumbnail/ldbco.de/YLwKLJcCutWIRNnAWDlxOzGN?width=100&height=100` to `https://ldbco.de:8448/_matrix/media/v1/download/ldbco.de/YLwKLJcCutWIRNnAWDlxOzGN`, you don't get a 500, but the actual image.

So this is a bug in synapse's thumbnail API.

**Comment by turt2live** [comment]
I believe this got fixed at some point
