### ISSUE TITLE
Still seeing devices which have been deleted

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#4527]
Example: zottel should only have a couple of devices visible but everyone on other homeservers sees 8 or 9 devices. (Seems to be a server-side issue rather than a client-side one)

**Comment by zzottel** [comment]
Clarification: Should be four devices, some in #megolm do see four, most see five or eight devices. IIRC, eight should be the total number of devices I ever had.

**Comment by richvdh** [comment]
Suspect this only affects people on remote homeservers

**Comment by jcgruenhage** [comment]
Get's worse for me all the time.. I currently have 3 devices, zottel sees 11. Isn't this also making crypto a lot slower?

**Comment by kaiyou** [comment]
Not only is this making crypto slower, when one of my contacts loses a device or decides to relogin (password change or anything), my messages in E2E encrypted chats still get encrypted for old, unused and uncared for devices.

At some point, unless everyone notifies all their contacts whenever they remove a device, so that everyone may blacklist it, this will become quite a serious security issue.

**Comment by ara4n** [comment]
fixed by matrix-org/synapse#3520
