### ISSUE TITLE
CDN riot.im to save bandwidth

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4561]

**Comment by jimaek** [comment]
You can use jsDelivr if you want https://cdn.jsdelivr.net/npm/riot-web/

**Comment by lampholder** [comment]
Hey @ara4n - do you want to prioritise this? Seems like an easy win (assuming some CDN can give us effective cache-clearing facilities; I've never used one but I imagine that's fairly standard), but I don't know how pressing a need there is for this right now.

**Comment by lampholder** [comment]
Arbitrarily assigning P2 for now - @ara4n please change if you don't think that appropriate.

**Comment by ara4n** [comment]
we're now using cloudflare for electron downloads, which helps a lot.

**Comment by ishitatsuyuki** [comment]
[Test results on Netlify](https://testmysite.io/5abdf9a692226a08dfbbc270/riot.im)

So TTFB is not good mainly because the HTML page doesn't get cached, and the requests are all hitting the origin. I believe setting up Netlify is trivial (I've had good experience with it), and it solves the problem because Netlify transfers the assets to their CDN globally, serving the page directly from edges. Do you want to try setting up with Netlify? I'm happy to help.

**Comment by aaronraimist** [comment]
It's behind Cloudflare now right?

**Comment by jryans** [comment]
Yes, Riot app components are using Cloudflare now.
