### ISSUE TITLE
BigEmoji should allow whitespace between emoji

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4571]
Otherwise we get messages like this:

![2017-07-13-144557_297x98_scrot](https://user-images.githubusercontent.com/6750344/28169379-0ca4a5ce-67da-11e7-98a9-a8c13dba43fe.png)

Ideally, both messages would have been given the css to be big

**Comment by uhoreg** [comment]
Make sure to also allow zwj in between emoji, so that things like http://emojipedia.org/female-singer/ display big.  This is how it currently looks in Riot web:
![image](https://user-images.githubusercontent.com/1012976/28898698-5e0284e6-77b5-11e7-8c0a-13a3cb595058.png)
(https://matrix.to/#/!UCnwUWwIKhcpaPTHtR:sw1v.org/$1501710544364350QtgZW:matrix.org)
