### ISSUE TITLE
Unable to decrypt: Encryption not enabled

### ISSUE THREAD

**Issue by commagray** [vector-im/riot-web#4606]
Rewrite of #4585.

### Description

E2E just don't work.

### Steps to reproduce

- Launch Firefox
- Open https://riot.im/app
- Enter or create some secret chat
- Instead of messages you see `** Unable to decrypt: Encryption not enabled **` and can send it only in unencrypted form
![2017-07-17-191406_492x389_scrot](https://user-images.githubusercontent.com/27947961/28278040-68f4b0ec-6b24-11e7-9302-59c6912e1f62.png)

### Version information

- **Platform**: web
- **Browser**: Firefox ESR (52.2.1)
- **OS**: OpenBSD (-current branch)
- **URL**: riot.im/app

**Comment by richvdh** [comment]
This is surprising. Could you send a bug report with logs from the settings screen?

**Comment by richvdh** [comment]
Oh, one thing that could cause this: US export regulations mean that we can't permit use of the crypto libraries in certain countries. The hosted riot.im blocks access to the crypto library to IP addresses which geolocate to Cuba, Iran, North Korea, Sudan and Syria.

**Comment by commagray** [comment]
> Could you send a bug report with logs from the settings screen?

Yep, already.
> we can't permit use of the crypto libraries in certain countries

Hehe, no. I live in right place, there encryption works. It's only problem with Firefox on OpenBSD, and why — I don't know. If it matters, in Chromium/Iridium all works fine, but they ugly as browser.

**Comment by richvdh** [comment]
Thanks for sending the logs. Sadly they don't show anything helpful, which probably means that whatever is going wrong is happening very early in startup, before the logging system starts. Can you see if there is anything useful in the javascript console in the browser developer tools?

We've previously had problems with Firefox on OpenBSD due to (apparently) memory constraints, but I thought we'd pretty much resolved that: https://github.com/vector-im/riot-web/issues/2726.

**Comment by thekyriarchy** [comment]
I'm experiencing this error as well. Additionally, a warning that says "Could not connect to the integration server"

**Comment by richvdh** [comment]
Not enough info here. @commagray if you have any more info please let us know.
