### ISSUE TITLE
allow width/height attributes in img tags

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4646]
On /develop:

This message: https://matrix.to/#/!vfFxDRtZSSdspfTSEr:matrix.org/$1499793683997Ldmzb:t2l.io (in #test) has `formatted_body`:
```html
<font color='#f7f7f7'>▌</font> <img src='mxc://t2bot.io/hcSELkhLCNMRxLLTXKffPPSn' width='16' height='16'> <a href='https://matrix.to/#/user/@voyager:t2bot.io'>Matrix Traveler</a><br><font color='#f7f7f7'>▌</font> This is the message body
```

(note the width and height attributes in the `img` tag), but displays like this:

![image](https://user-images.githubusercontent.com/1012976/28385076-c83842f0-6c94-11e7-8dec-9f8ad21dbf5a.png)

with a very large image because the `img` tag no longer has height and width attributes.  alt and title tags should probably also be allowed if they aren't already.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chromium
- **OS**: Debian
- **URL**: riot.im/develop (f7d282fc8e57-react-2f293adad53f-js-e686eb750ff4)

**Comment by turt2live** [comment]
The width and height get converted to url params as part of the transform to the timeline, however they seem unhelpful:
```
<img src="https://t2l.io/_matrix/media/v1/thumbnail/t2bot.io/hcSELkhLCNMRxLLTXKffPPSn?width=16&amp;height=16">
```

Likely because it's `&amp;` instead of `&`.

**Comment by lampholder** [comment]
Navigating to the above t2l.io link, with either &amp; or &, the media repo seems to ignore the width/height parameters. Is that our real bug here?

**Comment by t3chguy** [comment]
try adding `&method=crop` to the end of the URL

**Comment by lampholder** [comment]
Just did :) Now it scales :D

**Comment by lampholder** [comment]
So:
1. the link in the timeline is missing the `method` parameter
1. the media server seems to ignore the `method=scale`
1. the media server seems to scale the image if you specify `method=crop`

At the very least, 1 seems to be a bug and 2 and 3 seem like they could be bugs (at the very least I find the behaviour unintuitive and surprising)

Spec: http://matrix.org/docs/spec/client_server/r0.2.0.html#thumbnails - doesn't say what happens if `method` is omitted.

**Comment by t3chguy** [comment]
`method=scale` iirc is default, which is why its "ignored"

**Comment by uhoreg** [comment]
I think that the fact that Synapse doesn't actually scale the image is a separate issue; Riot should retain the height and width attributes anyways.

**Comment by lampholder** [comment]
I've heard from @lukebarnard1 that the media server is... more weird than I thought, and actually can end up serving thumbnails from previous requests (for the same image, but thumbnailed according to different parameters).

As @uhoreg says, this bug is really two bugs:
riot-web:
1. In translating the HTML message to the timeline it translates the height/width parameters into values passed to the thumbnailing request to the media server (and drops them from the client-side HTML formatting of the resulting `<img>`)

media repo:
1. Does some weird stuff, resulting in what appears to be images of the wrong size being returned for thumbnailing requests.

Since https://github.com/matrix-org/matrix-react-sdk/pull/1244 references this, let's declare this bug the canonical 'width and height get lost in translation riot-side' bug (also in line with its existing name) and I'll create a different bug for the media server shenanigans.
