### ISSUE TITLE
Search does not work at all

### ISSUE THREAD

**Issue by tliron** [vector-im/riot-web#4649]
### Description

The room is encrypted.

Search is returning no results, even when very clearly there are words used in the chat. Actually, the only result returned is for system messages such as "X changed the topic to ...".

Screenshots attached.

### Steps to reproduce

Start a direct chat. Set it to be to encrypted. Chat a bit. Try to search any of the words in the chat. No results.

### Version information

For the desktop app:

- **OS**: Tested on Windows and Ubuntu 16.04
- **Version**: 0.11.4

![screenshot from 2017-07-19 22-46-01](https://user-images.githubusercontent.com/1146849/28399657-1a1a87a6-6cd4-11e7-8b91-1ffc147ae4c4.png)
![screenshot from 2017-07-19 22-46-07](https://user-images.githubusercontent.com/1146849/28399658-1a1a99bc-6cd4-11e7-95c7-f5b17d1067b7.png)

**Comment by t3chguy** [comment]
The search is done by the server which cannot decrypt e2e content for obvious reasons

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/issues/2548

**Comment by tliron** [comment]
At the very least there should be some kind of error or information message for users. As it stands it looks very broken.

**Comment by gibbousmoon100** [comment]
"No results" indeed looks very, very broken, not least because there is no indication that the search can only be performed on the server.

"Search not available for encrypted conversations" seems like a reasonable compromise for as long as client-side search is not available.  "Searches are performed on the server; therefore, encrypted material is not included in these results" would be even better.

**Comment by t3chguy** [comment]
@tliron, @gibbousmoon100 see https://github.com/vector-im/riot-web/issues/2548#issuecomment-314752378 (comment on #2548, the issue that this issue duplicates.)
