### ISSUE TITLE
if riot is slow, pasting into the RTE can race with typing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4708]
I think this is the root of most of my RTE problems - if riot is being laggy, then pressing cmd-V to paste a URL may race with the stuff I am trying to type after it, causing the typing to appear *before* the thing I paste, despite me having pasted first.

**Comment by lukebarnard1** [comment]
I've seen a bug similar to this one where the selection state gets needlessly set to the beginning of the composer and I'm not convinced it's a race. (See https://github.com/vector-im/riot-web/issues/4675)

**Comment by lukebarnard1** [comment]
Upon investigation, this looks like a race in draft-js between the paste handling and the character insertion. This is likely because sometimes draft does native character insertions, which are done on (potentially) a different event-loop to the pasting. 

So when perf drops, the native character insertions get done first, followed by the paste(s if you've done multiple <kbd>ctrl</kbd>+<kbd>v</kbd>s).

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk#1890, thank goodness
