### ISSUE TITLE
Stable first cut of RTE

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4734]
We've done a lot of work on the RTE of late, and we want to get this in front of people in a way that:
- realises the value of this work
- doesn't introduce unreliable or unpredictable behaviour

### Proposal

The most significant source of bad behaviour is converting back and forth between markdown and rich text content. There does not exist a reliable way to do this conversion. so the proposal is that we **do not do this conversion**.

**The proposal is to maintain two separate versions of the composer, 'Rich Text' and 'Markdown'.**

Both versions of the editor will have their own independent histories, and both will support quoting exactly as it is on /develop today, warts and all (a better quoting system comes from referencing quoted events directly, not from digesting historical messages into representative markdown).

- the _markdown_ composer will:
    - support sending either markdown formatted text or plain text
    - accept rich text pastes, but digest them into a plaintext representation (crucially it will not translate formatted text to a markdown representation)
- the _rich text_ composer will:
    - support sending rich text only
    - accept rich text pastes maintaining formatting

To reduce surprise when switching between editors, this setting will be on the _user settings_ panel (we can leave a keyboard shortcut for power users). 

When toggling, we should consider advising the user that:
- any message they are currently composing will be lost
- their Rich Text composer history won't be accessible from the Markdown editor, and vice versa

**Comment by ara4n** [comment]
i think this may be a step backwards - i for one spend a lot of time toggling markdown on & off depending on what i'm writing. I think a simpler check would be to warn the user that they will lose their message when toggling it (if they are mid-writing a message).

I honestly don't think we need to agonise about the round-tripping at all; if weird things happen when you toggle, I don't think folks will be that surprised.

I'm much much more worried about the other flakinesses we've seen which impact normal typing (e.g. races between clipboard & typing, or bad interactions between pills & editing within the composer) rather than the edge case of toggling.....

**Comment by turt2live** [comment]
I'm not sure I'd be a fan of having two different editors where the only noticed difference is how my selection gets pasted into Riot. To be honest, I didn't realize this was a feature until reading this proposal - I've always just toggled markdown on/off for whether or not I wanted my message to be parsed as markdown.

It appears as though disabling markdown also disables the rich text option - which seems like an unexpected side effect rather than a feature (despite it being a feature). Would a "Paste with formatting" (and maybe a partner "Paste without formatting") button achieve the same end goal? This would allow the markdown button to do *just* markdown, and the rich text on/off be handled by something else. I'd imagine a user setting to "default paste with[out] formatting" would come as a result of this as well.

**Comment by lampholder** [comment]
I confess that I am struggling to reason sensibly about the composer, I think because there are so many orthogonal dimensions to the thing. 

Fundamentally, we want something stable that we can release soon and continue to build upon.

Can we get here more quickly by making some broad descoping statements:
- all pastes are plain text only
- pills are not rehydrated out of markdown message history - it's just the plain text of the display name

**Comment by lampholder** [comment]
> It appears as though disabling markdown also disables the rich text option

Does it? I thought disabling markdown was the only way to _enable_ rich text option? (On /develop)

**Comment by turt2live** [comment]
You're right, disabling markdown enables rich text, which is still counter-intuitive imo.

**Comment by ara4n** [comment]
no need as of matrix-org/matrix-react-sdk#1890, hopefully :)
