### ISSUE TITLE
writing @free<tab> to try to autocomplete a freenode user instead completes me a random recent MXID

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4746]
in this instance @free<tab> gave me a pill for 'felix' in HQ, who has nothing to do with freenode

**Comment by lampholder** [comment]
It looks like @free... doesn't match freenode users for autocompleting pills.

I didn't get the random recent MXID (perhaps because there are currently two members of HQ with mxids starting with @free), but nor did I get any of the freenode users you see if you start filtering users with @free in the room members filter.

**Comment by lampholder** [comment]
P2'ed just because I think we could release without the autocomplete feature working for bridged users -
- though I can see arguments for this being higher priority, I _really_ want to get a version of the new composer out.
