### ISSUE TITLE
ctrl-K impl uncollapses tags, which is mildly annoying

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4798]
says seequ_

**Comment by lampholder** [comment]
I can't reproduce this (ff/chrome ubuntu).

I am, however, familiar with the related UX problem that using the room names filter _doesn't_ uncollapse (or even otherwise highlight) tags containing matches. I'd observer that this behaviour does actually fit with the 'filter' paradigm though trips up my using it as a 'search'.

Are we sure seequ_ was complaining that the tags are uncollapsed, rather than the opposite?

**Comment by lampholder** [comment]
I could never reproduce this.
