### ISSUE TITLE
Can't submit a bug report without registering

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4802]
### Description

You're prompted several times and eventually give up. If there's a problem with the registration process, or with something in the context of an unregistered user, it's really hard to submit a bug report.

*Note: This was submitted to me through another user on a not-matrix.org homeserver. Their issue was human error, but they were frustrated that they couldn't rageshake their problem on web*

### Steps to reproduce

- Don't be logged in
- Try to submit a bug report

Expectation: Being able to send a bug report without having to go through the registration process.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 59
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment]
Because:
- filing a bug lives in the user settings panel
- we made a decision during ILAG that opening the user settings panel would launch the 'pick a username' dialogue

It strikes me that:
- only users familiar with Riot will be looking for the ability to file a bug behind user settings (so only they will be frustrated by its being inaccessible without registration)
- _anyone_ who is hit by a bug during registration (or login for that matter) will not be able to make us aware of that fact without herculean effort on their part (so we'll be missing vital data)

I'm going to make this a P2 because it seems like a risky gap but we don't have any suggestion of catastrophic registration bugs today.

Also, it's an interesting design challenge - how would we implement the UX to ingest maximum useful bug reporting?

**Comment by turt2live** [comment]
In general, most people would be aware of Riot enough to get a registration bug to the Riot team. In this case, it just so happened to be that they didn't know what Riot was but wanted to get help and ended up reaching out to me as I'm the point of contact for stuff like this in our organization.

**Comment by turt2live** [comment]
I'm going to consider this fixed by https://github.com/vector-im/riot-web/pull/7755
