### ISSUE TITLE
can't start a chat with yourself

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#4833]
from start chat screen, server responds that you're already in the room

**Comment by t3chguy** [comment]
Synapse replies `{errcode:M_FORBIDDEN,error:@x:riot.ovh is already in the room.}`

**Comment by lukebarnard1** [comment]
Surely just create an empty room? Or we could short-circuit specifically a 1-1 with yourself to just hit the createRoom API??

**Comment by Nostradamos** [comment]
Telegram has the feature to chat with "yourself", i like the idea because it can be used as a clipboard across multiple devices, quickly sending a picture/url/whatever from your smartphone to your desktop is a nice thing to have. All of this works if you're in an empty room but it would be nice to have it act a bit different:
1. be able to start a chat with yourself without the need of creating an empty room first
2. Show a chat with yourself under "Persons"  and not list it as a room.
3. directly set the name to something meaningful like "Yourself" or your own nickname

**Comment by lukebarnard1** [comment]
This could be quite a nice feature. In terms of implementing, do we want to 
 1. change the semantics of being in a room alone? OR 
 2. provide the ability to create a new room and explicitly setting the room name to "Yourself" in the chosen language and putting it under "People"?

The negative of 2. is that someone might chose a language, create a room with "Yourself" and then change to another language.

Changing the semantics of being in a room alone means changing "Empty Room" to "Yourself" (and this is generated when the room has no name, so there is no i18n problem.) However, it would be quite strange to move "Empty Room"s into "People", and I think it could be quite confusing to see a room with you and one other person in it become a direct message. Seeing the name changed to "Yourself" would probably be fine though.

**Comment by dbkr** [comment]
Suggest keeping this bug to be just that pressing 'start chat' and selecting yourself should give a room with just you in it and not an error message. If we want to rename the room or put it in a different section, this might want to go in a separate issue or it'll get lost when we fix the error and close this bug.

**Comment by lukebarnard1** [comment]
@dbkr sgtm

**Comment by aaronraimist** [comment]
This works now. For a better way to do this or more features, probably best to add in #4933 or a new issue.
