### ISSUE TITLE
Widgets UI/UX - I expected clicking the widgets button to let me add more widgets, but it closed the drawer.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4839]
Very closely related to #4834 - having added a widget and wanting to add a second, it was my natural inclination to click what I was already thinking of as the 'widgets button' (actually the show/hide widgets drawer button) - obviously clicking this just made the drawer disappear.

**Comment by lukebarnard1** [comment]
Your expectation is presumably generated by the "shortcut" of pre-opening the integration manager so that you can skip the extra click to add a widget. 

We do this in other parts of mdlr, including skipping to "Add an integration" when there are no integrations in the room. This [causes a jarring experience that we should avoid](https://github.com/vector-im/riot-web/issues/4845).

**Comment by almereyda** [comment]
For me it feels different: in my opinion the widget dialogue should only show when no widgets are present, as the button nicely toggles their view.

**Comment by rxl881** [comment]
As mentioned in #4834, the mechanism for adding / removing widgets has changed, so I'm assuming that this is no longer an issue.
