### ISSUE TITLE
The app drawer should remember whether it was closed per-room

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#4850]

**Comment by turt2live** [comment]
This is incredibly distracting and annoying currently.

**Comment by anoadragon453** [comment]
So we currently store a keyvalue pair in LocalStorage with key `!roomID:domain.tld_url_to_integration_content` and value `"true"`. Since we would need a per-room setting to keep track of whether the integration tray should be open or closed, we could do one of the following:

1. Add new pairs for each room with something like key `!roomID:domain.tld.show_integration_drawer` and value `"false"`. This is set to `"false"` when the user closes the drawer, and `"true"` when opened.

2. Generalize things (which would require some refactoring) so that we have one LocalStorage keyvalue pair per room, with the value being a JSON containing information about both whether the integration drawer should be opened or closed, as well as whether each integration URL is allowed or not. The resulting rule would then look something like key `!roomID:domain.tld` and value `"{"show_integration_drawer":"false", "url_to_integration_content1": "true", "url_to_integration_content2": "true"}"`

I believe the second method is better, even if it does require more work, as it creates a per-room JSON for settings that we can extend and add to in the future.

Thoughts?

**Comment by anoadragon453** [comment]
Storing the value for each room in AccountData may be a better solution, as that would allow widget preferences to be carried across clients.

2. should still be taken into account if we plan to store further room data in localStorage without making it cluttered.

**Comment by lukebarnard1** [comment]
@anoadragon453 I'm not convinced we should worry about `localStorage` being cluttered although it'd be nice to have some sort of organisation to it. I'd rather tackle that separately to fixing this bug. 

Generalising things does sound like a good idea but looking at the current implementation (widget permission IDs being stored in `localStorage`) I'd also prefer to de-scope the refactoring needed there (it's not clear at all why those items are in `localStorage` just by looking at the keys). 

There are plans to do generic per-room synced settings (via client-side abstraction), and it'd be good to get the right from the get-go otherwise we'll have hell trying to migrate `localStorage` things to account data.

**Comment by anoadragon453** [comment]
> There are plans to do generic per-room synced settings (via client-side abstraction), and it'd be good to get the right from the get-go otherwise we'll have hell trying to migrate localStorage things to account data.

Ah, that's good to know. Can you link or do you know what these plans consist of? Is it just a simple set of `"roomID:dom.tld":"JSON"` rows in account data or something more complex?

**Comment by anoadragon453** [comment]
@lukebarnard1 I plan to submit a PR for this feature using localstorage to store the state and leave the refactoring of localstorage to another commit.
