### ISSUE TITLE
Cut/paste of pill mention

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4902]
Typing a message to someone, then ctrl+a, cut, paste of the message should also keep the pill

**Comment by lukebarnard1** [comment]
We only paste text in markdown mode. We could at the copied HTML and convert it to MD but this would require implementing our own HTML to MD converter (the commonmark library obviously only supports MD to HTML). Of course, we could fix the RTE in general by not supporting RT :innocent: (see #4679 for crazy diagram).

**Comment by lampholder** [comment]
I've made this a P3 because sadly it is (I believe) a lot of effort for a _relatively_ small gain.

Not being able to cut and then paste a pill-containing message in the composer is surprising, and therefore bad. If we can fix this we should, but we shouldn't at this stage invest weeks of effort to resolve this issue :(

**Comment by turt2live** [comment]
Fixed by some magic in the last year.
