### ISSUE TITLE
The device delete dialog is ugly

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4929]
only visually bug still; note to self - ***INVESTIGATE***

**Comment by t3chguy** [comment]
or maybe it was always ugly
![image](https://user-images.githubusercontent.com/2403652/29784956-c8ec70ce-8c1d-11e7-8f37-819b5d9f661b.png)

**Comment by lukebarnard1** [comment]
I think it's always been ugly. It still needs to use the bulk deletion API :grimacing:

**Comment by uhoreg** [comment]
The dialog should say what action will be taken after the user enters their password, to avoid the case of: user walks away, cat walks on keyboard and tells riot to delete a device, user comes back, sees the dialog not knowing that it was because of a device deletion request, enters their password, and is confused as to why their phone can no longer decrypt new messages.

So something like: title: "Delete device", body: "To delete the device ABCDEFG (Riot on Android), please enter your password."

**Comment by aaronraimist** [comment]
![Screen Shot 2019-03-27 at 8 40 11 AM](https://user-images.githubusercontent.com/5855073/55080294-f09c2b00-506b-11e9-8d8f-7a549402d468.png)

For the record this is what it looks like on 1.0.5. I think it is OK now, maybe the text field is a little weird looking still.

**Comment by turt2live** [comment]
I'd count that as ugly still tbh. This is somewhere in the design backlog though

**Comment by uhoreg** [comment]
Still ugly, and still doesn't say what will happen when you hit "Submit".

**Comment by jryans** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/3071 has fixed the password box here. I am unsure if there's more feedback to still remaining in this issue... Please reopen if there is.
