### ISSUE TITLE
'Files' view in e2e-encrypted rooms does not show files

### ISSUE THREAD

**Issue by dorni1234** [vector-im/riot-web#4959]
### Description

Uploaded files are not shown in the 'Files' view when the room has e2e enabled.

### Steps to reproduce

- Enable e2e for a room, upload files, open 'Files' view.

Expected: list of uploaded files
Got: list of events when somebody changed the room image or added a widget, so only the not-encrypted events.

Log: not sent

### Version information

- **Platform**: Desktop, riot-web version 0.12.2 
- **OS**: Arch Linux, Kernel 4.12.8-1-vfio

**Comment by t3chguy** [comment]
the filtering is done server side and since the events are encrypted synapse has no waying of knowing which events are files.

**Comment by dorni1234** [comment]
Thank you for the information. Makes sense if you think about it...

**Comment by t3chguy** [comment]
Doesn't mean its right though, should be locally filtered for e2e

**Comment by uhoreg** [comment]
dup of #2591/#3412

**Comment by t3chguy** [comment]
Leaving this issue open as a meta until either is closed
(as a personal reminder)

**Comment by lampholder** [comment]
So #2591 is "Explain why the file list isn't working in E2E rooms" and #3412 is "Make the file list work in E2E rooms".

Neither of those captures the 'weird other events end up in the file panel' aspect :P

#2591 seems like it should be easy - is the only thing blocking this our not having a design/wording?

**Comment by t3chguy** [comment]
@lampholder as far as I am aware, so if you whip up some wording/design I can impl that

**Comment by lampholder** [comment]
I was thinking something like:

![image](https://user-images.githubusercontent.com/1922197/30285874-834737e8-9717-11e7-92f3-e8d32f11dc82.png)

For rooms which have encryption enabled:
- show all the files we can show (uploaded pre-encryption), or the 'there are no visible files' message
- show the 'files uploaded since encryption was enabled will not be displayed in this panel' message as the last item in the files panel

It's not 100% perfect, since it doesn't do anything to explain _why_ they won't be shown, but the full explanation doesn't really belong in the web UI. It might be nice to provide a [why not?](url) explanatory link, but I don't know if we have a precedent for that and how people hosting their own riots might feel about links to content hosted on https://about.riot.im

**Comment by t3chguy** [comment]
this is fiddly to implement due to how generic `<TimelinePanel />` is

**Comment by lampholder** [comment]
I was afraid that might be the case. Can you suggest something that does fit within TimelinePanel that captures the same spirit?

**Comment by Thatoo** [comment]
Why is it working in Android version of Riot and not in Desktop version of Riot?
If Android can do it, why Gnu/linux can't?

**Comment by RRREEEEEEEE** [comment]
@Thatoo 
> Why is it working in Android version of Riot and not in Desktop version of Riot?

Been wondering this past 6 months as well, decided to google it now with the big release of the riot version.. Thought it was my settings for a second.

**Comment by giomfo** [comment]
@Thatoo @RRREEEEEEEE 
Riot-Android and Riot-iOS list the attachments in the Files panel because they are filtering the room events locally:
- Riot-Android displays all the attachment types: file, image, video and audio (see [VectorSearchRoomFilesListFragment](https://github.com/vector-im/riot-android/blob/ff322d8838d4482abf422366add211160eef52ae/vector/src/main/java/im/vector/fragments/VectorSearchRoomFilesListFragment.java#L330)).
- Riot-iOS displays only the attachments with a media url (see [MXKRoomDataSource](https://github.com/matrix-org/matrix-ios-kit/blob/e05adec3faa3e44f3e278e44739b5745fec35bbb/MatrixKit/Models/Room/MXKRoomDataSource.m#L2129))

**Comment by Thatoo** [comment]
I assume completely if my question is naive : why Riot for desktop can't do the same?

**Comment by turt2live** [comment]
It can, but it involves a bit more work. The concern at the moment isn't really a technical one, but more of a design one.

**Comment by awesome-michael** [comment]
Any news on this? This is really annoying :/
Is there already work done? Maybe I could fix this and raise a PR. Could you give some more detail on how and where the local filtering should be done?

**Comment by t3chguy** [comment]
This could be probably linked to @poljar's local E2EE search stuff: https://github.com/vector-im/riot-web/pull/11125

**Comment by jryans** [comment]
This is not actually fixed yet, we still need the Riot integration from https://github.com/matrix-org/matrix-react-sdk/pull/3858.
