### ISSUE TITLE
Inconsistent behaviour with leading space in composer

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4965]
MD on consumes the space, MD off leaves the leading space

**Comment by lampholder** [comment]
This doesn't strike me as a problem, but that could be because my mental model of what's happening in the composer is different from other people's.

When MD is on what I type is going to be passed through a MD interpreter - leading spaces have meaning in markdown (at least, I think < 4 means nothing >= 4 means code block), so I understand that they're going to be faithfully interpreted.

When MD is off it's a WYSIWYG composer, so all my spaces are going to be rendered in the timeline wherever I happen to type them.

Thoughts?

**Comment by t3chguy** [comment]
I completely forgot that leading space in a line has meaning in MD, closing this as its kinda intentional
