### ISSUE TITLE
Symbol emoji aren't made big

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5050]
Apparently emojione's regex doesn't count symbols in the 'miscellaneous symbols' or 'dingbats' ranges, eg.  ✉︎ and ☺︎ even though it has graphics for them.

**Comment by dbkr** [comment]
I think this is related to https://github.com/vector-im/riot-web/issues/5049 as it's the emojione regex matching the symbol character when the actual emoji is the symbol character plus a variant

**Comment by pafcu** [comment]
This does not actually seem to be a bug but a feature. The non-working emoji uses variant 15 which explicitly means that it is to be treated as text, not an emoji. Using variant 16 (explicitly emoji) works as expected. In fact, the bug seems to be that the text-version is emojified at all (replaced by an image).

**Comment by turt2live** [comment]
We'll need to consider this as part of https://github.com/vector-im/riot-web/issues/9281

**Comment by bwindels** [comment]
Seems to work on #9281, the above mentioned characters render as:
![image](https://user-images.githubusercontent.com/274386/58083055-c9636500-7ba7-11e9-8c9f-141813d5ca17.png)

**Comment by ara4n** [comment]
\o/
