### ISSUE TITLE
encrypted files leak filenames

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#5198]
downloading an encrypted file from the content repository reveals the original filename, which is unexpected.  As pointed out by @ testingtime:matrix.org in https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$150773331351916ExaqC:matrix.org

**Comment by lampholder** [comment]
Ah - the detail I initially missed here is that you still get to see the filename even when you're downloading an encrypted file _for which you don't have the encryption key_.

That is pretty grim.

**Comment by lukebarnard1** [comment]
I seriously doubt this is true, given that the filename is not visible in the encrypted m.room.message.

**Comment by ara4n** [comment]
the mxc:// URL is visible to the HS admin, which defeats the whole point of E2E if we leak the filename. So I agree with @lampholder that it's pretty grim (i'd missed this).

The fix is also trivial; to stop clients submitting a filename when they upload files in E2E rooms, and instead apply the name from within the message when they decrypt the file.

**Comment by t3chguy** [comment]
This has already been done at some point, riot-web sends a filename of `undefined` and doesn't pass it on /download instead passes it into the `download` attr of the cross-origin iframed `<a/>`

![image](https://user-images.githubusercontent.com/2403652/41461665-3c25bc04-7088-11e8-88fd-845cae5cfc69.png)

is an upload from release riot in an e2ee room
also checked logs to confirm its not sending it when downloading accidentally.

---

BUT
riot-android LEAKS E2EE filenames.
![image](https://user-images.githubusercontent.com/2403652/41462059-7e568422-7089-11e8-972e-7ba7a2785fcc.png)

riot-ios at this time untested due to lack of access to a device.
