### ISSUE TITLE
Learning curve for groups is fairly high

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5246]
### Description

Having the experience of understanding the direction of groups made the climb a little bit easier for myself, however in a quick trial of a number of "regular users", everything fell flat.

I explained how to enable group support, then left them on their own to figure it out. Here's some of the comments/noticable problems:
* People kept clicking the "Add featured user" button to invite someone to the group
* People kept clicking the "Add featured room" button to add a room to the group
* People did not understand how flair worked at all
  * Someone found the "Publish" button and clicked it, starting a downhill spiral as to how to make it work
  * Expected to see flair in rooms that were "featured" or part of the group in general - didn't bother to look at the individual room settings
  * Didn't understand how to customize it (wanted a different icon from the group icon)
* Lots of problems with the bugs I've reported up to this point already

Overall, the introduction kinda flopped. People were excited about the groups in general (yay!) and flair when they found it, but towards the end it required a lot of coaching to get help them along. I'm not sure how to resolve some of these issues, but maybe this can help work out some of the bumps.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 61
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lukebarnard1** [comment]
This is valuable feedback, thanks @turt2live

**Comment by lampholder** [comment]
Thank you _so_ much for this, and the rest of your feedback. My triaging fingers are bloody stumps from working through it all, but it's _hugely_ valuable :laughing:

**Comment by turt2live** [comment]
No problem! As groups progress, I'll continue throwing people in the deep end and seeing how it goes :)

**Comment by lampholder** [comment]
Okay, we've discussed a plan to mitigate the above.

For clarity, the objective of this plan is to get a _first cut_ of groups out in front of all users as quickly as possible. What this means is:

- we won't have all of the features implemented, but the subset that _is_ implemented will be useful
- users will be able to use the features without training. This might be achieved through great UX design, or it might be achieved through putting elabourate descriptions on things or through providing multiple routes to achieve the same result.

This doesn't have to be our forever UX - it just has to be simple and workable.

### Okay so what is the plan?

- [ ] Remove the 'Join group' button (for now)
- [ ] Remove the 'Featured users' section - for the time being we'll only expose/manipulate the user list via the right hand panel
    - [ ] Make sure the users in the right hand panel are ordered with the admins at the top
- [ ] Replace the 'Featured rooms' section with a Rooms section, listing all the rooms in a group
    - [ ] Order the rooms in this section by size
- [ ] When User A adds room B to group C, automatically try and add group C to the 'Related Groups' room config for Room B (obviously only succeed if User A has the right power level in Room B)

And yes, we are cutting a lot back here, and losing some of the (perhaps most) useful bits about groups, but we're optimising for useful soon rather than complete/perfect later 🙂

**Comment by lampholder** [comment]
I would also like to suggest (though this hasn't been discussed with anyone) moving the 'leave group' and 'publish/unpublish' UX into the group settings.

For better or ill, you leave a room by going into the room settings.

Publishing/not publishing could be a checkbox rather than a button

**Comment by turt2live** [comment]
Part of the confusion around rooms and groups is the association. Adding a room to a group (via GroupSettings) doesn't seem to do much, but adding a group to a room (via RoomSettings) makes flair work. Is there a plan to also mitigate this confusion?

**Comment by turt2live** [comment]
Overall I quite like the plan, even if it does mean losing some features. Hopefully some rapid development post-launch will recover the lost features ;)

**Comment by lukebarnard1** [comment]
@turt2live 
>When User A adds room B to group C, automatically try and add group C to the 'Related Groups' room config for Room B (obviously only succeed if User A has the right power level in Room B)

**Comment by turt2live** [comment]
oops, thanks for pointing that out.

**Comment by ara4n** [comment]
what is the rationale for removing the join group button?

**Comment by turt2live** [comment]
Currently it doesn't do anything. If it won't do anything by launch time, it feels broken and imo shouldn't be there, until it does something.

**Comment by thekyriarchy** [comment]
With a hopefully solidifying featureset, Riot could probably use a UX overhaul generally. Not sure if a meta-ticket exists for that, but even before groups lots of UI oddities existed such as placement of notifications/user list/etc behind the same sidebar.
