### ISSUE TITLE
Icon disappeared in KDE 5.11 for riot-web: 0.12.6

### ISSUE THREAD

**Issue by akontsevich** [vector-im/riot-web#5305]
Subject

**Comment by clxcoltz** [comment]
Will like to add: there seems to be a long-standing problem where the systray icon will default to an ugly "mostly purple" when installing on KDE Plasma (5.8 - 5.11). I eventually figured out that removing /opt/riot/webapp/vector-icons/favicon.ico AND replacing /opt/riot/app/img/riot.png with a smaller version of itself fixes the issue, but it comes back every release and I'll have to manually do that again. Not sure what was happening, but will like to see a fix.

**Comment by ArchangeGabriel** [comment]
What distro are you on? Do you have any package with appindicator in name installed?

We have this issue on Arch where appindicator is handling the tray icon if installed. Without it we have a blurry icon (see https://github.com/vector-im/riot-web/issues/3133).

**Comment by clxcoltz** [comment]
I tested and it worked the same way on Fedora 26 - KDE and Debian 9 Stretch. As I see right now Debian does have libappindicator3-1 installed, but since my ad-hoc solution works for fixing rendering, I'll stick with it. Never had a problem with interacting with tray icon whether the icon was rendered wrong or not, but then aside from the right-click menu I don't know if I'm missing out on any additional tray-icon features.

**Comment by akontsevich** [comment]
> Will like to add: there seems to be a long-standing problem where the systray icon will default to an ugly "mostly purple" when installing on KDE Plasma (5.8 - 5.11). 

Recent time icon looked ok to me - pretty. 

>What distro are you on? 
openSUSE

>Do you have any package with appindicator in name installed?

Hmm... have some. Need to play with it a little bit. Mono app icon disappeared as well - seems KDE bug. Will report them.

**Comment by akontsevich** [comment]
Restarting KDE solved the problem, sorry.
