### ISSUE TITLE
[query] Password security when connecting to a custom server from Desktop Riot / riot.im

### ISSUE THREAD

**Issue by kwill** [vector-im/riot-web#5602]
**User story 1:** I am an everyday user with an account on an independent home server (`example.im`). I want to log in using Desktop Riot, so that I get the benefits of a desktop client.

**User story 2:** I am an everyday user with an account on an independent home server (`example.im`). I want to log in using `https://riot.im`, because I remember the URL and it offers custom server login.

**Query:** Is my password sent directly and securely to the independent home server (`example.im`), or is it visible to any intermediary servers (for example, `riot.im`)?

**Comment by pafcu** [comment]
@kwill In both cases the password is sent directly to your independent homeserver, _However_, there is nothing stopping the developers running riot.im from changing the code so that the password is not sent to them as well. If you use riot.im/app you are implicitly trusting whoever is running that service.

**Comment by kwill** [comment]
@pafcu Can I theoretically inspect the client-side JavaScript to confirm this, or there anything handled server-side?

On side note, is Desktop Riot a wrapper for `https://riot.im` or does it run entirely client-side?

**Comment by pafcu** [comment]
@kwill: You can theoretically inspect the Javascript. _However_, you would have to do this every time you use the website, because browsers generally have no way of alerting you if the JS they load this time is different than the JS they loaded last time (this is by design how the web works). It's a drawback of _every_ "webapp".

The Desktop app is run entirely client-side using Electron. In fact riot.im/app is just a static webpage that you can host anywhere.

**Comment by kwill** [comment]
Thanks for the clarification!
