### ISSUE TITLE
Desktop notifications have a blank body

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#5606]
When I receive a desktop notification it doesn't include the body:

![image](https://user-images.githubusercontent.com/8428120/32844417-49da596e-ca1a-11e7-9dad-14f8d32e2b40.png)

(The message was simply a plaintext "erik: test")

### Version information

- **Browser**: Chrome
- **OS**:  Ubuntu
- **URL**: riot.im/develop

**Comment by turt2live** [comment]
This is a confirmed case of granular settings gone awol. Previously the notification settings were tied together such that reasonable defaults were chosen. However, that got changed slightly to better support each setting's independence.

The fix is a bit dirty, but the idea would be to assume different defaults for the child settings (notification body, audio notifs, etc) either through the handler or controller (whichever is actually the problem).

**Comment by turt2live** [comment]
@erikjohnston has this since been fixed? Should have been done by https://github.com/matrix-org/matrix-react-sdk/pull/1613

**Comment by turt2live** [comment]
@erikjohnston second ping :)

**Comment by erikjohnston** [comment]
Yeah, fixed now :)
