### ISSUE TITLE
Inconsistent button order in dialogs

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5689]
### Description

In dialogs with OK and cancel buttons, sometimes OK comes first, and sometimes Cancel comes first.

Probably it would be a good idea for the developers using macOS (Cancel to the left) and the other developers (Cancel to the right) to get together and settle on one.

e.g. 

Cancel to the left:
![image](https://user-images.githubusercontent.com/62835/33234304-a5e2ced2-d224-11e7-86e3-377642b91e40.png)

Cancel to the right:
![image](https://user-images.githubusercontent.com/62835/33234329-39f51724-d225-11e7-8d35-5f642269aaae.png)

Cancel to the right:
![image](https://user-images.githubusercontent.com/62835/33234307-bcb4e23a-d224-11e7-8e71-b289292c8f00.png)

### Version

Riot-web c28d9e5cde96-react-c002d3ff9967-js-36ff0ad0193e on FF57

**Comment by aidalgol** [comment]
There appears to be a definite precedent for the primary button on the right.  @t3chguy, can you give a definitive answer?

**Comment by ara4n** [comment]
So, I've just gone through the original blueprints for the app (which were provided by a design agency), and it turns out that the Cancel button looks to be a thinko or a hangover from previous designs.  The actual intention was for the (X) button in the top right to cancel dialogs, leaving only one action button in the bottom left, which then simplifies things lots and solves the whole Windows v. Mac dilemma.  (That said, where we *do* have to make that choice, I'd agree that putting primary button on the right makes more sense).

**Comment by aidalgol** [comment]
Is that still the intention to have the (X) button _instead of_ a Cancel button?  If so, I will go through the all the dialog components, make sure they are derived from `BaseDialog`, and remove the Cancel buttons.  (I'm already in the process of the first part.)

**Comment by lampholder** [comment]
I'll try and get a conclusion on this :)

**Comment by lampholder** [comment]
Right, consensus was achieved on the following:
- Modals have (X) buttons
- Modals have a [Cancel] (or similar "no" or "don't do" meaning) button as the leftmost button
- Modals have the main affirmative button as the rightmost button
- Secondary action buttons can go in between
- Buttons are aligned to the bottom right hand side of the modal

We did not yet achieve consensus on whether some modals should have _no_ (X) (in order to force an active decision from the user), but I don't think that hinders us from making progress for now.

There's more work to be done on homogenising our modals and implementing best practices, but this is a valuable step to take independent of any further rabbit-holing.

**Comment by turt2live** [comment]
fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2231
