### ISSUE TITLE
@room notification should have permissions

### ISSUE THREAD

**Issue by VonManGuy** [vector-im/riot-web#5763]
I have moved a large group over to this platform and with this command notifications can be a real pain as people will abuse it just like how on the Discord platform people use the @everyone. I was wondering if there would be a way to limit the use of @room to only admins.

**Comment by t3chguy** [comment]
That is how it should be, by default

**Comment by t3chguy** [comment]
I just tried `@room` in a room that I am not an admin of and on another account did not receive a notification: 
![image](https://user-images.githubusercontent.com/2403652/33510811-1113bc46-d709-11e7-9b4c-68f53140167c.png)

**Comment by HorridComedian** [comment]
Well I will be damned. Then its working as intended. Its not really a bug more like me not knowing about a feature. Better documentation about certain features like this would be nice unless I cant search properly either lol.

**Comment by t3chguy** [comment]
I believe the powerlevel required for it being configurable is an open bug *somewhere*

**Comment by HorridComedian** [comment]
As someone who is moving away from Discord because they are not an open platform having something that shows the equivalent features from that platform would be helpful to new users. I think this platform is great minus the VOIP not having icons to see who is talking and seeming a big funky for a group larger then 10.

**Comment by ara4n** [comment]
yup, i think this is a dup of the doc bug
