### ISSUE TITLE
Decryption not working on web client, but is on Android app

### ISSUE THREAD

**Issue by PatrickRose** [vector-im/riot-web#5888]
### Description

I have a Riot room (3 people) with E2E enabled and infrequently encryption will work on the app but not on the client. Annoyingly, this seems to be infrequent and is only happening with _one_ of the other members of the chat. Not sure what other information I can give I'm afraid!

Log: sent

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 57.0.2 (64 bit)
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by uhoreg** [comment]
The main issue for tracking "Unable to Decrypt" bugs is https://github.com/vector-im/riot-web/issues/2996.  It's likely that one of the issues linked in there is the cause of your bug.  There is also some information in the second-last section of https://www.uhoreg.ca/blog/20170910-2110 that may help fix the problem for you.  But before trying those out, if you want, you can report a bug within the app (e.g. for Riot web/desktop click the "Report it" button in the user settings, and for Riot mobile, shake your device until it prompts you to submit a report).  Do this on both the sending and receiving device for messages that can't be decrypted, and make sure to include logs.  This will send more information to the developers so that they can see if it's a new issue, or one of the already-known issues.

**Comment by lampholder** [comment]
Thanks for filing, @PatrickRose - as @uhoreg says please report your problem as described to help us get to the bottom of it :)

**Comment by PatrickRose** [comment]
I did send the logs when I reported it, but I'll keep doing so if it happens again!
