### ISSUE TITLE
We should probably turn RTE on by default (rather than MD) to avoid confusing normal users

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5945]

**Comment by lampholder** [comment]
I'm not sure about this.

Counter arguments:
- our 'normal' users today probably _are_ familiar with markdown, and the option to turn markdown on is hard to see (when it is turned off)
- slack and whatsapp both default to MD (or radical subsets thereof) quite successfully

**Comment by ara4n** [comment]
<img width="865" alt="screen shot 2018-01-08 at 21 40 39" src="https://user-images.githubusercontent.com/1294269/34693692-9710fa4a-f4bc-11e7-9a5a-d44e4d9f43b0.png">

 * We can obviously make MD more obvious - and keep it turned on for existing users.
 * I'd argue that nobody uses WhatsApp as seriously for advanced collaboration (e.g. code collaboration) as Riot
 * What subset of MD does Slack actually support? I thought it had an RTE?

**Comment by turt2live** [comment]
ftr, granular settings tracks the editor preference. It should be as simple as changing the default value.

**Comment by romainf-unity** [comment]
> slack and whatsapp both default to MD (or radical subsets thereof) quite successfully

I disagree, Slack has a very very very small and derived subset of MD.
There's only 6 formatting possible:
* \*bold\*
* \_italic\_
* \~stroke\~
* \`code\`
* \`\`\`preformated\`\`\`
* \> quote

As you can see they simplified a lot the formatting features. They even simplified the bold and italic format, using only one character for each, instead of \* and \*\* (or \_ and \_\_). And they added the \`\`\` formatting because they know most of their users share blocks of code.

I like the fact that Riot follows a standard like CommonMark, but the real life experience is that most of the time it gets in the way of my users. They are mostly developers, they simply don't want to understand the ins and outs of Riot, which is understandable I think.

They don't really complain, they just use workarounds or simply try not to use CommonMark at all, which defeats the purpose.

Unfortunately, I don't have a silver bullet here. The more it goes and the more I think Slack took a good decision in the end: a simplified version exposed by the client to the user.

That being said, maybe there is a solution: how about the client (Riot) is proposing a subset of CommonMark (bold \*\*, italic \_, stroke \~\~, quote \>, code \`, and code block `    `). If the user wants more, he clicks on a button in the text area that pops up a more complete editor where he can do anything that CommonMark can do.

**Comment by MightyCreak** [comment]
> slack and whatsapp both default to MD (or radical subsets thereof) quite successfully

I disagree, Slack has a very very very small and derived subset of MD.
There's only 6 formatting possible:
* \*bold\*
* \_italic\_
* \~stroke\~
* \`code\`
* \`\`\`preformated\`\`\`
* \> quote

As you can see they simplified a lot the formatting features. They even simplified the bold and italic format, using only one character for each, instead of \* and \*\* (or \_ and \_\_). And they added the \`\`\` formatting because they know most of their users share blocks of code.

I like the fact that Riot follows a standard like CommonMark, but the real life experience is that most of the time it gets in the way of my users. They are mostly developers, they simply don't want to understand the ins and outs of Riot, which is understandable I think.

They don't really complain, they just use workarounds or simply try not to use CommonMark at all, which defeats the purpose.

Unfortunately, I don't have a silver bullet here. The more it goes and the more I think Slack took a good decision in the end: a simplified version exposed by the client to the user.

That being said, maybe there is a solution: how about the client (Riot) is proposing a subset of CommonMark (bold \*\*, italic \_, stroke \~\~, quote \>, code \`, and code block (4 spaces)). If the user wants more, he clicks on a button in the text area that pops up a more complete editor where he can do anything that CommonMark can do.

**Comment by t3chguy** [comment]
We no longer have RTE as we doubled down on Markdown + formatting buttons
