### ISSUE TITLE
regression: we now show a spinner at the bottom of every room for ~30s after launching the app

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6068]

**Comment by dbkr** [comment]
I looked into this a bit: my suspicion is that it's waiting for an additional `/keys/changes` request that we're doing because the device list sync token is older than the sync token in the stored sync request. In practice this request should do nothing, but we still need it because we can't be sure the device list store saved correctly. If this is indeed what is causing this, we'll have to think about how to fix it safely.

**Comment by dbkr** [comment]
Update: having got Matthew to repro, it looks like my hypothesis is broadly correct (plus we have a shedload of groups requests going on at the same time for the Tag Panel):

https://matrix.to/#/!WCHwNGGsrVwPeRtAnq:matrix.org/$15174950301118850fPpTb:matrix.org
```
so the spinner-at-bottom-of-page looks to be blocked on a bunch of groups which took 22s :|
(having just reloaded)
and also a keys/changes req that took 48s
each group req took ~20s, of which there were about 20

summary / rooms / invited_users per each group i'm in
```

**Comment by lukebarnard1** [comment]
>shedload of groups requests going on at the same time for the Tag Panel

These will be a red herring - the requests don't effect the state of the sync.

**Comment by ara4n** [comment]
the spinner now shows for about 2 minutes.

**Comment by turt2live** [comment]
I usually see up to 10-15 minutes to be honest.

**Comment by dbkr** [comment]
So, this is Riot actually having a *newer* token in the device list store than in the sync store, because we write the device list immediately, whereas we only write the sync store every 5 minutes. We're also writing it unnecessarily often, so the first thing that will help this is https://github.com/matrix-org/matrix-js-sdk/pull/623

**Comment by dbkr** [comment]
...there is actually more to this. Having debugged this over Matthew's shoulder, this is now the first incremental sync request getting queued behind all the groups requests which number in the tens and take a couple of seconds each. Easiest fix for this is probably to limit the number of concurrent groups requests.

**Comment by ara4n** [comment]
just dug into this with dave; looks like what's happening is that the groups stuff spins up a whole flood of GET requests to get the users, invited_users, summary and rooms for the groups you're in.  This means about 20 concurrent HTTP hits start, and for whatever reason these requests take ages (to the extent that they often 504).  This in turn stalls the first initial sync.

I am bemused and sad as to why the groups API makes us poll for all this rather than shoving it down /sync like everything else.

**Comment by ara4n** [comment]
see also https://github.com/matrix-org/synapse/issues/2966

**Comment by lukebarnard1** [comment]
Mitigated by https://github.com/matrix-org/matrix-js-sdk/pull/629
