### ISSUE TITLE
Can no longer accept calls from Chrome Canary?

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6081]
Possibly because of `Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.`

**Comment by MTRNord** [comment]
I think Google changed that Tabs cant autoplay any Audio without having the user to activly click a Button to do so

**Comment by lampholder** [comment]
Tabs' not autoplaying audio without active button click sounds like a great feature that I'd guess we can expect to see implemented cross browser in the not too distant future.

We have an early warning then that this is something we're going to have to tackle/work around; worth considering sooner rather than later if we can find the bandwidth.

**Comment by dbkr** [comment]
After looking into this for a bit, the `play()` thing is a complete red herring. The problem is that the buttons aren't getting the 'click' events, although I don't yet know why. Clicking triggers a 'focus' even on the LeftPanel and in one of these states it gets the mousedown event but not the mouseup, in the other, vice versa, so clicking repeatedly, the button will get a mousedown, then on the next click, a mouse up, but never both on the same mouse button click and never the actual 'click' event.

This may just be something going very screwy with event routing on Canary.
