### ISSUE TITLE
Add an option to require a click to insert emoji from the picker

### ISSUE THREAD

**Issue by eternaleye** [vector-im/riot-web#6150]
### Description

In an [earlier issue](https://github.com/vector-im/riot-web/issues/4974) about the emoji picker being over-eager about replacing message content, there was a [degree of consensus](https://github.com/vector-im/riot-web/issues/4974#issuecomment-331931963) that acting on mouse-over was intrinsically too aggressive.

However, the ticket was closed after only changing the behavior to require actual mouse movement (as opposed to instantly on the picker opening), rather than after the full change was implemented. This results in subpar UX in various cases, especially when the mouse moves slightly during typing (which happens to me frequently, due to the placement of my touchpad).

Some have expressed a preference for the mouse-over behavior, but could those of us who feel otherwise have an option to disable it?

### Steps to reproduce

- Begin typing an emoji sequence, with the mouse slightly above the input area
- Slightly move the mouse
- See the sequence replaced by an entirely random emoji based on where the mouse was, rather than what you had been typing (and were intending to tab-complete)

Instead, I'd expect the user input to be preserved without some form of positive confirmation (click, tab, etc).

- **Platform**: Web
- **Browser**: Firefox 57
- **OS**: Exherbo Linux
- **URL**: riot.im/develop

**Comment by cmr** [comment]
This is, frankly, the last UI annoyance I have with Riot. Otherwise, I am extremely happy with it as a client.

**Comment by lampholder** [comment]
fb messenger requires an overt click; slack has the same behaviour as Riot does today.

This is tough, because it's hard to strike a balance between customisable behaviour and too many checkboxes in the settings panel.

That said, we currently expose such fine-grained configuration features as choose-your-own-autocomplete-delay, so having the ability to choose whether autocomplete picking is triggered by mouseover or mouse click certainly is in line with that, philosophically.

Perhaps the answer is to add (yet) another customisable option for this, and then when we come to rework the settings UI make sure that composer settings are somehow sensibly and clearly grouped.

**Comment by turt2live** [comment]
tbh, I'd prefer the default to be requiring a click/tab/positive action as mentioned in the OP. I'm also often bitten by the mouse problem (granted, this might be a result of Riot not having focus on the field all the time, so my mouse is almost always in the area because I'm having to click the composer).

**Comment by aaronraimist** [comment]
Isn't this already the default behavior? I can't reproduce your issue in Safari, Firefox, or Chrome on my Mac.

For me, Emoji don't get inserted until you tab over to them or click them in Riot 0.16.4 or the current /develop

**Comment by t3chguy** [comment]
This was changed with slate
