### ISSUE TITLE
Bad experiences when creating groups

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6208]
I created a new group from the GroupsPage.
*  It didn't show up in LLP for a while (i /think/, although I may have missed it due to it having the wrong avatar)
*  It got added to a weird place in the LLP - second from last group, making it hard to spot that it had been added.
* [x] I set an avatar; this didn't get reflected in the LLP - fixed by https://github.com/vector-im/riot-web/issues/6208
*  I enabled flair for this group in a room; flair doesn't appear.

**Comment by turt2live** [comment]
> I set an avatar; this didn't get reflected in the LLP
https://github.com/vector-im/riot-web/issues/6189

Related flair bugs:
* https://github.com/vector-im/riot-web/issues/5957
* https://github.com/vector-im/riot-web/issues/6202
* https://github.com/vector-im/riot-web/issues/5235
* https://github.com/vector-im/riot-web/issues/5559 (maybe the one you hit?)

**Comment by lampholder** [comment]
I think there's a chance we're going to want to address at least some of this before releasing 0.14, so I'm adding it to that milestone to make sure it doesn't get forgotten.

**Comment by lukebarnard1** [comment]
The issues are due to:
 1. FlairStore caching
   a. User <-> publicised group mappings
   b. Group profile data
 2. GroupStore caching:
   a. Rooms associated with the group
   b. Users associated with the group

Solutions
 1. Can be partially solved by reducing the cache time from 30mins down to something much more real-time. This will increase traffic but we haven't suffered so far, so it feels safe to decrease it a bit but keep it on the same order, so perhaps 5mins? It might be a good idea to (a) immediately pull new data for the user making changes (b) tell the user that it will take some time to update for other users.
 2. Can be solved by finishing https://github.com/vector-im/riot-web/issues/5902

**Comment by lampholder** [comment]
We think we have address all of the material problems with creating groups (_real_ solutions would involve addressing some of the caching problems, but this was scoped to improving the UX which we've achieve with a mixture of local echo and explanatory microcopy)
