### ISSUE TITLE
Scroll jumping when back paginating

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6265]
Reported by @AmandineLP 

Pagination is broken when I try to scroll back too quickly.

If I scroll back too quickly in a room, at some point (I assume when I reach the end of what is cached) the timeline only jumps slightly up and down, as if trying to find the right place to be. I have to wait several seconds to be able to start scrolling again.

**Comment by lukebarnard1** [comment]
Would be really useful to know which platform/browser/version we're talking about here!

**Comment by AmandineLP** [comment]
Sorry I thought this was a rageshake. Using trackpad on my macbook air, in Chrome (64 today). I can show you IRL

**Comment by lukebarnard1** [comment]
Oh my bad, I didn't see the ref to the rageshake.

**Comment by lukebarnard1** [comment]
>trackpad on my macbook air

I have to say that I've witnessed the same on my Mac and I think the conclusion was that it would require a rewrite of our scroll component (ScrollPanel). 

In short, the Mac fires scroll events at a very high frequency which makes it likely for one to fire immediately after a scroll jump has occurred - the panel then takes this incorrect position as truth because we save it.

The issue for me is that we have an implementation that saves & restores the scroll position. In theory we could have one the relies entirely on a new technology - web anchoring. Interestingly, Chrome does this remarkably well and I even tested this in the past with Riot. 

The conclusion here was that until all major browsers support this, we continue to maintain a single code path as we don't have capacity to maintain two different code paths for the same component. 

It's possible that we're missing out though.

**Comment by lukebarnard1** [comment]
This is related to https://github.com/vector-im/riot-web/issues/2646

**Comment by ara4n** [comment]
this is really sucking - i'm seeing jumps of several pages when I backpaginate.

**Comment by ara4n** [comment]
@lampholder says this has got worse since /experimental; for me it's got better. i'm going to investigate.

**Comment by ara4n** [comment]
this has been eclipsed by https://github.com/vector-im/riot-web/issues/8565
