### ISSUE TITLE
why does the groups button on the llp have opacity: 0.5?

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6397]

**Comment by lampholder** [comment]
The groups button should appear the same as the other bottom left buttons - i.e. 100% opacity, no change on hover.

**Comment by ara4n** [comment]
i think this was a deliberate cosmetic choice when it was a (+) button, but now it's become a groups button it makes zero sense.  Have fixed in df5ffb5a6d99d40c1520e8f22ccbc9e3f18cdf53 (and pushed directly as it's utterly trivial) - and fixed the CSS which wasn't renamed when the button icon was changed :(
