### ISSUE TITLE
'Last seen' IP address is incorrect

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#6406]
possibly related to CloudFlare?  e.g. it lists my desktop and tablet as 38.121.82.210 and 99.224.204.143, neither of which are my IP address

**Comment by jtl999** [comment]
To clarify, this is an issue with the matrix.org homeserver.

I live in BC, Canada and my home IP address is in the 162.156.x.x range. Funny enough some of the random IP addresses that were listed were near Vancouver, one was from Winnipeg, another was University of Idaho. Another was Kitimat, BC Telus.

But Cloudflare IP rangers are different to what I've seen in the "Last seen" column tonight, none of them were from Cloudflare

Either we have a severe technical glitch or someone with a gazillion exit nodes hacking multiple Matrix.org accounts.

**Comment by jtl999** [comment]
Interesting seeing how many of the "last seen" IP addresses are of reasonably close proximity to Vancouver

```
Resolving IP: 73.109.159.113
{
  "ip": "73.109.159.113",
  "hostname": "c-73-109-159-113.hsd1.wa.comcast.net",
  "city": "Renton",
  "region": "Washington",
  "country": "US",
  "loc": "47.4637,-122.2140",
  "postal": "98055",
  "org": "AS7922 Comcast Cable Communications, LLC"
}
```

**Comment by jtl999** [comment]
Oh look. An IPv6 prefix that isn't mine.

```
Resolving IP: 2001:569:f9e4:7a00:2da5:a5f5:bbc7:9609
{
  "ip": "2001:569:f9e4:7a00:2da5:a5f5:bbc7:9609",
  "city": "Kitimat",
  "region": "British Columbia",
  "country": "CA",
  "loc": "54.0524,-128.6530",
  "postal": "V8C",
  "org": "AS852 TELUS Communications Inc."
}
```

Definitely smells like some CDN shenanigans given the proximity.

**Comment by wey1288** [comment]
I guess me strange here,  never smth to understand, sorry me opt off. Bye
guys
On 28 Mar 2018 9:32 am, "JTL" <notifications@github.com> wrote:

To clarify, this is an issue with the matrix.org homeserver.

I live in BC, Canada and my home IP address is in the 162.156.x.x range.
Funny enough some of the random IP addresses that were listed were near
Vancouver, one was from Winnipeg, another was University of Idaho. Another
was Kitimat, BC Telus.

But Cloudflare IP rangers are different to what I've seen in the "Last
seen" column tonight, none of them were from Cloudflare

Either we have a severe technical glitch or someone with a gazillion exit
nodes hacking multiple Matrix.org accounts.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vector-im/riot-web/issues/6406#issuecomment-376749827>,
or mute the thread

**Comment by wey1288** [comment]
First such style i met in twitter, 2 years ago
. Anya involved me in that dark . Shit. I beleive will not go crasy

**Comment by richvdh** [comment]
so, this should now be fixed in future, though people may still see incorrect IP addresses prior to us deploying the fix at 14:25 UTC.

Background: Cloudflare give us the IP address of the client via an X-Forwarded-For http header. Sometimes they send us multiple requests, possibly from different clients, over the same TCP connection, via HTTP 1.1 keepalives.

It turns out that we were not correctly honouring the X-Forwarded-For header for the second and subsequent requests, and instead attributing them to the same IP address as the first request. (This also explains why the "incorrect" IP addresses tended to be geographically located close to the "correct" IP address: you only end up sharing a TCP connection if you go through the same Cloudflare server).

Sorry for the snafu.
