### ISSUE TITLE
Default colour scheme doesn't apply until you're in a room

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6424]
### Description

```
"settingDefaults": {
  "roomColor": {
    "primary_color": "#a442f4",
    "secondary_color": "#cc92fc"
  }
}
```

Having the above in your config.json should give you a vibrant purple Riot. However, if you open riot and log in to a newly created account (no rooms) you'll end up with a default interface until you join a room. May need to use a fresh browser session as well, not sure.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: Private deployment (0.14.0-rc.4)

**Comment by MTRNord** [comment]
Happens with the "guest starter page" too. According to the log the tinter never got called on that page. So it might just miss a function call.

**Comment by MTRNord** [comment]
I debuged it to the point where I tracked it down to the onload's on the elements not getting triggered and the disabled flags not getting removed/falsed on firefox. Triggering the onload manual fixes the tinting issues

**Comment by MTRNord** [comment]
Only fix I found atleast in firefox is to remove the onload check. This is because of 2 reason:

1. From my understanding from classic DOM loading the js code which is included at the bottom of the body gets called after everything before it loaded
2. From the logic of 1 I can now assume that a onload set on the stylesheets gets already never triggerd as the onload obviously never fires at that point as the stylesheets are already loaded.

The second point leads to the solution of just removing the onload check and just call the setTheme. In my tests in Firefox with virtual slow internet speed it always worked and I didn't get side effects from calling setTheme directly. After having a Theme set the tinter obviously knows what it has to do. The reason it works after room changes is simple too: The onload triggers after it as the url changes when switching rooms. 

Please tell me if 1 is wrong if so my solution will have race conditions. If 1 is correct I dont think there will be race conditions. I am not sure if HTTP2 changes the DOM loading order or if it just preloads everything.

**Comment by MTRNord** [comment]
Well Matthew pointed out in Riot-dev that chrome needs the onload. And yes it works under chrome using the onload but not under firefox. So this more likely needs a browser detection to work correct

**Comment by MTRNord** [comment]
This PR should fix it while not breaking chrome: https://github.com/vector-im/riot-web/pull/6831
