### ISSUE TITLE
Stickerpack feedback: tooltip sticks around

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6441]
> the tooltip doesn't go away when one moves the mouse to hover over the image next to it. And is also clickable and sends the event

from https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15227822384550324eUvpZ:matrix.org

cc @rxl881

**Comment by aaronraimist** [comment]
What browser do you see this issue on? Works fine for me on /develop right now in Firefox 59.0.2

**Comment by turt2live** [comment]
For reference, this is the tooltip:
![image](https://user-images.githubusercontent.com/1190097/38272589-e2dc2c98-3746-11e8-8848-3e0a0806e8dd.png)

Clicking on 'Carrot' causes carrot to be sent, and it's relatively annoying to try and get at the sticker under the tooltip.

Chrome 65 for me.

**Comment by rxl881** [comment]
I believe that this is an issue when you move the mouse cursor such that it moves directly from the selected sticker over the tooltip covering the adjacent image. As soon as you move the cursor off the tooltip on to the adjacent image, it disappears and the correct tooltip is displayed.

![stickers](https://user-images.githubusercontent.com/6763606/38807168-ab3113f8-4173-11e8-91fe-c68f11483f9a.png)
 
I think that this should be (easily) fixed by setting the tooltips to accept no pointer events.

**Comment by rxl881** [comment]
I believe that this should now be fixed as a result of a number of related PRs that addressed sticker picker layout and performance. I'm going to close this for now, but please fee free to re-open if you are still seeing any issues. Thanks.
