### ISSUE TITLE
Notification sound plays after being turned off in system preferences

### ISSUE THREAD

**Issue by natestemen** [vector-im/riot-web#6442]
### Description

Notification sound persists after turning it off in Notifications within System Preferences.

### Steps to reproduce

- Open system preferences on mac
- -> Notifications 
- under Riot, uncheck "Play sound for notification"
- listen to notification sound

### Version information
- **OS**: MacOS High Sierra 10.13.3
- **Version**: 0.13.5

**Comment by rib** [comment]
I'm also seeing that if I have 'Noisy' notifications turned off for everything then I'm still getting notification sounds. For me it seems to make a difference if I have the riot.im tab focused then I won't get a noisy notification, but when I switch apps/tabs then it seems to ignore my preferences to turn of noisy notifications. For now I have to turn off notifications since I'm having a mini heart attack whenever people send messages. I separately wish there was a way to change the sound to at least be a little more subtle.

I'm also running on MacOS, but with Mojave, 10.14. I'm using Firefox Nightly.

**Comment by t3chguy** [comment]
The Electron (HTML5) Notification API doesn't allow to specify custom sound only the generic system one so the app just plays sounds internally; it has an option to turn off audio.

![image](https://user-images.githubusercontent.com/2403652/88453714-64696600-ce61-11ea-9882-d6903223655d.png)
