### ISSUE TITLE
Discussions are strangely filtered when a community is selected [v0.14]

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#6490]
### Description / Steps to reproduce

When a community is selected the discussions displayed in the "Personnes" (French for "People") section aren't coherent.

Say I have two contacts: P1 and P2, and two communities: C1 and C2.
I am in C1 and C2.
P1 is in C1 only.
P2 is in C1 and C2.

I've seen two issues so far:
    1. I have a 1:1 discussion with P1, but when I select C1, this discussion doesn't appear in the "Personnes" section.
    2. I have a discussion with P1 and P2, and when I select C2, the discussion appear in the "Personnes" section.

The first case seems like a bug: all the 1:1 discussions with people in a community should be listed when the community is selected.

The second case is a bit harder to grasp, but basically what is weird is that the discussion should only appear when I select C1 since all the member in this discussion are part of C1. But the discussion also appear when I select C2, even though not all the participants are in C2.

### Version information

- **Platform**: web

For the web app:

- **Browser**: Rambox 0.5.16
- **OS**: macOS
- **URL**: riot.im/app

**Comment by lampholder** [comment]
Case 1 does sound like a bug - we use some heuristics to decide whether or not a 1:1 is shown when a community filter is selected, that might not be working correctly.

Case 2 is probably an issue with the same heuristics.

**Comment by spantaleev** [comment]
I've had what I believe is "Case 1" happen to me as well.

Turns out that the problem was that:
- the given room (what I believed was a 1:1 chat) was **not** a FULLY direct chat, as it was **not part** of the `m.direct` account data. Because of this, the Room List (`RoomList.js`) calling `dmRoomMap.getDMRoomsForUserId(member.userId)` was returning an empty array, indicating that this room should not be shown when filtering by a community which has that user as a community member.
- opening the context menu for the room (`RoomTileContextMenu.js`) had `isDirectMessage = true`, because for some reason `dmRoomMap.getUserIdForRoomId(this.props.room.roomId)` was returning a user id. Because of this, the room was indicated as **Direct Message**, even though it wasn't fully a direct message room.

So it seems like this Direct Message thing is fragile.. And the UI is confusing. Some things (the room context menu) indicate that a room is a direct message, others indicate that it isn't. Different things (Context-Menu vs Room List) use different code to judge things, which leads to confusion.

IMO, the `m.direct` account data thing is fragile by design, as any modification completely overwrites its data and it's possible that using multiple clients simultaneously can lead to data loss. It might be reason for what happened to me.

----------

Workaround:

- go to the room context menu and press **Direct Message** to force-unset the direct message flag (it likely hadn't been fully set to begin with)
- go to the room context menu again and press "Direct Message" again. This should put the room in the `m.direct` account data properly this time
- restart Riot to cause the "user to room / room to user" mappings to refresh (otherwise the change you did won't kick in)
