### ISSUE TITLE
Emoji rendering destroys paragraphs

### ISSUE THREAD

**Issue by spantaleev** [vector-im/riot-web#6523]
This seems to be a regression since `0.14.0`.

The paragraphs in the following message get destroyed while rendering.

Original (as it appears in the message input box):

```
test 🙂

test
```

Resulting event:

```json
  "content": {
    "body": "test 🙂\n\ntest",
    "msgtype": "m.text"
  },
```

**Incorrectly** renders as:

![riot-web-emoji-plain](https://user-images.githubusercontent.com/388669/38767542-b590bfc4-3fe3-11e8-8a0a-cda13f19cb38.png)

----------

# Workaround 1

Forcing Markdown-processing to trigger works around this problem.

The following message:

```
**test** 🙂

test
```

produces the following event, which renders correctly (paragraphs are preserved):

```json
  "content": {
    "body": "**test** 🙂\n\ntest",
    "msgtype": "m.text",
    "formatted_body": "<p><strong>test</strong> 🙂</p>\n<p>test</p>\n",
    "format": "org.matrix.custom.html"
  },
```

-------------

# Workaround 2

If there's no emoji in the text, everything works well.

The following message:

```
test

test
```

produces the following event, which renders correctly (paragraphs are preserved):

```json
  "content": {
    "body": "test\n\ntest",
    "msgtype": "m.text"
  },
```

**Comment by lukebarnard1** [comment]
We apply the CSS class `markdown-body` in messages with emoji (because we insert emoji with HTML). This class includes the rule `white-space: normal;`. 

With `white-space: normal`, "Sequences of whitespace are collapsed..." including newline characters.

Using `white-space: pre-wrap` (preserves `\n` as `<br>`) might be a solution (which is what `.mx_MTextBody` defines) , but it would be worth:
 - testing this in a whole world of different cases
 - finding out why we're using `white-space: normal` (perhaps something to do with wrapping? or overflowing?)
 - writing a bunch of unit tests for EventTile :hearts:

**Comment by ZerataX** [comment]
Same seems to happen for Braille Patterns U+2800-U+28FF) possibly more.

**Comment by spantaleev** [comment]
Will this see some fix/workaround in 0.14.x?

Seems like a pretty annoying regression to drag along.

**Comment by MazeChaZer** [comment]
I found the problem that caused this bug, will submit a pull request this evening.

**Comment by MazeChaZer** [comment]
See matrix-org/matrix-react-sdk#1910

**Comment by lukebarnard1** [comment]
It does indeed, merged :smiley:
