### ISSUE TITLE
Room/chat labels on left panel failing to render

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/riot-web#6594]
### Description

Room and people labels in left panel fail to render after a screen resize.

Chrome, OSX, /develop

### Steps to reproduce
Resize chrome to half screen size, responsive design means that rooms and chats are repsented by avatar only.

Resize window to full screen and rooms/chat are /still/ represented by avatar only.

Can be fixed by reload or by continuing to resize

Behaviour is intermittent - cannot reproduce now to send screen shot, but I have this twice in two days.

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chrome 66.0.3359.117
- **OS**: macOS 
- **URL**: riot.im/develop

**Comment by dbkr** [comment]
I get this almost every morning now, so this morning I had a quick look and it's because the room name element is being pushed below the image, in this case probably because of gemini scrollbar adding its extra phantom scrollbar when my laptop gains or loses a pointing device.

![screen shot 2018-05-08 at 10 11 16](https://user-images.githubusercontent.com/986903/39748853-2331c668-52a9-11e8-9ccf-16973f1a3bf8.png)

**Comment by lukebarnard1** [comment]
This seems very similar to https://github.com/vector-im/riot-web/issues/6919

**Comment by turt2live** [comment]
I believe we fixed this in the redesign when we saw it.
