### ISSUE TITLE
Restarting Firefox looses local E2E encryption keys

### ISSUE THREAD

**Issue by schmittlauch** [vector-im/riot-web#6621]
### Description

*I'm sure this is a duplicate of some issue, but I just couldn't find a relevant one so far.*

Whenever I restart my Firefox, I am not able to decrypt previous messages from E2E rooms I wrote or which were sent to me, because apparently the local keys got lost.

I set up Firefox to purge cookies at restart, but not "offline website data" (which I think should be LocalStorage). So I expect the keys to remain between browser sessions. 

### Steps to reproduce

- start an E2E conversation
- exchange messages with communication partner
- restart Firefox (in my case without logging out, don't know if that'd make a difference)
- log in again because session cookies have been purged
- see that messages from the past can't be decrypted anymore due to missing key

Log: not sent

### Version information

- **Platform**: web (in-browser)

- **Browser**: Firefox 59.0.2
  - special settings: `about:preferences#privacy` set up to clear Cache, Cookies and History when closing Firefox
- **OS**: Gentoo Linux amd64
- **URL**: riot.im/app

**Comment by dbkr** [comment]
If you're getting logged out, it's because your localstorage is being deleted. To be honest, I couldn't tell you what exactly Firefox means by, "Offline website data". It seems Firefox itself isn't entirely sure (https://bugzilla.mozilla.org/show_bug.cgi?id=1047098). In this case, localstorage is presumably included as part of 'cookies'.
