### ISSUE TITLE
Infinite spinner on joining a room

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6679]
I still reliably get an infinite spinner joining a room on my local dev riot/synapse:

1. Create new account
1. Go to room directory
1. Click on a publicly joinable, peekable room
1. Click 'join' on the top panel bit
1. Observe that your join event appears at the bottom of the room and the room appears in your left panel
1. Wait an infinite amount of time
1. Observe that the top panel with the spinner is still there and you have no composer

**Comment by lampholder** [comment]
I often get infinite spinners on joining new rooms/rooms for the first time :(

**Comment by lukebarnard1** [comment]
My suspicion here is that the room view store is not updating the view when it should. I shall investigate this.

**Comment by bwindels** [comment]
I've been hitting this with a local synapse & riot. From looking at the /sync calls, /sync doesn't seem to wake up (sometimes) when calling /join and when it times out, room.joins doesn't contain the new room. 
Being a local synapse with nothing else happing, it's probably easier to see /sync not waiting up because there is nothing else happing anywhere that would wake up /sync.

The weird thing is that it only happens sometimes so hard to tell whether it's a server or client or both bug. Need to investigate more.

**Comment by bwindels** [comment]
Looks like a server bug to my untrained eye.
The below video was recorded with local synapse on develop, and riot all repos on develop as well.
Upon joining a peeked room, synapse doesn't seem to return from /sync poll for the newly joined user until something actually happens in the room. In the video you can see the request for joining a room completes successfully, but /sync keeps on polling until sometimes happens in the room timeline (or returns empty if nothing happens). As I understand it, /sync should report newly joined rooms immediately after joining them.

![infinitespinner3](https://user-images.githubusercontent.com/274386/43126906-6159df9a-8f2e-11e8-9891-dcc500e91ffe.gif)

**Comment by bwindels** [comment]
Not a synapse bug, indeed related to what Luke described. See https://github.com/matrix-org/matrix-js-sdk/pull/673
