### ISSUE TITLE
Replies "X ... in reply to Y" doesn't read well

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6969]
![2018-07-03-131129_445x216_scrot](https://user-images.githubusercontent.com/6750344/42219193-f8a0a162-7ec2-11e8-8ea1-df86c0cb38c2.png)

When a reply is read top-to-bottom, it effectively reads "Person Replying ... in response to Original Poster ... Previous Person Replying: Previous Reply ... Reply Text".

In the example above, one would read "Luke in reply to Erik... Benpa: message text ... message text". This feels unnatural. 

I have a suggested design, but not sure about the positioning of the "..." and ofc it would need appropriate styling:
![2018-07-03-132050_434x198_scrot](https://user-images.githubusercontent.com/6750344/42219498-03a639ea-7ec4-11e8-90d5-22bf75befafa.png)

**Comment by jaw-sh** [comment]
I'm bumping this because there's someone on my server who uses replies exclusively and it takes up a third of the vertical height of the entire chat on 1920x1080 every time he does.

There is absolutely no reason for replies to include the @ of the username, followed by a full paragraph break with paragraph margins, followed by a new block with its own margins, including the username _again_ with paragraph margins, with the avatar for some reason, and with the message finally adding more margins, broken again by more paragraph margins, followed by the actual reply.

No other chat service in the world has this because it's absolutely hideous.

Normal people replying to a message. Notice this takes up no extra space.
![image](https://user-images.githubusercontent.com/9262991/57163045-beaf7e80-6df8-11e9-8edb-da0b780d2dd9.png)

Riot
![image](https://user-images.githubusercontent.com/9262991/57163172-1352f980-6df9-11e9-97d5-af5975ccfa8e.png)


Suggested fix: remove this entirely, or use something like

```
Josh:
(In reply to crunklord420 [where you can hover over this to see the original message]): based and redpilled
```

**Comment by uhoreg** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/7159

jaw-sh's issue is different, and is probably the same as https://github.com/vector-im/riot-web/issues/7169
