### ISSUE TITLE
Can't tab complete names when typing commands

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6993]
The autocomplete just jumps to the command rather than a username.

**Comment by t3chguy** [comment]
This only applies to the force tab completion with no denote, e.g if you type `/me Trav` <kbd>TAB</tbd>

**Comment by aaronraimist** [comment]
🤔 I was just about to file the exact opposite issue...

Every time I type `/d`<kbd>tab</kbd> to get to `/devtools` it autofills some user in the room instead of the command.

![Screen Shot 2019-05-17 at 6 11 37 PM](https://user-images.githubusercontent.com/5855073/57960629-65068400-78cf-11e9-8164-21ec5c303f37.png)

**Comment by turt2live** [comment]
@aaronraimist I suspect your editor state is corrupt in that room... possibly a clear cache and reload will fix it, if not logging out and back in. It shouldn't be giving you name suggestions when typing a command,

**Comment by aaronraimist** [comment]
Hmm I don't think so. It happens in both Firefox and Safari, across multiple accounts, and persists through a clear cache. It only happens if I do it quickly, if I type `/d` and then wait a couple seconds before pressing <kbd>tab</kbd> then it works as expected.

**Comment by turt2live** [comment]
That sounds like a different issue then - mind opening that and referencing this conversation?

**Comment by jryans** [comment]
As @aaronraimist says, this appears to be fixed.
