### ISSUE TITLE
Slate issue: pasting from Gdocs pastes in bold

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#7077]

**Comment by lampholder** [comment]
We get weird HTML from Google Docs:

![image](https://user-images.githubusercontent.com/1922197/43135090-1d415e6a-8f3c-11e8-80ac-6a29c1eabcb5.png)

So that's a `<b style="font-weight:normal;">` which is very unhelpful (since we strip all/most style information in the composer).

Slate.js' example _doesn't _ suffer from this unnecessary-emboldening from Google Docs, but it also seems to miss Google Docs content that has been explicitly formatted as bold :\

This might be fiddly to fix.

**Comment by turt2live** [comment]
Note: This only applies to rich text mode

**Comment by t3chguy** [comment]
Is this still an issue for you in the new composer?

**Comment by turt2live** [comment]
> Note: This only applies to rich text mode

No.
