### ISSUE TITLE
Click-to-ping appears to be a memory hog (or there's a memory leak somewhere)

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7216]
I'm a little surprised, but clicking a person's name reliably crashed Riot for a user (aw snap). Their tab sits at 330mb and their system is otherwise not contending for resources.

**Comment by dbkr** [comment]
Details on this are that both tab completing someone's name and clicking on it to insert a pill both caused the same symptom, which was that the tab froze (we think spinning CPU) and then Aw Snapped after tens of seconds.

I suspect this is the same as https://github.com/vector-im/riot-web/issues/7105

**Comment by dbkr** [comment]
It is indeed Slate getting stuck in the same normalisation loop as #7105

**Comment by non-Jedi** [comment]
Symptoms match what I'm seeing here (tab-completion a username crashed the qutebrowser renderer process). Let me know if I can help by providing debug info.

**Comment by dbkr** [comment]
@non-Jedi if you have reliable repro steps that would be very useful - I've managed to repro it before but then doing the same thing on a new account doesn't repro the bug.

**Comment by non-Jedi** [comment]
Unable to reproduce today following exact same steps with same account as yesterday. :/

**Comment by zzottel** [comment]
Reliably reproducible here in Firefox, but not with certain steps—just use Riot Web for a few hours, and Firefox will hang. It will use more and more CPU over time, and then at some point, it's completely stuck and must be killed.

I know this is not really helpful, but it's very annoying. I have to restart Firefox several times a day due to this bug if I actually use Riot. If I don't have time for Matrix and Riot is just running in the background, it sometimes manages a day without crashing.

**Comment by zzottel** [comment]
To add something that might actually help: Not always, but very often it hangs for me when I switch rooms, especially when the room I switch to is encrypted and there's a large image to decrypt and display that Riot doesn't have in the cache yet, or when there are many user avatars to download and display.

**Comment by turt2live** [comment]
I'm confident enough that this is just https://github.com/vector-im/riot-web/issues/7105 and closing accordingly.
