### ISSUE TITLE
If you disinvite someone from a room over federation, they get a stuck invite

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7318]
* I invited `@tom:lant.uk` to a test room
* I then disinvited him
* He then has a stuck invite
* We're waiting to see if it goes away when he flushes his cache.

This is probably same as #3743 (and in turn https://github.com/matrix-org/synapse/issues/2181) but filing as separate as it's quite a different flow - not a case of rejected invites but withdrawn invites.

**Comment by lampholder** [comment]
It went away when I flushed my cache

**Comment by turt2live** [comment]
This is different from https://github.com/vector-im/riot-web/issues/3743 and requires a lot of intimate synapse knowledge to fix.

The issue in this specific case is that Synapse doesn't send the `leave` (disinvite) event to the target homeserver, so the target homeserver can't even react. When Synapse does send it, the target Synapse drops the event but otherwise passes the transaction because of "Ignoring PDU for unknown room_id" (event format lookup error). I can't really see an obvious way to fix that part, and have given up there for the time being.

I've left my code here for future onlookers: https://github.com/matrix-org/synapse/commits/travis/fix-stuck-invites

This might require some amount of spec to clarify that servers should be sending these events to targets, and that targets should expect them. I don't think we need a new API for this case.

**Comment by turt2live** [comment]
(reported as https://github.com/matrix-org/synapse/issues/4808 to synapse)

**Comment by lampholder** [comment]
Looks like we've done everything on this that we can Riot side.

I'll make a note in my todo to review https://github.com/vector-im/riot-web/labels/synapse and agitate for these issues to be addressed synapse-side. Removing from FiP for now.

**Comment by t3chguy** [comment]
Synapse fixed this recently
