### ISSUE TITLE
clicking X by room alias doesn't actually remove the alias

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#7350]
It looks like it worked, but you have to actually save?

**Comment by lampholder** [comment]
Settings manipulation paradigm fail. Combination of deferred effect and direct manipulation == confusion.

This is an infrequent enough action that I don't think fixing it should go near the top of our UX problem stackrank.

I can imagine a quick-and-dirty fix (instead of removing the alias when clicking the X, instead grey it out and put the words 'Save settings to persist this change' next to it) but that risks introducing yet more settings manipulation confusion :(

**Comment by ara4n** [comment]
honestly i’m not sure this is even a bug currently. Nothing in RoomSettings is direct manipulation; you always have to hit Save. in future we might address this by having little islands of deferred manipulation with individual save buttons in a big page of direct manipulation, but for now it’s working as intended.

**Comment by ara4n** [comment]
going to close as a dup of #3567

**Comment by richvdh** [comment]
> honestly i’m not sure this is even a bug currently. 

I'll agree it's a special-case of #3567, but I really found it super-confusing. A little help-text saying "don't forget to save" or something might help.
