### ISSUE TITLE
deleting an alias from a room's settings removes the alias from the directory, even if the alias no longer points at that room

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#7353]
... which isn't entirely riot's fault, because I don't think there is a sensible way to do this via the C-S api

**Comment by lampholder** [comment]
I don't know anything about how visibility in the room directory is managed, so I can't quite grasp the scope of this issue.

At the very least, some users are making changes in Riot which will have a very different result to the one they expected, so that's a bug.

Who is affected by this? What roles/power levels/ACLs dictate whether a user can modify a room alias' visibility in the room directory? Crucially: are people able to edit things they shouldn't, or is this just a problem if I have two Riots open, redirect `#alias:matrix.org` from `!roomA:matrix.org` to `!roomB:matrix.org` in one and then remove stale `#alias:matrix.org` from `!roomA:matrix.org` in the other?

**Comment by richvdh** [comment]
you don't need two riots open; you need for the m.room.aliases event in room A to lie about which aliases point to it (which you might achieve via a state reset, manipulation of the events outside riot, or a race of some sort when updating the settings).

This bug doesn't allow people to edit things that they wouldn't otherwise be able to. You can remove an alias from the directory on a server if you are an admin on that server, or you created the alias. It bit me because I am an admin on matrix.org: I tried to remove the #riot alias from old-#riot, but said alias was actually pointing to new-#riot, which got deleted (as we discovered after several confused users)

**Comment by ara4n** [comment]
the only soln i can see here is to lookup each and every alias in settings on load to see which spurious ones should be ignored. this feels heavy, and settings is already pretty heavy.

**Comment by richvdh** [comment]
as I said, I don't think there is a sensible way to fix this with the C-S API as it currently stands, and really it points to aliases and directories needing an overhaul.

**Comment by richvdh** [comment]
given that the room directory is now based off the the events in the room (with all the problems that entails (https://github.com/matrix-org/synapse/issues/6346, https://github.com/vector-im/riot-web/issues/12373)), I think this might be fixed now.
