### ISSUE TITLE
Adding a second widget of the same type replaces existing widget, causing data loss

### ISSUE THREAD

**Issue by colans** [vector-im/riot-web#7369]
### Description

Adding a second Etherpad widget doesn't actually add a second Etherpad widget.  Instead, it replaces the existing one.  Any data in the original is effectively lost, as there's no way to find the old URL for the pad.  (We can't count on users have a separate tab open with the URL.)

A rule in UX is *never* throw your users' work away. It's fundamental.  I'm sure this was simply an oversight, but in any case it's a serious problem.

### Steps to reproduce

1. Add an Etherpad widget.
2. Add some data to it.
3. Add a second Etherpad widget.
4. Notice that your original pad is gone, replaced by a new one.

#### App

Desktop, riot-web version: 0.16.4

#### OS

MacOS

### Proposed ideas for fixing

Either:
1. Actually open a second Etherpad widget (leaving the original untouched),
2. disallow a second one from being created, or
3. warn that creating a second one will replace the original, and cause data to be lost.

**Comment by lampholder** [comment]
Hi @colans - I haven't been able to reproduce this failure mode - unless you give the etherpad a name, the etherpad id is just the room id, so when I load two etherpads I just get two views on the _same_ etherpad (which is not wildly intuitive, but at least is non-destructive).

Are you using the standard integration manager? Are you sure you're not seeing the same etherpad instance in both widget windows? What happens if you do give one or both of the etherpads a name?

Thanks for your help!

**Comment by colans** [comment]
@lampholder I was actually posting this on behalf of someone else.  I just tried it myself, and I couldn't reproduce it either.  When I chose the same name, I got two widgets pointing to the same pad.  When I used a different name, I got a new pad.  In each case, no pad was lost.

@mkeara: Would you kindly jump in here?  I can't seem to reproduce your experience, and they're looking for more info.  Thanks!

**Comment by lampholder** [comment]
Tagging this 'cannot-reproduce' for now - please let me know if you do find a way to reproduce the issue. Thanks!

**Comment by jaywink** [comment]
Closing, has not been reproducible for almost a year.
