### ISSUE TITLE
Riot fails to start up if it can't contact the HS at load time

### ISSUE THREAD

**Issue by fladd** [vector-im/riot-web#7455]
### Description

When opening Riot (develop), I get the following error message:

![image](https://user-images.githubusercontent.com/2971539/46467928-59969a80-c7cf-11e8-9ac4-d6db9e7c1105.png)

### Steps to reproduce

- Go to https://riot.im/develop/

Describe how what happens differs from what you expected.

I expect to be able to use Riot.

Log: sent/not sent?    yes 

### Version information

- **Platform**: web (in-browser) or desktop? web 

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? Firefox 62.0.2 (64-bit)
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Windows 10
- **URL**: riot.im/develop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y

**Comment by dbkr** [comment]
Looks like this is a regression where the app fails to load if it can't contact the HS at startup time: we now check for lazy loading support on the server at startup and if this fails, the app fails to load.

**Comment by bwindels** [comment]
Thinking about how to fix this. We need to check server support before the initial sync, because sync needs to be called with the correct filter. I see two options:
 - if off-line, you must already have a persisted session for anything meaningful to be shown. Hence we assume the same LL setting as the session used previously. This will fail to detect the server starting/stopping to support LL in the mean time once connected to the HS again.
- instead of polling /sync, we poll /versions if the lazyLoadMembers was passed to the js-sdk. Feels like a bigger chance.

**Comment by kirushik** [comment]
I'm encountering this issue (or something which looks exactly the same) on packaged `riot-web` for Ubuntu, latest version `0.16.5` installed from the official repo `https://riot.im/packages/debian/`.

Clicking "Clear Storage and Sign Out" doesn't help: after logging in with the dialog on the next start I'm presenting the spinner which never finishes. After shutting down that forever-logging-in Riot and starting it again — this "Clear Storage and Sign Out" dialog presents itself.

I'll be glad to provide any necessary logs and debug info. So far it is not possible to use Riot on my machine.
