### ISSUE TITLE
Using some localized symbols is not availble

### ISSUE THREAD

**Issue by BrotherWarrior** [vector-im/riot-web#7515]
### Description

We are from Russia and use ldap integration, that's why we need to enter localized symbols for searching members . When we try to open search members dialog for invite users to community, room, or just start private chat we can't use letter 'б' or capital 'Б'. This character not displayed in every search members dialogs. We can send this letter in chats without problems.

### Steps to reproduce

* Open riot web or desktop
* Click on 'Start chat'
* In search dialog try to enter somthing that containt symbol 'б' or 'Б'
* Symbol is not displayed
* Symbol not passed to search pattern

Describe how what happens differs from what you expected.
* Symbol whould be displayed and passed in search pattern to server

 

### Version information

- **Platform**: web (in-browser) and desktop any version (tested since 0.16.3+)

For the web app:

- **Browser**: Chrome any version
- **OS**: Windows, macOS tested
- **URL**: private hosting. Tested since 0.16.3+

For the desktop app:

- **OS**: Windows, macOS
- **Version**: 0.16.3+

**Comment by lampholder** [comment]
Dup of https://github.com/vector-im/riot-web/issues/4523 (and closed dups https://github.com/vector-im/riot-web/issues/7246 and https://github.com/vector-im/riot-web/issues/6789).

I'm going to bump the severity on #4523 to `major` (since it does have a pretty dramatic impact on usability if you need to find a user by searching on б) and close this as a dup.
