### ISSUE TITLE
Japanese input doesn't work well in composer

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7630]
[craigmyster reported the issue on #riot](https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1540889805194590wbTnD:matrix.org?via=matrix.org&via=chat.weho.st&via=disroot.org&via=maunium.net):
> anyone else having issues with multi byte characters typing on windows riot?  we use it heavily in our organization but the IME typing of japanese characters has been rather unusable for the last 2 weeks (not sure if it was a windows update or riot update)

I verified, after setting up a japanese keyboard (I used kana kanji variant/hiragana input method) under Gnome 3.28, typing "hello" on https://www.slatejs.org/#/rich-text yields ”へぉ", while in the riot.im/develop composer I see things appearing and disappearing but after having typed "hello" completely, the composer is empty. I don't know any japanese but that doesn't seem right.

**Comment by turt2live** [comment]
I think this might be the same issue as https://github.com/vector-im/riot-web/issues/7535 just with a different language.

**Comment by RickCogley** [comment]
Hello @bwindels, I was just talking to Rick (@rxl881) over on matrix/riot.im and he asked me to point out what I had found. I can corroborate that I'm seeing input anomalies entering Japanese on latest macOS Safari. 

Using either the ever-popular ATOK IME or, the built-in macOS IME, when I try entering Japanese what I expect does not get entered at all. Depending on what I type, I can sometimes see the list that you usually see but, the characters just look jumbled in most cases. If I _do_ get an entry that actually looks correct, and use arrow keys and Enter to "fix" it to the textarea, I get nothing. It just returns spaces. 

In the below screenshot, taken while entering Nihon in here, you can see after I switch to ATOK and type nihon, it gives me the most typical solution 日本 ready to be entered. I can use the arrows to select others, even unicode emoji. ATOK has a nice dictionary function as well, where the definition pops out to the right. This is great because there are a lot of homonyms in Japanese. 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/512328/48259265-cbab7080-e45a-11e8-89c7-6eb8eac776ff.png">

But in riot.im, when I enter nihon, it kind of appears backwards and selecting it does nothing. ﻿Hopefully it's visible here: 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/512328/48259420-39f03300-e45b-11e8-9409-8d72523a5eac.png">

**Comment by RickCogley** [comment]
Yeah, it's entering right to left. 

n
i い
h
o お
n

**Comment by RickCogley** [comment]
Today I tested again in riot.im, and now I can enter Japanese correctly. Something got fixed?

**Comment by RickCogley** [comment]
Oops, I spoke too soon. This does _not_ work in latest macOS Safari (Version 12.0.1 (14606.2.104.1.1)) but, does work in latest macOS Firefox (Quantum 63.0.1 (64-bit)). The other day, I must have tested in Safari... Sorry for the confusion.

**Comment by RickCogley** [comment]
Also works ok in Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by craigmyster** [comment]
very much still having this issue.
if I type slow then i can type the Japanese but the cursor goes to the begging of the input and i can't type enter.  Going to a different chat window and coming back it disapears.

Windows 10 recent Build
matrix-react-sdk version: <local>
riot-web version: 1.0.8
olm version: 3.0.0

Issue happens with all team members only on Windows Client
