### ISSUE TITLE
Feature: Private Contact Discovery (discovery without servers learning your contacts list)

### ISSUE THREAD

**Issue by ajvsol** [vector-im/riot-web#7649]
[Private Contact Discovery](https://signal.org/blog/private-contact-discovery/) is a feature implemented by Signal which allows you to discover your social graph without revealing your contacts to any server. This is one of the bigger metadata leaks and helps prevent that privacy issue where your contact info is up for grabs to any server which any of your contacts use.

**Comment by ara4n** [comment]
We rebuilt our contact discovery process as part of the work outlined in https://matrix.org/blog/2019/06/30/tightening-up-privacy-in-matrix/  - specifically https://github.com/matrix-org/matrix-doc/pull/2134, which is in turn implemented by matrix-org/matrix-js-sdk#1021
and matrix-org/synapse#5897 and matrix-org/sydent#197 and matrix-org/sydent#184.

We have no plans to implement trustzone / SGX style private contact discovery, not least due to concerns over SGX's trust model.

**Comment by mulles** [comment]
Maybe this is the solution for decentralized IM Services to scale: 

Mobile Private Contact Discovery at Scale by Daniel Kales (TU Graz), Christian Rechberger (TU Graz), Thomas Schneider (TU Darmstadt), Matthias Senker (TU Darmstadt), and Christian Weinert (TU Darmstadt) in 28. USENIX Security Symposium (USENIX Security'19). Paper available on ePrint.

POC: https://github.com/contact-discovery/mobile_psi_android

I didn't have a deep read into it, but it seems aligned with the way matrix does things, seems future proof for web3 and still  works on current web :) 

Please guide me should I bring up this idea in a different existing issue or create a new one!
