### ISSUE TITLE
Should be able to specify public/private room (preset?) when creating a room

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7684]
When creating a room, I forget nearly everytime to make the room publically joinable. I usually share around the alias before looking rather stupid when nobody can join.

For the sake of stupid, the option to be able to set a room public or private in the create room dialog would be helpful,  *ideally* requiring you to select an option to continue.

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/5599

**Comment by lampholder** [comment]
Since the redesign has moved the 'create room/start chat' UX to a (+) next to the roomlist header, there's a chance we could pick some very sensible defaults depending on whether somebody is trying to create a 1:1, room, or 'group'.

But yes, I'd like to see this decision somehow incorporated into our create room flow.

**Comment by Half-Shot** [comment]
![image](https://user-images.githubusercontent.com/2072976/73689195-9a553b00-46c5-11ea-8b79-b4bff0bb82e0.png)

Gorgeous, this is done.
