### ISSUE TITLE
Jitsi concerns

### ISSUE THREAD

**Issue by uppps** [vector-im/riot-web#7711]
Riot conferencing has been moved to Jitsi and it is using your Jitsi server by default (jitsi.riot.im) not giving the ability to change to my own server. If I run my own Matrix server is to have total control over my data. Also, I suppose that because it's a Widged it's not part of the official Matrix spec so other clients will not be able to use it. What happens if two clients use different Jitsi servers? They can't communicate? Why not develop your own conference system completely integrated in Matrix spec?
@ara4n 
@dbkr 
@lampholder 
@turt2live

**Comment by t3chguy** [comment]
The client will use the jitsi in the widget state event, which will depend on which client made that event.

**Comment by uppps** [comment]
@t3chguy And what Jitsi server will be used?

**Comment by t3chguy** [comment]
The one that the client which made the state event wishes

**Comment by t3chguy** [comment]
(the one which started the conference)

**Comment by Half-Shot** [comment]
The Jitsi server used *by default* is `jitsi.riot.im` but if you want to host your own server, you just have to host your own integration manager too. https://github.com/turt2live/matrix-dimension is something you can use to self-host integrations and run your own installation of Jitsi on. You will also need to host your own Riot instance too and configure it to use dimension.

As @t3chguy stated, any conference you start (or any users you have running your riot/integration manager instance) will use that server and users can join into that. The reason that matrix.org hasn't yet got a spec for a conferencing system is that they are *quite hard* to write and not really the objective of the platform. It's simply been easier to adopt an existing system, which is entirely self host-able. 

Funnily enough, the *old* freeswitch system was much more of a problem because the addresses were hardcoded into the app but now you are free to run your own stack of widgets and with that, your own Jitsi instance.

**Comment by lampholder** [comment]
@uppps thanks for your question - your concern is understandable but hopefully @Half-Shot's response has explained the situation clearly.

I'm going to leave this issue open (and flag it as `wontfix`) because I think it's a useful one for people to be able to find/reference.

**Comment by ara4n** [comment]
this bug seems to be causing more confusion than it solves (see the backlink above). We support custom jitsis already (Dimension does so); we need to support hooking the video call button up to it, which is https://github.com/vector-im/riot-web/issues/6930. We don’t have plans to replace jitsi, which works pretty well these days - which is why this was marked wontfix in the first place.

so, before anyone else takes the wontfix out of context, i’m closing this.

**Comment by turt2live** [comment]
with my Dimension hat on: You can also force the call button in Riot to use your custom Jitsi by turning on the toggle for "use this domain as the default conference domain" (the same place where you'd configure your jitsi server). 

The toggle forces the widget added to the room to use the configured jitsi server rather than the one implied by the widget. Although this isn't compatible with the mobile Riot apps, it does work for desktop/web.
