### ISSUE TITLE
UtD, persistent OLM.UNKNOWN_MESSAGE_INDEX errors

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7714]
I'm seeing Unable to decrypt: Error: OLM.UNKNOWN_MESSAGE_INDEX from @nadonomy 's new phone :(

**Comment by lampholder** [comment]
This is very likely the same olm session wedge problem we've seen elsewhere (triggered by restoring a phone from backup).

There's a fix for riot web (currently on /develop), and it will be addressed in iOS and Android. Until then, I _believe_ this can be fixed by (probably either you or Nad) exporting your keys, logging out, logging in and re-importing the keys. That way you'll have a brand new 'device' (from a Riot encryption perspective anyway) which will force a new, unbroken encryption session.

**Comment by Half-Shot** [comment]
I've not seen this in a long time, can I close it?

**Comment by turt2live** [comment]
/me defers to @lampholder and his UISI tracking plan

**Comment by lampholder** [comment]
I think we can close this - I'll follow up with @manuroe to check this fix also landed on mobile

**Comment by uhoreg** [comment]
Looking through the rageshake, this looks like another instance of https://github.com/vector-im/riot-web/issues/8793, which should be fixed now
