### ISSUE TITLE
QUESTION: How does (video) calling currently get routed?

### ISSUE THREAD

**Issue by Julian2000nl** [vector-im/riot-web#7746]
I've looked this up but didn't get an answer as every answer seemed different from one another.
Let's say I have a homeserver, and my friend has a homeserver, we both use Riot and place a call. Does this call get routed through our homeservers or is this placed via the matrix.org server(even though we both don't use it). And how important is the installation of our own TURN server, I don't see a lot of guides including TURN and from what I can see Riot uses the Jitsi protocol. 

Are calls truly Peer-to-peer?

**Comment by t3chguy** [comment]
- 1:1 calls (exactly two users in the room) are peer to peer optionally going through the configured turn servers if a peer to peer connection cannot be formed due to nat/cgnat/firewalls/etc. Jitsi is used if not exactly two participants and will go through a jitsi videobridge server, which depends on the integrations server being used.
