### ISSUE TITLE
Switch to yarn

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7756]
to save the symlinks to the react-sdk and js-sdk that npm hates so much

**Comment by aaronraimist** [comment]
`@MattFellows:matrix.org` had also asked about switching to pnpm but I haven't tried that

https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$15433242401368966mEztG:matrix.org?via=matrix.org&via=t2bot.io&via=riot.tenx.tech&via=lant.uk

**Comment by MattFellows** [comment]
To be clear, with `pnpm` everything in node_modules becomes a symlink (or hardlink), so it may not solve the issue if people have problems with symlinks in general...  I've used it `[pnpm]` on MacOS and Windows machines with no issues, but I tend to be the only user on my machines and don't often run into permissions / ownership problems.   

I'll try out the build process as soon as I find a spare few minutes, using `pnpm` instead of `npm` and see if it at least works, then offer up some timings / findings on `yarn` vs `pnpm` and see what others think...

**Comment by jryans** [comment]
@aaronraimist and I are both having a good experience with Yarn while working on Riot so far.

Along with the key improvement of preserving the symlinks, it's also around twice as fast than npm:

```
$ rm -rf node_modules/
$ time yarn install
real	0m17.682s
user	0m12.489s
sys	0m23.458s

$ rm -rf node_modules/
$ time npm install
real	0m31.418s
user	0m42.215s
sys	1m16.561s
```

**Comment by ara4n** [comment]
i'm not aware of any reason why we shouldn't switch :)

**Comment by jryans** [comment]
JS SDK converted in https://github.com/matrix-org/matrix-js-sdk/pull/856. React SDK and Riot are in progress.

**Comment by jryans** [comment]
React SDK converted in https://github.com/matrix-org/matrix-react-sdk/pull/2773. Riot Web converted https://github.com/vector-im/riot-web/pull/9132.

All repos now have Yarn lock files and updated docs for the Yarn workflow. 🎉
