### ISSUE TITLE
Port/merge grid view to experimental

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7836]

**Comment by bwindels** [comment]
Got the branch rebased and working, now we need to decide whether it's good enough to go on experimental...

**Comment by ara4n** [comment]
So, I spoke to tom about the UX of this today. Thoughts included:
 * Expecting people to define communities for this is far from ideal (at least with the current communities UI).
 * We could mark rooms as 'pinned' in order to incrementally build up dashboards, but it doesn't help with presetting them.
 * We could improve the communities definition UI so it doesn't feel so clunky to define a community which is also a screen layout.
 * We could store them as presets jumbled up with other LLP things like custom tags?
 * We desperately need input from @nadonomy on how to land this coherently :)

**Comment by jryans** [comment]
Merged in https://github.com/matrix-org/matrix-react-sdk/pull/2348, but then later reverted. I assume a separate issue will track the future of this...?
