### ISSUE TITLE
e2e key backup takes forever

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7863]
I've been here for about 5 minutes and it still isn't done. A progress bar might help to show that the thing isn't dead?

**Comment by turt2live** [comment]
or run it async and tell me that it failed/succeeded later. It's not fun not being able to use riot for this long

**Comment by jryans** [comment]
I asked @turt2live to run a small script that logs the number of group sessions in the crypto store (assuming that a large number would be the main thing to cause backup to take a long time). His device has approximately 3x the number of group sessions that I am seeing, and for me backup is pretty fast, so it doesn't seem to explain the whole story here.

I suspect this might have become much faster after this issue opened: a few days after this issue was filed, we [changed](https://github.com/matrix-org/matrix-js-sdk/commit/c48a6c060146d04967f4dd8a9997d1211deca285) the keys sent per upload request from 10 to 200 (a 20x change). It's possible this greatly improved the key upload experience.

I have asked @turt2live to try again when he has time available.

**Comment by jryans** [comment]
@turt2live is still seeing delays of 5 - 10 minutes to create a key backup. Even if we can improve, I think we still want an async flow that uploads in the background.

**Comment by jryans** [comment]
Related: https://github.com/vector-im/riot-web/issues/8047

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2416 and https://github.com/matrix-org/matrix-js-sdk/pull/820.

**Comment by jryans** [comment]
I filed https://github.com/matrix-org/synapse/issues/4395 to investigate any related performance issues in Synapse.
