### ISSUE TITLE
Letters on the left of a message can be slightly trimmed when italicized

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7916]
Note the `g` in the following image: ![](https://i.imgur.com/UGtW6jM.png)

**Comment by yannicka** [comment]
Do you still have the problem?

I can't reproduce it:
![image](https://user-images.githubusercontent.com/22885898/82260923-6b09c780-995e-11ea-857d-958b11d875b8.png)

The font used on my side is Nunito (and I'm on Firefox on Linux):
![image](https://user-images.githubusercontent.com/22885898/82261239-f8e5b280-995e-11ea-98b8-035218e41ae8.png)

So if the default font has changed, maybe the problem is solved?

**Comment by t3chguy** [comment]
Assuming fixed
