### ISSUE TITLE
.well-known error is not helpful to non-expert users

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7925]
We shouldn't expect all of our users to understand **Invalid homeserver discovery response**.

![image](https://user-images.githubusercontent.com/1922197/50279959-1ef1e500-0443-11e9-855e-044bc0ece2fe.png)

Let's not worry about fixing this for now, but make sure that our redesigned login screen can accommodate useful feedback for non-expert users. @nadonomy

**Comment by dkasak** [comment]
Where can I find more background information for this error? I have a user that stumbled upon it.

**Comment by chresan** [comment]
So I just installed the latest riot on a new computer (win16, riot 64-bit) and ran into this problem. I am unable to login. Using custom server settings does not work. My homeserver implements the .well-known for matrix. 
(1) Login is not possible with the riot-desktop version!
(2) There is no way to exit the login dialog other than killing riot in the task manager and starting it again.
(I wanted to update the riot desktop version for some of my homeserver users and I am glad I didn't because they might not be able to login anymore)
Hope this gets fixed soon.

**Comment by jryans** [comment]
This issue is about the error message being unhelpful, while @chresan is describing being unable to login, which is a separate problem to investigate. I created #8428 for @chresan's issue.
