### ISSUE TITLE
Reset password on custom server does not allow changing the HS/IS urls

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#7940]
### Description
Unable to update custom server boxes on password reset page.

### Steps to reproduce
If you go to the reset password page, then select custom servers:
![reset-email-1](https://user-images.githubusercontent.com/1917473/50341172-c0e20200-0515-11e9-8388-4a49875e4e91.png)

You then try to click and change the box, and it snaps back to hiding the custom server section:
![reset-2](https://user-images.githubusercontent.com/1917473/50341171-c0496b80-0515-11e9-9d16-3817a037f507.png)

If you have the custom section open in the sign in then click reset password:
![reset-3](https://user-images.githubusercontent.com/1917473/50341170-c0496b80-0515-11e9-9423-8e39c91b29cb.png)

Anything typed in the boxes is automatically overwritten by the javascript

I would expect either some visual indication that you cannot update that URL on that page (greyed-out input boxes?) or that that page works the same as the others, and you're able to update the URLs.

Probably not that vital as you have to thread a narrow set of actions to reach that point, and there is a workaround (move back to the login page, update the URL, move forward to the reset password page)

### Version information

riot.im/app, using firefox 64.0 on linux.

**Comment by lampholder** [comment]
I guess this might have been impacted by .well-known

It's hard to know how to prioritise this, since it won't affect most users. Modular users using their own riot instance will be fine, matrix.org users using riot.im/whatever will be fine. People using their own homeservers won't often find themselves needing to reset their password, and the login/registration/password reset UX should all get some attention in the redesign so it won't be like this for long.

However, leaving _any_ login/registration/account recovery path broken feels like very bad news.

@turt2live do you have a perspective on how easy this would be to fix?

**Comment by turt2live** [comment]
It's probably medium difficulty to fix and high amounts of frustration.

**Comment by turt2live** [comment]
Fixed
