### ISSUE TITLE
redesign: italics aren't italic enough on nunito

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7961]

**Comment by lampholder** [comment]
They're barely perceptible imo - do we have a solution to this? Do they ship a slantier italics?

**Comment by turt2live** [comment]
![image](https://user-images.githubusercontent.com/1190097/50728676-ee6ca500-10ea-11e9-9ebb-d318d595fbff.png)

For perspective on just how bad this is: which word is italicized? (spoilers: it's 'not').

**Comment by ara4n** [comment]
this is https://github.com/google/fonts/issues/1726

**Comment by ara4n** [comment]
there doesn't look to be a solution short of using a different font entirely for italics, which is very bad karma. this might be the excuse @nadonomy has been looking for to try Inter UI. (but I still really like Nunito :( )

**Comment by nadonomy** [comment]
I think we're just hitting more artefacts of it being a display typeface (designed for large sizes rather than body text).

I love the legibility of [Inter UI](https://rsms.me/inter/) and we're well aligned with its goals as a project. That said, I'll can also browse for alternatives that are aesthetically more in line with Nunito.

**Comment by ara4n** [comment]
bodged it for now with https://github.com/matrix-org/matrix-react-sdk/commit/1082f548d3666aa23f1130df17dac2273a50066a.

i'm still concerned that Inter UI is too sharp and unfriendly relative to Nunito, although happy to give it as an option.
