### ISSUE TITLE
Confusing (+) button to add chats/rooms

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#7963]
I find the juxtaposition of unread messages in the circles, with the new button to add rooms very confusing. Even without unread messages, out of the corner of my eye, those pluses grab my attention, and I think it would be better to either move them before the tag label, or use another UI element, so that there's better distinction from the unread message labels.

![screenshot_2018-12-28 riot 1](https://user-images.githubusercontent.com/195073/50519144-d3ca7880-0ab9-11e9-884e-b9ebae4cc673.png)

**Comment by bwindels** [comment]
Makes sense, will change it to something like:
![image](https://user-images.githubusercontent.com/274386/50770046-cd888900-127d-11e9-81ff-92a31459d584.png)

**Comment by madduck** [comment]
That's still pretty close. How hard would it be to impose the counter over the Avatar, like is done on most other UIs? Or to put the (+) on the left side?

**Comment by nadonomy** [comment]
Hey @madduck— thanks for the input/suggestions so far!

It's not technically hard— but rather than implementing every individual design suggestion we get (of which I'm sure you can appreciate there's many, of varying levels of subjectivity!) we'd prefer to validate changes holistically, in chorus with the rest of the UI and its various states, rather than action each one piecemeal.

We plan on iterating on a few room list related issues in the near future and I'll keep the suggestions in mind for then.

**Comment by nadonomy** [comment]
P.S. The changes in the comp @bwindels posted should relieve some of the 'corner of the eye' glanceability failures of the previous design, the change is light so should make it in soon.

**Comment by turt2live** [comment]
The new room list has a very grey + sign (no circle), with badges being blatantly obvious. If it continues to be a problem, please open a new issue (referencing this one).
