### ISSUE TITLE
Signed out by server after a migration

### ISSUE THREAD

**Issue by tleydxdy** [vector-im/riot-web#7975]
### Description

riot logged my out after I had trouble migrating synapse. 
what got logged out:
my laptop (riot-web) and my phone (android) I was using them to test the migration for the entire process, at first they can't connect, because I miss-configured PostgreSQL, fixing that and they connected but told me I was logged out. 
my old laptop. I tried to connect with a old laptop (after backing up firefox's profile) to my now working synapse, it got logged out too. 

### Steps to reproduce

- migrate synapse install to another server, by coping /etc/matrix-synapse, the media folder, and the postgresql dump over
- forgot to enable peer auth for psql's unix socket, so for a while synapse wasn't able to use the database. 
- fix it, drop the database, recovering it from the dump again
- opened riot and get logged out. 

I have send the logs via the riot client. 

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: FIrefox
- **OS**: Arch
- **URL**: riot.im/app

**Comment by lampholder** [comment]
This is weird, but a fairly niche edge case.

I'm about to migrate my homeserver sometime in the next few weeks - I'll see if I have similar troubles.

**Comment by ara4n** [comment]
unfortunately this is fairly expected; if the homeserver runs against a database which doesn't know about your access_token it will send a 403 back to the client, which the client will interpret as a panic and log you out (and delete you e2e keys if you don't have incremental backup happening).

We could improve this once [MSC1466](https://github.com/matrix-org/matrix-doc/pull/1466) lands we might be able to have the server issue a soft-logout rather than hard-logout if it gets an access_token for a user it simply doesn't know about.

**Comment by tleydxdy** [comment]
it was running with the old database so the tokens should be there. it now looks like a synapse 0.34.1 bug, it just happened when I migrate. so don't upgrade folks.
