### ISSUE TITLE
Room upgrades: Continuation icon broken on dark theme

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#7990]
### Description

The icon for room continuation looks fine on light theme:

![image](https://user-images.githubusercontent.com/1342360/50640597-2a9cdb80-0f1a-11e9-8918-3b36706f044d.png)

But broken on dark theme:

![image](https://user-images.githubusercontent.com/1342360/50640571-19ec6580-0f1a-11e9-8694-4cb4a68aa414.png)

### Steps to reproduce

- Create room
- Upgrade room version
- Join new room
- See broken icon on dark theme

### Version information

- **Platform**: desktop

- **OS**: Debian Linux
- **Version**: 0.17.8

Ask if you need a room to test on.

**Comment by turt2live** [comment]
@lampholder with the dark theme disappearing so soon due to experimental, is it worth trying to fix this?

**Comment by turt2live** [comment]
@lampholder if it is worth fixing, I'll also want to know what the fix should be. Changing the background of the whole thing is easy, but may affect other parts of the app. Changing the icon is also an option, but I'm crap at color choices.

**Comment by bwindels** [comment]
we've been implementing theme-compatible icons by using svg's with `mask` instead of `background-property` and then set the background to a color defined in the theme. We do have https://github.com/vector-im/riot-web/issues/7578 in the backlog to fix these kinds of things, but it's good to explicitly mention this :) So I'd say we can leave it for the mentioned task.

**Comment by turt2live** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2737
