### ISSUE TITLE
Option to minimize widgets by default everywhere

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8039]
I find them a bit intrusive and normally minimize them manually anyways. Would be nice to have them be collapsed by default in rooms.

**Comment by lampholder** [comment]
This suggests a bigger problem with them (why are they defaulting to maximised if that's not useful to everyone? Is it because we're not confident people would notice them in their minimised form? Is that something we could tackle?)

This might be okay as a short term sticking plaster, though it would probably end up being Yet Another option in user settings :\

**Comment by turt2live** [comment]
The larger issue is the widget takes a third of my screen, is much more visible than the timeline, flashes a lot while loading (on the dark theme), and doesn't finish loading until well after the room has been opened.

Starting widgets minimized fixes a lot of those issues while still keeping their usefulness.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/12921
