### ISSUE TITLE
Read receipt sent if you have the room open

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8041]
/develop (and therefore /app) used to require some sort of interaction with the client before a read receipt would be sent, such as mouse movement or typing. /experimental doesn't appear to have this check and simply sends a read receipt if you so much as have the room open.

This is problematic for people who leave a room open their laptop and try to use riot on their desktop - they just miss messages for that room. Not to mention it also gives the impression that someone has read your message when in fact they haven't.

**Comment by spantaleev** [comment]
If this is not a release-blocker, I don't know what is.

It's especially problematic on Linux (due to the frequent use of desktopworkspaces). You'd leave Riot open (even unfocused) on some workspace and it would mark everything as read immediately..

With that:

- you don't even really get notifications on your phone (you get them, but they disappear right away.. so unless you're vigilant, you effectively don't get them)
- you can't notice the try icon showing activity, because you've "seen it all"
- you can't notice the title bar showing activity, because you've "seen it all"

**Comment by aaronraimist** [comment]
I assume this was broken by https://github.com/matrix-org/matrix-react-sdk/pull/2345

**Comment by skylord123** [comment]
My wife is actually really bothered by this. If she leaves the app open on her phone but it goes to lockscreen (so she isn't using it anymore) then goes to use it on the computer (and I message her) it will mark messages as read before she even opens the app on the computer. This leads to her not always getting my messages because the app in the task bar isn't showing that there is a message. It seems if she closes the riot app on her phone before locking it this does not happen.

This started happening after the recent update (that changes how the UI looks). This is quite an annoying bug.

**Comment by lampholder** [comment]
related: https://github.com/vector-im/riot-web/issues/9023

And fixed.

**Comment by jryans** [comment]
#9023 does change some of the behaviour in this area, but I am not sure if it resolves all of the similar but not identical issues that were historically duplicated here.

At this point, I would recommend opening fresh issues if you are still seeing this behave differently from your expectations on develop.
