### ISSUE TITLE
Room list is hard to use on small screens

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8042]
For the last ~week I've been trying to shake the feeling of my room list missing rooms, and can't seem to get over the feeling. My main display for Riot is only 1080p, which means a relatively large chunk of the room list is taken up by the gradients. It'd be nice if these were a lot more subtle to give preference to showing more rooms.

This is particularly bad on my laptop (which admittedly does have a crap resolution, but there's not much I can do about that):
![image](https://user-images.githubusercontent.com/1190097/50792138-37eef880-1281-11e9-97a7-9679e8cb5f8f.png)

It feels as though my invites, favourites, and recent rooms are disabled/inaccessible. This is the default layout for the sections, with the exception of being a bit narrower to maximize timeline space.

**Comment by jryans** [comment]
The gradient feels especially strange on the invites section (since it only appears as needed when there are invites to show). Perhaps that's a separate issue from the gradients more generally, though.

**Comment by ara4n** [comment]
I have the opposite problem. in the screenshot below, the gradient is so small it's almost invisible and i  found myself staring stupidly at the list wondering where all the rooms had gone:

<img width="415" alt="screenshot 2019-01-20 at 14 27 49" src="https://user-images.githubusercontent.com/1294269/51440532-274a7380-1cc0-11e9-85fd-8378c9f5190b.png">

the grad was originally 40px;  then got reduced 30px on Dec 18; i've just bumped it up to 35px to see how people react in efcfaed335bc66ceb6487f766bf832f667048b40

**Comment by turt2live** [comment]
tbh it's no better or worse for me after efcfaed335bc66ceb6487f766bf832f667048b40

**Comment by ara4n** [comment]
i agree the improvement is marginal. it may need a different tween function to be punchier rather than just changing the height.

<img width="409" alt="screenshot 2019-01-20 at 20 52 45" src="https://user-images.githubusercontent.com/1294269/51444864-7363db00-1cf5-11e9-9165-2fe48819c27f.png">

**Comment by turt2live** [comment]
This is still an issue - have generalized the title given the gradient is much different from when it was first opened.

**Comment by ara4n** [comment]
so, the changes to remove the bottom gradient improved this considerably for me.
Can you articulate how it's still jarring for you?

**Comment by turt2live** [comment]
The discussion in #riot-design mostly reminds me of just how little I can see/use of my room list on my laptop. I usually end up having to minimize all the tags except the one I want to look at in that second, which still takes up a quarter of the screen.

I also find myself clicking tag headers to expand/collapse them more often than scanning the room list for unread rooms (I intentionally have all my rooms set to 'mentions only'), making my experience feel less productive.

**Comment by ara4n** [comment]
what is the actual vertical height of the laptop? and to check: we're not talking about custom tags here?

I'm wondering how this ever worked before at this vertical height - did you just scroll through the whole list (truncated to 10 rooms per sublist) every time you wanted to check for activity?

**Comment by turt2live** [comment]
1366x768 (making roughly 600px available to the viewport, because Chrome). This is without custom tags.

I had a similar but different problem before because of the different room list behaviour: due to all the custom tags, the room list couldn't possibly fit, forcing the list to be a giant scrollable panel. This was preferred because I could scroll down and leave the window at the couple tags I cared about at the moment. When disabling custom tags, the room list was relatively unusable for similar reasons currently on develop (headers filling the viewport).

**Comment by turt2live** [comment]
I'm not sure this makes any sense 2 years later, but https://github.com/vector-im/riot-web/issues/3824 is a thing where I tried to describe wanting a settings flag for that fully-scrollable panel to always be shown.

**Comment by ara4n** [comment]
AH! so on the old design, it flips into "one big scrollable list" if there's not enough room for custom headers? That explains why folks have been able to use it with so many custom tags. Presumably it still truncated the sublists to 10 rooms by default?

Would your use case be solved then by having a great-big-list mode in the roomlist then, and having to constantly scroll between favs, DMs, rooms etc?

**Comment by turt2live** [comment]
yes, yes, and yes :D

**Comment by mvgorcum** [comment]
Yes, that's basically how I currently use the room list.

**Comment by michaelkaye** [comment]
I showed the design to leo last night, his only and immediate feedback was that he couldn't use it on his primary development laptop (a thinkpad x220) - more than half the vertical height in the sidebar is taken up by non-functional UI, leaving a few hundred pixels for the 8 room names that ended up being visible.

**Comment by HansJK** [comment]
When I compare how I use Riot to Discord or Slack, the main differences I find hard to get over is the focus on rooms instead of organisations/communities/servers. On Riot it's nearly impossible to keep up with all the rooms, because they all get buried under each other. They are also always moving. When using Slack and Discord, I have all the channels organised within servers and organisations. This way I can stay up to date with the ones that I care about. And because the channels are organised within their own communities, they don't all end up being in one place stacked on top of each other.

**Comment by mvgorcum** [comment]
I have given the new design some time, and while I still like a *lot* about the new design, I still notice that there is a very large amount of rooms that I used to be able to casually read/talk in, that I just never open anymore, because they just don't really show up.

A positive is that this means I use riot a bit more deliberately, since finding rooms I actively seek out is easy enough, but this design change really changed how I use riot.

The advantage of the old way, from my perspective, is that riot naturally focused on the room tags that I wanted to look at while scrolling, because it automatically 'collapsed'  the tags that I wasn't currently looking at.

**Comment by OtherSystems** [comment]
The organisation in communities/servers seems to be indeed still a big plus slack has over matrix. Before the last big release the channels where easier to manage on smaller resolution screens (x230 with 1368x768 resolution), but now I can't find anything any more, my browser will tell me there is a message for me waiting but it's a pita to find it. 

Would really like to see community based organising of rooms but also more efficient space of screen-space, or friendly towards lower resolutions/smaller screens.

Thanks!

**Comment by bwindels** [comment]
this should be fixed once we work on communities

**Comment by edrex** [comment]
@ara4n @turt2live IMO having a single scrollbar for the sidebar is much better usability wise, because:
1. as  @mvgorcum mentioned, it avoids the need to collapse/expand to get full sublists visible
2. the sublists present a small scroll target which in my experience leads to wrong-target errors with wheel and touch scrolling
3. sub-sub-sub-sub-spaces (sublist-panel-window-screen-reality) are pretty confusing for our savanah-adapted spatial brains.

![Screencast](https://user-images.githubusercontent.com/14615/58351283-33d10b00-7e1d-11e9-951e-7cb88d77e83e.gif)
(recorded with [Dark Reader](recorded with Dark Mode))

**Comment by edrex** [comment]
(my laptop has a 13" 16:9 UHD screen and that's at 100% zoom)

**Comment by edrex** [comment]
I think also for those of us not Matrix engineers, we don't think so much in terms of the sublists, but more spatially as "there is a room near the bottom that I want to view".

**Comment by ieure** [comment]
Just throwing in here that I also have issues with the room list.  My primary laptop is a ThinkPad X230, which has a 1366x768 display, but even on larger displays I find the individually-scrolling panels and jumping around of room list ordering to be a major usability hurdle.

A recent version seems to have added *another* panel of recently-used rooms, except this is horizontally scrolling (ugh).  It reduces the vertical space for the room list even more, so my groups can only display 1-3 in the list.

I wish:

 - The order was stable, or at least there was a preference to toggle between recently-active and alphabetic ordering.
 - The entire panel scrolled, instead of having multiple (four, in my case) scrolling subsections.

**Comment by jryans** [comment]
> A recent version seems to have added _another_ panel of recently-used rooms, except this is horizontally scrolling (ugh). It reduces the vertical space for the room list even more, so my groups can only display 1-3 in the list.

This new feature can be controlled with the setting at Settings -> Preferences -> Room list -> Show recently visited rooms above the room list.

**Comment by mvgorcum** [comment]
> this should be fixed once we work on communities

While I think work on communities can certainly improve the situation, I presonally would still prefer the old single-scrolling behaviour that the old design has. After using the new design since februari (~6 months) I unfortunately still miss the old behaviour of the roomlist and I still find it much harder to engage with the large amount of rooms I'm in.

**Comment by ara4n** [comment]
> While I think work on communities can certainly improve the situation, I presonally would still prefer the old single-scrolling behaviour that the old design has.

the new design for communities brings back the single-scrolling behaviour, given the expectation is that people will use communities to make the size of the list more navigable.

**Comment by edrex** [comment]
@ara4n is there a target release for the new design or is it already launched?

**Comment by HansJK** [comment]
> the new design for communities brings back the single-scrolling behaviour, given the expectation is that people will use communities to make the size of the list more navigable.

Hope communities included powerful moderation tools like we have on Discord. It's a must on large communities.

**Comment by turt2live** [comment]
Please let's keep this issue in topic about the room list and move communities discussion elsewhere.

**Comment by HansJK** [comment]
Although I might of gone off track a little bit, sorry about that. I think the community feature is what will solve this issue.

**Comment by phoerious** [comment]
I'd like to add that this is not only a problem for people with small screens. I have very large 4k and WQHD screens and I prefer to have the window in one corner. Maximising it at that resolution makes no sense and for using it, I don't need (or want) a window that is larger than approximately what a low-end laptop screen would give you.

Having four or five individual tiny scroll areas is very tedious to use and I have no idea what channels are open at all times, because half of them are hidden behind multiple scrollbars. Even if I add all of them to my favorites and then collapse the other areas, I still have their headers consuming an awful amount of space, which is just dead screen space therefore.

**Comment by OtherSystems** [comment]
> Although I might of gone off track a little bit, sorry about that. I think the community feature is what will solve this issue.

Except for people in lots of separate rooms. Most rooms I'm in, the room is the community.

**Comment by turt2live** [comment]
Disclaimer: I haven't read 99% of the conversation here before leaving this comment.

I think this is fixed in the 2020 room list. With scrollable panels and having used it in a super tiny viewport (400px high) it's not too bad. We also don't have stacked headers anymore.

**Comment by jerrykan** [comment]
@turt2live is this considered fixed in a stable version?

I haven't tried any of the dev versions, but using v1.6.8 the room list is definitely still a lot worse to use than the "old version" that had a global scrollbar that covered all rooms. I wouldn't say I have an especially small screen (768px high) but the individual scrollbars for each header is rather painful to use.

The image in [comment 495782565](#issuecomment-495782565) "describes" the problem best, where you can only seem one room at a time under FAVORITES with a very small scroll bar.

**Comment by turt2live** [comment]
The fix is not in stable yet. We close issues when they're fixed in development.

**Comment by mvgorcum** [comment]
No, the new room list is still just behind a labs flag, so you won't find it on 1.6.8 yet.
