### ISSUE TITLE
Riot-web installation error; repository does not have a stable release

### ISSUE THREAD

**Issue by Sumaid** [vector-im/riot-web#8095]
### Description

When I try to install riot-web in Ubuntu 18.04, using bionic distribution, 
it gives the following error
E: The repository 'https://riot.im/packages/debian bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by lampholder** [comment]
Following the instructions on https://riot.im/desktop.html on a fresh bionic install worked for me - @dbkr do you have any thoughts as to what might be going wrong?

**Comment by jryans** [comment]
@tejasvi Since you are seeing this as well, did you follow the instructions on https://riot.im/desktop.html?

**Comment by tejasvi** [comment]
@jryans Yeah, I surely did.

**Comment by lammas** [comment]
The package repository and https://riot.im/desktop.html seem to be 404 now. What's up with that?

**Comment by turt2live** [comment]
@lammas That would be because of https://matrix.org/blog/2019/04/11/security-incident/

**Comment by ecofintech** [comment]
Any update about this issue? I saw today a new version was released but i cannot install it because that 
'E: The repository 'https://riot.im/packages/debian bionic Release' does not have a Release file.'

thanks

**Comment by t3chguy** [comment]
@ecofintech the repository isn't riot.im/packages anymore, it is packages.riot.im,

https://packages.riot.im/debian/dists/bionic/Release

so you'd want
`https://packages.riot.im/debian bionic Release`

**Comment by gen1e** [comment]
I don't know if this helps some others having this issue, but I'm running Linux Mint 19 (Tara) and ran into the same error. I was using the [exact commands on the site for desktop](https://riot.im/download/desktop/). However, because I'm using Mint instead of straight up Ubuntu or Debian the `lsb_release -cs` command returned `tara` instead of `bionic` which messed up the link to the repo. I replaced the `$(lsb_release -cs)` in the echo command with `bionic` and it worked. 

So for those having the same problem and come across this issue, you may want to run `lsb_release -cs` in your terminal and make sure that the distro coming out matches one of the ones [here](https://packages.riot.im/debian/dists/). If it doesn't match, then manually replace it in the echo command.

This might be something to be noted on the desktop download instructions page.

**Comment by LinuxOnTheDesktop** [comment]
> This might be something to be noted on the desktop download instructions page.

Definitely. It would not take that long to make that change and it would save every Mint user time.

**Comment by t3chguy** [comment]
The original issue likely caused by a 32 bit system where 32 bit Electron is no longer supported. https://www.electronjs.org/blog/linux-32bit-support


The mint issues will be solved by https://github.com/vector-im/riot-web/issues/13367
