### ISSUE TITLE
We should make the rageshake issue description and/or URL required 

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8155]
There's a lot of rageshakes that get sent with zero context. We should require the user enter an issue URL or a textual description before being able to submit the report.

**Comment by jryans** [comment]
On a related point, someone else recently mentioned (can't seem to find where) that there's a confusing cyclical ordering between the Riot bug report UI and the issue templates, since the issue templates tell you to send logs and report if you did so, but of course the log report is much more valuable if it has issue attached.

Perhaps we should also clarify the issues templates if the URL is required.

**Comment by lampholder** [comment]
We definitely need to rework the way in which we get feedback generally and bug reports specifically
