### ISSUE TITLE
Roomlist reordering lags

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8184]
Erik and Anoa reported that they would get the notification badges on rooms, but those rooms wouldn't move to the top of the roomlist until ~30 seconds later.

**Comment by bwindels** [comment]
really feels related to the roomliststore cache, as the badges, font-weight for unread, ... are not going through the cache but go straight to the source (`room` & `Unread`, ...), whereas the sorting is based on the cache.

**Comment by bwindels** [comment]
I did notice that the badge does get updated when you are hovering over the roomlist. Need to check if it wasn't because my keyboard focus was on another window with the react tools. If this is the case, it would be interesting to know what triggers that update to the roomlist. It could mean that roomliststore isn't emitting change events at all (as opposed to emitting them but without clearing the cache them having the same order), and something else is updating the roomlist.

**Comment by bwindels** [comment]
RoomTile updates it's notification count on a Room.timeline event without any filtering. This is backing the badge count (and showing of a grey badge).
RoomSubList sets unread and highlight props on RoomTile, which backs the font-weight and red badge.

So it seems RoomSubList (and thus RoomList) is not re-rendering for some reason. Either because of the hover state, or something in RoomListStore deciding not to regenerate.

**Comment by bwindels** [comment]
@erikjohnston has been able to repro the issue while seeing `RoomList.state.hover: true` (through React tools) when not having the cursor over the RoomList.

**Comment by bwindels** [comment]
Turns out that Chrome doesn't fire `mouseleave` reliably if the `mouseenter` handler is still running.
See also https://github.com/vector-im/riot-web/issues/2420

**Comment by turt2live** [comment]
In practice this should be fixed now
