### ISSUE TITLE
Staging/Nightly builds for electron

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#8299]
Lots of silly mistakes keep happening with desktop (like #8298, #8288, and #8229(?)) I guess because no one can test it before the release comes out. There needs to be release candidates of Desktop that people can test.

**Comment by lampholder** [comment]
100% agreed, this has been outstanding for a while. I hope for us to get to this very soon.

**Comment by aaronraimist** [comment]
Related: #3009

**Comment by lampholder** [comment]
Related: https://github.com/vector-im/riot-web/issues/9337

**Comment by ara4n** [comment]
@turt2live just pointed out that if we're making Riot/Desktop more the first class citizen (for E2E features like storing cross-signing keys, or E2E search), then we really need to increase the priority on this.

My preference would be to have the option in the desktop app to just point its HTML+JS+CSS at https://riot.im/develop rather than running off file:/// if you want develop, so you get full live-updating as per riot.im/develop today - but I can also see this being a bit painful as we add more and more electron specific bits.

**Comment by turt2live** [comment]
further to that: we could introduce this as a nightly/beta/release channel (with release being the default). Users could pick the channel they want and go from there.

I don't think we need down to the minute updates on the nightly channel: once a day should be plenty for what we're doing. How we actually distribute those is probably some heavy abuse of a CDN.

**Comment by jryans** [comment]
Nightly builds now exist at https://packages.riot.im. 🎉 We'll [update](https://github.com/vector-im/riot-web/issues/13173) https://riot.im/download/desktop/ with clearer instructions for each platform in the coming days.
