### ISSUE TITLE
chevron is broken for LanguageDropdown

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8339]
Should we switch this over to being a normal <select>?  Originally this was a custom component so that it could have flags - but languages categorically don't have flags.

**Comment by ara4n** [comment]
<img width="431" alt="screenshot 2019-01-31 at 12 31 54" src="https://user-images.githubusercontent.com/1294269/52051603-554b7580-2554-11e9-9e6a-63e8c25be2d8.png">

**Comment by ara4n** [comment]
(chevron should be on RHS)

**Comment by lampholder** [comment]
Looks like we use this component on the login page, too (choosing your login mechanism suffers from the same misplaced chevron).

**Comment by jryans** [comment]
This is the `Dropdown` component that has been around a while. The arrow icon was recently updated, so perhaps the position regressed when that happened.

There is also a new `Field` component which (when used as a `<select>`) also has a dropdown arrow that we [just tuned](https://github.com/vector-im/riot-web/issues/8264) to be on the right with the identical arrow icon.

So, we currently have two dropdown components with the same arrow icon, but `Field` will use native select / options, while `Dropdown` is all custom so it can include images and such.

So it looks like here we should:

* FIx `Dropdown` to push the arrow to the right again
* Possibly switch this language selector to `Field` because it doesn't show fancy things like flags

**Comment by jryans** [comment]
I fixed the `Dropdown` chevron position in https://github.com/matrix-org/matrix-react-sdk/pull/2564.

Let's consider switching to away from `Dropdown` as a separate task.
