### ISSUE TITLE
Always (or opt-out) remove metadata from sent media.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [vector-im/riot-web#8379]
I just sent a photo through riot-web desktop and then downloaded it, it was an unmodified file containing all the metadata. Metadata should be completely removed from sent photos, movies and possibly other files. If someone really cares about metadata being preserved, then there should be a switch in settings to disable metadata removal.

The photo should be equal to the file resulting after running `exiftool -overwrite_original -all= file.jpg` There's no reason for there to be anything. This is the default behavior for apps like Signal, Whatsapp, even Facebook Messenger.

PS. Why on earth do I still have to waste time reporting this sort of obvious privacy problems and then wait years hoping they will get fixed?! I get the impression that this project doesn't care about privacy at all as literally everything is designed in opposite way.

**Comment by l3jyeo** [comment]
I agree. I have also uploaded a photo as a profile picture using riot-web, went on another user, downloaded the profile picture, and all the metadata was still there. This is a privacy concern.

**Comment by lampholder** [comment]
Thanks for your comments; feedback is always appreciated. Stripping exif data from images is a good idea, especially if it's a default setting people can change if they do want to upload their images with the metadata unmolested.

> PS. Why on earth do I still have to waste time reporting this sort of obvious privacy problems and then wait years hoping they will get fixed?!

I understand your frustration, but please remember that we're a small team working on a lot of very complex problems - we're trying to priortise the best we can, but we can't work on everything at once. We don't always get our prioritisation right, but we're always trying to strike a balance between adding features, improving stability, enhancing privacy, growing our user base and supporting the ecosystem.

Also do remember - if you want to submit specific fixes for things, the project _is_ open source and submissions are welcome. This might be a tricky one - you'd have to liaise with the core team to get the design right, 'cause (I think) we'd ideally want to implement this as an additional step in media upload (I think we'd want to strip exif on the way in rather than just on the way out).

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/4426
