### ISSUE TITLE
Secure Message Recovery should be renamed.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [vector-im/riot-web#8380]
The name 'Secure Message Recovery' is misleading, it should be changed to allow people to have a grasp on what it does. There's currently nothing that implies it involves private keys nor backing up of them, nor that it's done to a not trusted (E2E is about not trusting servers) server. I notice in riot-web that currently it's forced down people's throats - 'Show a reminder to enable Secure Message Recovery in encrypted rooms' is enabled by default. Some ideas: Server Key Backup, Encrypted Server-Side Key Recovery.

It should either be disabled by default and hidden in Settings or implementors should read a good amount of docs about dark patterns utilized by companies like Google or Facebook or do exactly the opposite. So if there's a box that asks for consent to enable this when you first open Riot, it should do everything possible to make user not want to enable it (yes! use these dark patterns, make the user accidentally tap 'disable', make them feel as if they are asked to install a virus, do it!) and only enable it after they have a few good nights processing all the information they should know about this beforehand and that they have been given in that box and are sure that's what they want knowing its pros and cons. Most people are fine without this feature, see Whatsapp and Signal, most of the rest will be fine with Cross-Signing which is the easiest sane way to do multi-device E2E I know of, only some will want to have everything on the server.

**Comment by lampholder** [comment]
At the core of your feedback is a good point - 'Secure Message Recovery' is a misleading title. We've changed it, and we're still iterating on the E2E UX.

We're trying to strike a balance between making interaction simple enough for the average user to do (what we think is) "the right thing", whilst keeping people who want/need more information and options informed and empowered. This is pretty difficult to do.

> It should either be disabled by default and hidden in Settings or implementors should read a good amount of docs about dark patterns utilized by companies like Google or Facebook or do exactly the opposite. So if there's a box that asks for consent to enable this when you first open Riot, it should do everything possible to make user not want to enable it (yes! use these dark patterns, make the user accidentally tap 'disable', make them feel as if they are asked to install a virus, do it!) and only enable it after they have a few good nights processing all the information they should know about this beforehand and that they have been given in that box and are sure that's what they want knowing its pros and cons. Most people are fine without this feature, see Whatsapp and Signal, most of the rest will be fine with Cross-Signing which is the easiest sane way to do multi-device E2E I know of, only some will want to have everything on the server.

I'm afraid I can't understand the point you're making here - some additional punctuation might aid legibility. I can respond to the last sentence, though - a gross simplification of what we're trying to achieve with our E2E impl is that we're trying to offer some of the best bits of _both_ WhatsApp and Signal - we want Riot/Matrix to have:
- persistent (always encrypted) history
- multi device support
- secure-enough and usable-enough by default 
- visibility on users' changing devices with good UX cues to do appropriate due dilligence required to maintain secure communication

And - that's hard. It's worth pointing out that the current E2E UX is just a way point on our journey - trying to give people the benefit of the key backup system we've implemented en route to cross signing. But cross signing itself isn't a silver bullet - what happens if you lose your only device?
