### ISSUE TITLE
Intermittent OLM.UNKNOWN_MESSAGE_INDEX errors when trying to KS after SAS verif

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8433]
I've had this twice, once on stage at FOSDEM...

https://youtu.be/C2eE7rCUKlE?t=2953

It also looks from the video as if i got two KS reqs from the new device, which may be related?

**Comment by uhoreg** [comment]
It looks like what's happened is that after verifying using SAS, the keysharing dialog doesn't get the message that the devices are now verified (note that at t=2958, @ara4n has to click the 'X' button on that dialog), and so it never actually sends the keys.  Clicking the re-request keys button would probably fix it (though it wouldn't have worked in the demo because re-requesting keys was broken at the time).

**Comment by turt2live** [comment]
I think we managed to fix this, somehow. Has anyone else seen it outside of the live demo on stage?

In gif form, here's the demo sped up and scaled down (so the gif isn't massive):
![keybackup-small mp4](https://user-images.githubusercontent.com/1190097/59955209-2cb21280-9446-11e9-8273-e3bf9806de00.gif)

**Comment by turt2live** [comment]
Counting this as "probably fixed, hopefully". If people see it again, please open a new issue.
