### ISSUE TITLE
No way to clear chat history/conversation logs?

### ISSUE THREAD

**Issue by TNW9imKLC3fv** [vector-im/riot-web#8544]
Hi, I was meaning to post this a while ago when I made the issue before after trying this program for the first time (I since moved away from Riot as a solution onto Gajim/Pix-art messenger/Conversations/XMPP), it seemed a rather glaring issue of missing basic functionality, that I was surprised and disappointed at, and made me a little skeptical about the whole project that such a thing could be missed (aside from the whole having Google IP-tracking captcha as a compulsory part of the only login page):

Why is there no option to clear history of a chat instead of forcing people to (impractically) go line-by-line?

**Why no option to delete conversation logs which are apparently kept on everyone, forever?**

**That's many peoples' issue with Discord, but it seems like Riot's exactly the same?**

As well as individual conversations, even better would be implementing the EU's Right to be Forgotten and letting people remove their own chats from the group chat rooms on servers (including ones not a member of anymore)

**Comment by jryans** [comment]
If you participate in a room federated with multiple homeservers, it's quite hard to _truly_ delete anything. When you choose to remove a message, another message is sent requesting that clients remove it.

It's a lot like email in that sense: you can delete your local copy, and you can tell everyone else to delete their copy, but it's hard to be sure everyone did in fact do so.

There are other issues about history retention that may interest you, such as #3800 and #3177.

**Comment by hoergen** [comment]
Sure deletion can be a complex task in a federated environment, but they way of looking on that topic is to start with the own homeserver and/or room on "some" server.

My view on this is, that you should be able as
 - room creator to set a retention/deletion time for messages and attachements
 - home server admin to set a general maximum retention/deletion time for messages and attachements

because 
 - firstly of the space on your harddrives where you pay money for it, 
 - secondly of cleaned up rooms and 
 - thirdly there was a big discussion years ago on the net about "the right to forget", what is for example very important topic for me. And that is part of the GDPR https://gdpr-info.eu/art-17-gdpr/

And according to the third point there is a movement coming from the privacy site, to collect only data that is nescessary and to delete everything else.

You never can control if the data is deleted as well on other instances. You only can send  a deletion requests and that's it. And that is "okay". If there are "black sheeps" out there you can block them anyways with your firewall or other tools.

I really would love to see such an option in riot/synapse.

**Comment by ara4n** [comment]
closing as dup of #3800
