### ISSUE TITLE
Dark theme avatars should have brighter background color for transparent images

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#8558]
As most transparent avatars seem to assume a light background.

![image](https://user-images.githubusercontent.com/274386/52710458-a36a6b00-2f8f-11e9-8b48-873254d0ec4b.png)

**Comment by ara4n** [comment]
i think this is incorrect, as per https://github.com/vector-im/riot-web/issues/8425.

tl;dr:
 * if you want your avatar to have a light background, you should upload one with a light background.
 * if you want your avatar to have a dark background, you should upload one with a dark background.
 * if you want your avatar to have a transparent background so that it fits into both light and dark themes, you need to design the artwork to work on **both** light and dark backgrounds (e.g. not upload a black-on-transparent avatar and then wonder why it's invisible in a dark theme).

**Comment by rxl881** [comment]
I think that @matthew is right, but there will be a lot of existing avatars out there that will look pretty broken / invisible in the current setup. Could this be fixed by adding a hairline border (with the same colour as the room list separators) around the avatars, so that at least you can see that they are there, regardless of the content?
