### ISSUE TITLE
Dark theme: redacted messages could look nicer

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#8559]
Currently they look like this, which is a bit too flashy for me on a dark theme:

![image](https://user-images.githubusercontent.com/5547783/52710725-f2ac9d80-2f87-11e9-9601-1acecf70c1f5.png)

**Comment by jryans** [comment]
I think this one needs feedback from @nadonomy first.

**Comment by swedneck** [comment]
I think it'd be nice to treat deleted messages the same as join/leave/avatar change messages, it feels much more appropriate than a big band of warning tape.

**Comment by turt2live** [comment]
@swedneck that is an option in your settings.

**Comment by turt2live** [comment]
Worth noting that this used to work with the old dark theme:
![image](https://user-images.githubusercontent.com/1190097/52817113-2a871400-3060-11e9-9a0a-0ce8da2e12c4.png)

**Comment by swedneck** [comment]
It is? i know about the "Show a placeholder for removed messages" toggle, but that doesn't seem to replace them with join/leave-style notifications.

**Comment by targodan** [comment]
I was missing the keyword redacted when searching for an issue. Sorry about the duplicate. I like the old version probably even better than the one I cobbled up earlier.

**Comment by turt2live** [comment]
@swedneck it somewhat depends on what you mean. Redacting a join event causes it to disappear (currently). If you mean the MELS thing, that would be a new issue.

**Comment by swedneck** [comment]
@turt2live i presume MELS is the stuff like join/leave/avatar change/kick/ban, in which case that is what i mean.

**Comment by turt2live** [comment]
Yup, Membership Event List Summary - it sounds like you're looking for new functionality, which is worth a new issue :)

**Comment by tebjan** [comment]
even in the old theme this was way to massive, at least for my eye. it could be very decent and don't draw attention at all.

**Comment by tebjan** [comment]
also: the ability to edit messages would make this issue much less pressing ;)

**Comment by matrixes** [comment]
I read a couple of comments in the Riot-chat from @swedneck and I think he's onto something good;

Make the redacted highlight into something _visually similar_ to join/leave messages.

![redacted-enhanced](https://user-images.githubusercontent.com/46491408/52822131-28997100-30b1-11e9-88e3-0f9201d838a2.png)

There are a few ways you can make it "unique" if that's what you're going for. Custom icon and text color for one.

I'm actually not really sure why the redacted highlight has taken such a prominent place in the chat (I'm new to Synapse/Matrix/Riot, so I don't have the background yet), as it is.
The way it's presented right now (the striped graphic), redactions are among the single most important events in the chat.
This may be my personal view, but I definitely want them to be lowlights, not highlights. I want to be aware of them, but only in my peripheral view. If I'm interested in redacted messages, I'll go look for them, but I don't want to become aware of every single time it happens. It's impossible to ignore them at this point.
Also, having this as a text phrase instead of a striped "thing", makes it easily searchable, if that's a concern.

**Comment by aaronraimist** [comment]
A related issue requests that they be collapsed: https://github.com/vector-im/riot-web/issues/3657

**Comment by matrixes** [comment]
I think that should be considered as well.
I (as many others, I'm sure) have used both Slack and Discord and they have way less intrusive (none at all, really) indicators/highlights that a message has been removed.
They do have something for _modified/edited_ messages, but that is another topic.
For redaction/removal, Riot is the first I've come across that makes such a "big deal", in lack of a better phrase/word for it, out of redacted messages, and I'm not geling with them, and it looks like others have had the same thought as well.

**Comment by jryans** [comment]
This issue is about redacted messages and how they look on the dark theme. For now, I'll restore the previous behavior that @turt2live mentioned.

The other ideas people have mentioned here about new behavior don't seem to specific to the dark theme. I would recommend filing a separate issue for these.

**Comment by jryans** [comment]
Fixed by matrix-org/matrix-react-sdk@91c91c5ca9cec166d90b71211a4f14b61ffcdf93.
