### ISSUE TITLE
Some icons are now weirdly cropped in UserSettings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8578]
<img alt="screenshot 2019-02-13 at 15 22 19" src="https://user-images.githubusercontent.com/1294269/52722293-36f96700-2fa3-11e9-89cc-a8e48888d360.png">

I suspect the SVGs need to be tweaked so that the bounding box is 1px larger in all dimensions ,so that the stroke isn't cropped in half when it overlaps the current boundary, causing the flagpole to be half-width and the phone to be truncated on the sides.

**Comment by nadonomy** [comment]
> I suspect the SVGs need to be tweaked so that the bounding box is 1px larger in all dimensions ,so that the stroke isn't cropped in half when it overlaps the current boundary, causing the flagpole to be half-width and the phone to be truncated on the sides.

Just checked— the SVG's are all good.

The problem is `.mx_TabbedView_maskedIcon` has a width of 16px, while it's  :before pseudo-element carrying the mask is only 14px, hence the clipping.

I'm not sure if the delta is intentional, but changing the width of `.mx_TabbedView_maskedIcon:before` to 16px fixes it.

**Comment by turt2live** [comment]
The gap is intentional to fix clipping on windows, which was happening at least locally. Will test again though.

**Comment by turt2live** [comment]
looks like something else was causing it to be weirdly cut off on windows - upping to 16px fixes it.
