### ISSUE TITLE
Save buttons on room settings are confusing and inconsistent 

### ISSUE THREAD

**Issue by rxl881** [vector-im/riot-web#8581]
- **Browser**: Chrome
- **OS**: macOS

### Description

There are multiple save buttons on the form (which is confusing, especially when changing the avatar as it isn't clear that you need to click the save button before exiting the form. However the save buttons are also inconsistent in appearance - see the following screenshot where the first save button is disabled and dimmed (presumably because there were no changes to the form), but the ones further down the page were not disabled (despite there not being any changes in those sections either).

![screenshot 2019-02-13 at 16 10 12](https://user-images.githubusercontent.com/6763606/52725928-08cb5580-2faa-11e9-8621-d9ea92c1d571.png)

Personally, I would like to see a single save button for the form (fixed to the top or bottom of the form window), or even better dynamically updating and saving the form as elements are updated.

**Comment by turt2live** [comment]
The profile save button being weird is https://github.com/vector-im/riot-web/issues/8569 - the other buttons are temporary placeholders due to bad code. See https://github.com/vector-im/riot-web/issues/8207 ("* `EditableItemList` should be using `Field`, not whatever it currently is (aliases, related groups)")
