### ISSUE TITLE
Make scrolling more discoverable on room list

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8647]

**Comment by jfrederickson** [comment]
I'm personally not a huge fan of the individually scrollable room list sections; when I'm looking for something, I typically know what section it's in, but I don't necessarily know where in that section it is (because rooms are reordered based on activity).

With the new scrolling behavior, I can see fewer rooms in each section onscreen at once unless I resize the section before scrolling through it, which is kind of frustrating.

**Comment by turt2live** [comment]
Good news! We've ripped out the letterboxes in the new room list.

**Comment by remram44** [comment]
Hurray! I'm glad your stubborn UX team finally saw reason. I can now retire [my patch](https://github.com/remram44/matrix-react-sdk/commit/21b5b070b804c01c673ff63a2b8be9943dad3608), and I think you can close #10665 and #3824.
