### ISSUE TITLE
Stop using Cloudflare

### ISSUE THREAD

**Issue by theel0ja** [vector-im/riot-web#8691]
You advertise yourself as "decentralized" platform, but use Cloudflare for `riot.im` and `matrix.org` (all communications using that Matrix server is routed through Cloudflare)

**Comment by jryans** [comment]
I think this is quite hard to change in a world where DDoS attacks are possible.

**Comment by lampholder** [comment]
Matrix is decentralised because there is no single point of control - the multitude of Matrix homeservers running globally can operate and federate and communicate amongst each another regardless of whether any particular homeserver is running.

Routing the matrix.org homeserver behind Cloudflare doesn't change this - as @jryans says it's just an implementation detail that helps the instance we run from matrix.org defend itself against DDoS attacks. 

Likewise the Riot instances at https://riot.im - if you don't want to rely on Cloudflare's availability to access a Riot client, you can download the electron client, or a mobile app, or host your own Riot web instance, or use one hosted by somebody else.

**Comment by smnthermes** [comment]
@jryans @lampholder Privacy violations are worse than DDoS. Even with other instances, metadata is still sent to matrix.org. 

Read this article:
https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README.md

**Comment by t3chguy** [comment]
So some service is worse than no service? If you're not happy using the hosted riot.im you can use the desktop (electron) app which is offline or host it yourself from the freely provided tarballs. I know I'd prefer having some highly available hosted riot-web instance running than wasting the foundations money on other DDoS solutions or ops time to put out fires.
