### ISSUE TITLE
Cannot change default server urls in client's config file

### ISSUE THREAD

**Issue by eleius** [vector-im/riot-web#8730]
### Description

I want to use my custom homeserver & identityserver urls in riot's config file, but when I restart the client it reverts back to the default (matrix.org and vector.im). I can still enter them manually each time.

### Steps to reproduce

- Change default_hs_url and default_is_url in /etc/riot/config.json
- Start the riot client
- Click sign in > change > other servers: defaults URLs are used

### Version information

- **Platform**: desktop client (riot-desktop package)
- **OS**: Arch Linux
- **Version**: 1.0.1-1

**Comment by eleius** [comment]
I reported the above after trying for hours (and making sure the riot process was not active between restarts). Now it suddenly started to work. I don't understand why... Closing this issue nonetheless.

**Comment by drseussofporn** [comment]
I know this issue is closed, but it seems like the only reasonable place to put it. I'm experiencing the exact behavior on a Windows 10 desktop client where my custom homeserver and identityserver are configured in config.json but the client does not pick up the settings on launch (defaults to matrix.org and vector.im respectively). I did discover, however, that changing the language on the login page THEN causes the corrects values to populate from the config.json file. Has anyone else experienced this behavior? It almost seems that the initial load of the Client retrieves a cache of default values until an item is changed, then uses the settings in config.json.

**Comment by jryans** [comment]
Please file a new issue and describe precisely what you have changed, version of Riot, etc. so we can investigate.
