### ISSUE TITLE
Room Directory is hard to find

### ISSUE THREAD

**Issue by spantaleev** [vector-im/riot-web#8770]
This is probably the new equivalent of #3321.

The redesign makes it hard to "Explore" stuff.

Whether that's intentional (because matrix.org is very slow and can't serve a Room Directory quickly enough) or not, I don't know.

I knew there was a Room Directory feature from before, and even with that knowledge, it still took me a few minutes to randomly stumble upon the "+" button next to "Rooms". Finding it was completely random, as I've clicked a similar "+" button before (next to People) and knowing that it just shows a textbox did not give me the impression that the "+" button next to "Rooms" would bring up something more interesting. I merely expected a text input.

Whether this is an issue or not, I can't decide yet.. It could be my prior conditioning..

**Comment by eddie1030** [comment]
Same issue here! I couldn't find the Rooms Directory until I found this post (what the hell , just a + sign for such an important feature :)).

Actually, I was confused since the left menu in my Riot Web app ( debian package ) shows the "communities" and "bug report" icons, while the scrollbar seems a bit up. So I thought you'd have to scroll down to see the other icons ( rooms dir , start chat, .. ) and that it was the scroll being buggy :)..

Conclusion, a more prominent place for this feature would be much appreciated!

Just my 2 cents !

**Comment by DJCrashdummy** [comment]
IMHO this is a clever UX!
as soon as **somebody wants to add a room *(whether existent or not!)* to his account/interface**, it is not that hard to "find" the plus-sign.

i guess this is just an issue because some people are **used to an other workflow** in this case **because of the old design**. - for my part, i always wondered why there is so much space of the old UI used (beside other useless buttons) for a feature i use once while exploring and then hardly again.

**Comment by turt2live** [comment]
just a data point: I had to explain over an email where the room directory was so that someone could find the rooms they were looking for. It's very hard to say "Click the + next to the ROOMS list" because the person interpreted that as the one on PEOPLE.

**Comment by aaronraimist** [comment]
Well it has gone back to being a separate button... just as it seemed like people got used to it being the + button :/
