### ISSUE TITLE
"Room contains unknown devices" - but devices are not listed

### ISSUE THREAD

**Issue by IzabellaDK** [vector-im/riot-web#8815]
### Description
**"Room contains unknown devices" - but devices are not listed
and they are not visible elsewhere**
Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce
Just open the padlock with the exclamation mark on top of the room
- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.
**Since I no longer can see on the entries from the participants which device they are using I would look for unknown devices at the mentioned padlock icon. But nothing shows so I still do not know which devices and who has them**

Log: sent/not sent?    

![image](https://user-images.githubusercontent.com/25612389/53078453-8e905900-34f4-11e9-80ad-1c5ab0ec33eb.png)

### Version information
**Windows version of 16.2.19**

- **Platform**: web (in-browser) or desktop?
**Desktop**
For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:
**Windows 10**
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y 
**matrix-react-sdk version: <local>
riot-web version: 1.0.1
olm version: 3.0.0**

Thank you for a nice app that has a lot of charm and looks much better in the latest version!

**Comment by git-minix** [comment]
I came across the same problem - this brought the upgrade to the Riot version 1.0 - It confuses our matrix users, who are already overwhelmed with E2E Keys anyway - so it is not a cosmetic problem.

**Comment by Valodim** [comment]
I'm also seeing this, quite commonly in fact. I just checked three one-on-one rooms and one with three people, and in each of these there are devices listed clicking on the profiles in the member list, where *just some* of them aren't listed.

I could not find any pattern to this:
* It's not a particular client that's not showing up (happens with at least both android riot and web)
* I've seen devices missing that have written messages recently, while others that have written recently do show up

**Comment by lampholder** [comment]
If I understand this correctly, the dialogue is actually doing what it was designed to do - showing you a list of _unknown_ devices.

Unknown is a peculiar state in Riot E2E UX - a device is _unknown_ if:
- you don't trust it
- you have not tried to send an encrypted message to the room since this device joined

When you try and send a message, if the number of _unknown_ devices is > 0, you get the "unknown devices" warning and this dialogue will pop up with a reasonably sensible list of all the devices that have joined since you last sent an encrypted message.

If you click the padlock, you open this same dialogue, but it often contains no entries, which is confusing.

We should either:
- disable the clicking of the padlock, or
- modify the dialogue so that it shows what people expect - a list of _untrusted_ devices (or perhaps a list of all devices, including their _trusted_, _untrusted_, _unknown_, _blacklisted_ states).

Looking to maximise ROI, I think we should probably disable the padlock clicking for now.

**Comment by IzabellaDK** [comment]
Why close the subject? The problem is still there...

**Comment by aaronraimist** [comment]
It was just fixed, 18 minutes ago. There isn’t a release out yet with the fix but 1.0.4 will contain the fix.

**Comment by Valodim** [comment]
It is "fixed" by https://github.com/matrix-org/matrix-react-sdk/pull/2784, in a way.

Surely it is useful and even necessary to have a way to see what the problems with a room e2e state are, and what the user has to do to fix them. However, as soon as cross signing lands, any work that's been done on that part of the UI will probably be redundant. I guess that's why the short term band aid is to not show the dialog if it can't actually be helpful.

**Comment by jryans** [comment]
Issues are auto-closed when a fix is merged to develop. You can check https://riot.im/develop if you'd like to try the latest testing build that includes the changes made here.

**Comment by git-minix** [comment]
Disabling the padlock click handler is no solution, as the user, as well as the administrator of a matrix homeserver, would like to know which "unknown devices" are triggering the alert. If such warnings exist without the user being able to identify the cause, users will in the future ignore such warnings.

**Comment by aaronraimist** [comment]
The whole bug is that that popup is able to show up when there are no unknown devices.

**Comment by turt2live** [comment]
This issue was treated as a bug, I've opened the feature request side as https://github.com/vector-im/riot-web/issues/9156

**Comment by git-minix** [comment]
The question is, what was fixed in the Bug? Were there false warnings about "unknown devices" that did not really exist? Then the padlock click handler with the empty list of "unknown devices" would be correct.

Or was it a correct warning, but the padlock click handler was unable (for whatever reason) to display these "unknown devices"?

**Comment by turt2live** [comment]
The padlock was supposed to link to something helpful, but instead it linked to an unhelpful dialog. It should have shown *unverified* devices but was showing *unknown* devices (which have a subtle difference). However, we don't have a design or UX for listing unverified devices, hence https://github.com/vector-im/riot-web/issues/9156

**Comment by heini** [comment]
Just seeing this on Riot Web 1.5.6. I've got a room which states there were untrusted devices, but I see no means of identifying them. So how could this be closed?

**Comment by heini** [comment]
OK, found it, by accident. Need to click the user's icon in one of the messages, which opens the right pane which in turn has a list of all devices, incl. buttons to verify the untrusted ones.
