### ISSUE TITLE
Can't create rooms if the /publicRooms API is broken

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9046]
Because we hide room creation in the room dir now, if the roomdir can't load because /publicRooms is slow/broken (as is often the case), you can't create rooms any more :(

**Comment by jryans** [comment]
Do you have more detailed steps to reproduce here? I tried to force the problem by making the code path that requests `/publicRooms` never return, but I was still able create a room.

I don't think this needs to block the upcoming release as it stands (since we've had this UX live for a while with the redesign).

**Comment by dbkr** [comment]
If I block `https://matrix.org/_matrix/client/r0/publicRooms` in Network in chrome dev tools, this happens:

![infiniteerrors](https://user-images.githubusercontent.com/986903/55080775-9cf30700-5096-11e9-9b85-d7cbdad4de42.gif)

**Comment by jryans** [comment]
Ah right, if I simulate `/publicRooms` being rejected, I get something similar. Let's assume that's the issue we want to fix here.
