### ISSUE TITLE
Device keys change if indexeddb data gets deleted

### ISSUE THREAD

**Issue by rxl881** [vector-im/riot-web#9107]
### Description

UTDs from existing Linux chrome client that has worked previously. All other devices continue to work. Unable to fix by verifying devices or requesting re-sharing of keys.

For the web app:

- **Browser**: Chrome
- **OS**: Linux
- **URL**: https://riot.im/develop

**Comment by dbkr** [comment]
What has happened here is that Rick's device has had its indexeddb data deleted (presumably he got low on disk space and Chrome looked for things to sacrifice). When this happens, the device keeps the same device ID (because that's in localstorage) but gets new keys (because those are in indexeddb). The result being that any device that has seen his device before will refuse the key change and therefore e2e will break between the two devices.

**Comment by lampholder** [comment]
We're going to draw this occurrance to users' attention with https://github.com/vector-im/riot-web/issues/9109 so we can probably close this.
