### ISSUE TITLE
Reliable Storage: Error to the user when IndexedDB gets blown away

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9109]

**Comment by ara4n** [comment]
rather than failing silentlyl

**Comment by ara4n** [comment]
closely related to https://github.com/vector-im/riot-web/issues/7465

**Comment by turt2live** [comment]
Technically a fix for https://github.com/vector-im/riot-web/issues/6120

**Comment by jryans** [comment]
I assume we are fairly confident that people are observing:

* IndexedDB deleted by browser
* Local storage remains in place (because they are still logged in)

as the case we want to handle here?

(That's not _supposed_ to be what happens, since browsers are meant to atomically purge all forms of storage for a origin together when you are out of space, but it's hard to be sure about what happens in practice other than testing manually to see.)

**Comment by jryans** [comment]
> I assume we are fairly confident that people are observing:
> 
>     * IndexedDB deleted by browser
> 
>     * Local storage remains in place (because they are still logged in)
> 
> 
> as the case we want to handle here?
> 
> (That's not _supposed_ to be what happens, since browsers are meant to atomically purge all forms of storage for a origin together when you are out of space, but it's hard to be sure about what happens in practice other than testing manually to see.)

While the Storage Standard says all storage for an origin group should be limited by a single quota, in practice, browsers appear to handle `localStorage` separately from the others, so it has a separate quota limit and isn't evicted when low on space.

* Chrome, Firefox
    * IndexedDB for origin deleted
    * Local Storage remains in place

**Comment by jryans** [comment]
I have merged some [investigation notes](https://github.com/matrix-org/matrix-js-sdk/blob/develop/docs/storage-notes.md) with what I've found so far here.
