### ISSUE TITLE
Auth footer links should be configurable

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9127]
Use case: my twitter is not your twitter

**Comment by jryans** [comment]
This one of those things that Riot inserts by replacing React SDK components. Now, usage of the React SDK as an SDK is quite low I assume...

Not sure the easiest way to make this area configurable. Options include:

1. Load external static content like `welcome.html` and such
2. A complex JSON blob to configure links
3. Edit the `VectorAuthFooter` component

**Comment by turt2live** [comment]
Can't it just use the sdkconfig?

**Comment by jryans** [comment]
> Can't it just use the sdkconfig?

Sure, that's what I am implying with "A complex JSON blob to configure links".

I guess personally, it feels like just allowing static content would be simpler than defining a set of options for describing links that we then have to maintain and support in config.

**Comment by turt2live** [comment]
I'm honestly not convinced that HTML is easier to support than sticking `"blogUrl": "https://example.org"` into a branding section of the config

**Comment by jryans** [comment]
Well, `authFooterUrl: "footer.html"` should be fairly low maintenance, I think. It leaves it open ended for admins to put whatever content they prefer using regular HTML.

If we go the configuration route, what happens when we add more or less links to the Riot version of the footer? Do we preserve support for community ones alongside those because we added options for them in the past?

Maybe people would like to put something other than links in the footer. Maybe they would like to have extra links to other services that the Riot version doesn't have.

**Comment by turt2live** [comment]
as a branding config there's no guarantee that the features stick around, just that wherever Riot shows a link to a blog it'll use `blogUrl`. So if all the blog links disappear, then the option becomes useless. Similar to how a theme would work (say, Neon Pink), if things were added then it's the brand's (or theme's) responsibility to handle that as well.

Arbitrary customization adds complexity in maintenance and is harder for us and users to keep up to date. Not to mention it is worth a conversation about how much customization we want people to have, with the understanding that too much customization can result in misc Riots out there being unrecognizably bad but still using the brand. Although this is already possible today by just forking the thing, the barrier to entry becomes higher and much less risky than providing an option for people to easily make it bad.

**Comment by jryans** [comment]
Hmm. I guess my perspective is assuming we think the existing home and welcome areas (which are external static content) are a good idea. If that's true, I am trying to use that as a consistent means of customization.

I guess the main point I am trying to articulate is: we seem to be okay with inserting external static content as a means of customization. What is it about the footer that means it should be handled differently?

Since you are arguing for configuration in the footer, does that mean you also think welcome and home should have been configuration instead of inserting static files?

**Comment by turt2live** [comment]
I'm being super helpful and arguing that we need to take a more serious look at how we do customization in general and what we want from it, using this issue as a vessel to spark that conversation. I do think that there's some value in having arbitrary HTML pages for welcome & home, but also think that we shouldn't let the entire app be free-form. I tend to consider branding on the same level as theming: we shouldn't let people easily create some red-on-pink app; instead, we should be careful in what we allow people to change and apply more intelligent filtering on their inputs.
