### ISSUE TITLE
Clicking mx_E2EIcon mx_E2EIcon_warning used to give a summary of issues, now it doesn't. Should this be added back?

### ISSUE THREAD

**Issue by benparsons** [vector-im/riot-web#9209]
This element:

class="mx_E2EIcon mx_E2EIcon_warning" title="Some devices in this encrypted room are not trusted"></

**Comment by jryans** [comment]
The click handler here was recently removed as part of https://github.com/vector-im/riot-web/issues/8815#issuecomment-472116586 because it was showing _unknown_ devices instead of _untrusted_ devices, and the unknown set could also be empty, so it was just confusing all around.

https://github.com/vector-im/riot-web/issues/9156 hopes to offer something better here.
