### ISSUE TITLE
Getting to the Startpage and searching for Communities is hard to find

### ISSUE THREAD

**Issue by rubo77** [vector-im/riot-web#9261]
### Description

The old riot Interface had a link to an overview page, with links to the matrix community and so on. Now I cannot find a link there any more and also I cannot find a way to search for public Communities (former groups). I can only see the Communities, I created and that are on my own homeserver. Or I can create a nes Community with the "Communities" Button at the bottom left.

### Question
- How do I find Communities, that are created by others?

### Version information

- **Platform**: desktop

- **OS**: Ubuntu
- Version von riot-web: 1.0.5
- Version von olm: 3.0.0

![Bildschirmfoto von 2019-03-23 10-19-55](https://user-images.githubusercontent.com/1591563/54864268-406db000-4d55-11e9-82a7-5c88f139c7cb.png)

**Comment by lampholder** [comment]
At the moment community discover is only handled out of band (i.e. there is no way to search communities in Riot). This may well change in future.

**Comment by lampholder** [comment]
Also, we've removed the home page from riot.im/app and /develop (since we felt it made Riot feel too much like "an app to chat about Matrix" rather than "a chat app for communicating over Matrix") - there's still support for it as a configurable option if people do want to have their own home pages on their own Riot installs.

Onboarding and discovery planning and design is very much in flight - I'm going to close this issue for now (since we're already addressing the issue it raises). Once our initial designs are shared, though, it'd be great to get feedback on how well you think they meet your needs. Thanks!

**Comment by rubo77** [comment]
1. How is it possible to discover communities outside of Riot? Do I have to query the Database directly? or is there another service online somewhere that can discover communities?

2. can you please link to the issues for Onboarding and discovery planning and design here?
