### ISSUE TITLE
If you redact an event, any read receipts associated with that event go missing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#948]

**Comment by turt2live** [comment]
Because of the page tear, it seems like this issue has evolved: https://github.com/vector-im/riot-web/issues/3511

**Comment by jryans** [comment]
This appears to be fixed in current Riot. If you have "Show a placeholder for removed messages" enabled, then read receipt is shown on the placeholder. If that option is disabled, as of https://github.com/matrix-org/matrix-react-sdk/pull/3056, we now rewind the read receipt, so it will appear on the previous message.
