### ISSUE TITLE
Reactions: Use new emoji picker in main composer as well

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9484]
If it's easy to use the new emoji picker (https://github.com/vector-im/riot-web/issues/9483) from reactions in the main composer as well, we should do as part of the aggregations project.

**Comment by aaronraimist** [comment]
Would fix https://github.com/vector-im/riot-web/issues/1107

**Comment by nadonomy** [comment]
To clarify and make sure were aligned.. the intention here is to:

- Still use the full-composer-width emoji autocomplete input when typing a colon into the composer
- Expose the emoji picker using the smiley icon on the composer
- Figure out a nice way to expose stickers (likely, using a new icon) in the composer

**Comment by lampholder** [comment]
That is clear and fully matches my understanding.

**Comment by Flexmaen** [comment]
For me this was very confusing... When I click on the smiley in Riot on Android I can pick emojis.
When I click on the smiley in Riot-Web, I can only select some ugly stickers.
And when I tried to close that sticker window I uninstalled previously installed sticker packs since I expected the X on the right top to close the window...

So the whole situation does not appear intuitive to me. I think it can be improved by adding the emoji-picker there, and maybe the stickers in some tab there. Similar like you have it on your phone (although it is done there by the system, not by Riot I guess).

**Comment by fti7** [comment]
https://matrix.org/blog/2019/10/10/new-vector-raises-8-5-m-to-accelerate-matrix-riot-modular
Maybe we can spent some of the Money into a state-of-the-art Messenger Interface where a Emoji Picker is behind the Emoji Icon? That would be really great :smile:

**Comment by jryans** [comment]
I believe everyone agrees this should be fixed. There are other higher priority items for the team at the moment, so community contributions would likely be the best way to accelerate things here.

**Comment by fti7** [comment]
Higher Priorities than a major UX Issue in a Messenger Application? Ok... :disappointed_relieved: we will wait

**Comment by t3chguy** [comment]
I mean there is already an emoji autocompletion similar to that in slack launched using ':' in the composer so its not like it's impossible to do

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/riot-web/issues/1107
