### ISSUE TITLE
View Markdown Source

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9501]
I would love to have a way to view the Markdown source for HTML messages sent by Riot. This would be quite useful for tweaking a message, pasting the same message in another place, etc.

I realize that Riot only sends the generated HTML in the event, so potentially we'd have to try to convert it back to Markdown as best we can...? Alternatively, we could attach the Markdown source as an additional fields for events that are entered as Markdown.

**Comment by jryans** [comment]
If a message is sent from the composer's Markdown mode, then the MD source is in `content.body`. If the rich text mode is used, then `content.body` is plain text only (without any formatting).

(For some reason, I though the MD source was lost even for messages entered as MD.)

With that in mind, I don't think we really need to do anything here.

**Comment by martinvonwittich** [comment]
I'm currently missing exactly this functionality in Riot. While I can easily get the Markdown source of my own message by editing them, there is no simple way to get the Markdown source of messages sent by other users, because I can't open the editing view for these.

The ability to view the Markdown source of messages from other users would allow people to take an existing message, extend it, and post it again. I could for example copy the source of a list someone else has posted, and add new entries to it. This can't easily be done by copy-pasting the message as it is displayed, because this will cause it to lose all formatting.

Could this issue be reopened?

**Comment by jryans** [comment]
@martinvonwittich Well, you can view source for anyone's events, and the `content.body` would have the MD source if it exists. If you are looking for something fancier than that, I'd suggest filing a new issue to describe your suggestion.

**Comment by martinvonwittich** [comment]
> @martinvonwittich Well, you can view source for anyone's events, and the `content.body` would have the MD source if it exists. If you are looking for something fancier than that, I'd suggest filing a new issue to describe your suggestion.

Done! #13516
