### ISSUE TITLE
Phone numbers in Romania are not currently supported

### ISSUE THREAD

**Issue by nicolaevladescu** [vector-im/riot-web#9532]
### Description

It looks like OpenMarket supports Romania

https://www.openmarket.com/docs/Content/globalcoverage/country/romania.htm

### Steps to reproduce

Add a Romanian phone number and prefix.

You will get this error : `Phone numbers in this country are not currently supported (Status 400)`

### Version information

riot-web 1.0.7

**Comment by lampholder** [comment]
The issue is this:

![image](https://user-images.githubusercontent.com/1922197/56648369-1d4b5e80-667b-11e9-8966-90ee300d1b28.png)

OM supports SMS to Romania, but not without some country-specific registration - we don't have the bandwidth to pursue country-specific registration work in all the countries that require it, so (unfortunately) we've chosen to declare all countries that don't "just work" to be unsupported. Sorry for the inconvenience :(

In the long term we will consider integrating with a dedicated 2FA provider that can validate phone number registration globally without our doing any per-territory work.
