### ISSUE TITLE
New "Do you want to join this room?" prompt is missing important info

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9564]
It should surely:
 * mention the room's name (not just the name of the person who is inviting you)
 * say whether it's a DM or not (e.g. "you have been invited to chat by ..." for a DM)
 * have a way of telling you the mxid of who's inviting you, to avoid a major phishing attack

**Comment by lampholder** [comment]
### 1. Loss of the room name:

Old (used to have the room name in its standard place at the top of the timeline):
![image](https://user-images.githubusercontent.com/1922197/56897052-62a9ca80-6a85-11e9-86ff-178d8e3e2e06.png)

-------
New (room name not displayed, except in the roomlist):
![image](https://user-images.githubusercontent.com/1922197/56897068-6c333280-6a85-11e9-83e7-8ec10fedd6d1.png)
We need to display the room name - it would probably be good for @nadonomy to recommend how this should be impled in a way that scales to massive room names (or handles rooms that only have an alias, or no name or alias).


### 2. Say whether it's a DM or not:
Can we know this before we've joined? Nice to have if we can, but if it's tricky I'd say we could release without this.

### 3. Displaying the mxid:
The old UX displayed the mxid (and only the mxid, not the display name). The new UX only shows the display name, though if you click on it you get the following UX:
![image](https://user-images.githubusercontent.com/1922197/56897216-d2b85080-6a85-11e9-9ec4-1614175bd3c2.png)
This is pretty confusing, since we've now lost the preview bar and just have memberinfo on a blank screen (with no obvious way to return to the invite without finding it again in the roomlist).

We show mxids whenever there's a need to disambiguate, so I think having the mxids baked into the room preview bar to clearly identify the inviter makes sense.

**Comment by nadonomy** [comment]
> * mention the room's name (not just the name of the person who is inviting you)

You can see this in the room list. But if we want it to be explicit, a sensible place to put it would just be in the title. i.e. "Do you want to join Matrix HQ?" instead of "Do you want to join this room?"

> * say whether it's a DM or not (e.g. "you have been invited to chat by ..." for a DM)

Didn't know we could do that. Again, changing the title text to "Do you want to chat with Matthew?" would work.

> * have a way of telling you the mxid of who's inviting you, to avoid a major phishing attack

We discussed this during dev and opted to reveal it after clicking the display name. After testing, I agree with @lampholder that the current implementation is confusing, and was meant to pop out in context, not hiding the dialog. I propose:

a) We should let the member info panel pop out in context, without dismissing the room preview dialog.
b) If we want to be even more defensive, we could display the mxid in brackets after the name: **Person** (@person-not-on-github:matrix.org)

**Comment by lampholder** [comment]
> You can see this in the room list. But if we want it to be explicit, a sensible place to put it would just be in the title. i.e. "Do you want to join Matrix HQ?" instead of "Do you want to join this room?"

Should we just truncate for massive room names? Should we pick an alias if there's no room name? What should we do if the room has no name or aliases?

> Didn't know we could do that. Again, changing the title text to "Do you want to chat with Matthew?" would work.

I don't know that we can, but this ^ is good if we can.

> a) If not too difficult, we should let the member info panel pop out in context, without dismissing the room preview dialog.
b) If we want to be even more defensive, we could display the mxid in brackets after the name: Person (@person-not-on-github:matrix.org)

Ideally I think we'd do both.

**Comment by nadonomy** [comment]
> > You can see this in the room list. But if we want it to be explicit, a sensible place to put it would just be in the title. i.e. "Do you want to join Matrix HQ?" instead of "Do you want to join this room?"
> 
> Should we just truncate for massive room names? Should we pick an alias if there's no room name? What should we do if the room has no name or aliases?

CSS `word-wrap: break-word;` should do the lifting for us on the majority of long names, but I'm not against truncating after 100 characters or so if we need this UI to be more defensive against the protocol.

The app displays 'empty room' when a room name isn't set, I'd vote to keep consistency and display 'empty room' in the title. I'm not sold on the utility of the room ID in this context, but if others think it's important in this specific instance I'd add it as part of the body text as a new line, so there'd be:

```
'x' has invited you
Room ID: xyz123
```

**Comment by lampholder** [comment]
I think we'd want _not_ to show the room id - as far as I know we _never_ want to show room id in the UX (outside of generated permalinks and in the 'advanced' section of room settings for people who are really hunting the roomid (and the address bar, obvs))

**Comment by ara4n** [comment]
> Should we pick an alias if there's no room name? What should we do if the room has no name or aliases?

Invites are special in that the sender gets to choose the name of the room - given we haven't joined the room itself yet, we don't know what its actual m.room.name or aliases are.

We should never ever show room IDs in the UI.

> > mention the room's name (not just the name of the person who is inviting you)
>
> You can see this in the room list. But if we want it to be explicit, a sensible place to put it would just be in the title. i.e. "Do you want to join Matrix HQ?" instead of "Do you want to join this room?"

The fact this tripped me up repeatedly until I finally realised what's going on is not a good sign.  We should definitely be saying "Do you want to join Matrix HQ?", and **showing the avatar of the room, not the inviter**.

**Comment by ara4n** [comment]
We also seem to have lost the ability to peek into public rooms which you're invited to? :/

**Comment by jryans** [comment]
> We also seem to have lost the ability to peek into public rooms which you're invited to? :/

When testing on /app, I was not able to peek into public rooms during an invite there either. Perhaps I am missing some detail though... Please file a separate issue with more detail if you're confident that's how it used to work.

**Comment by jryans** [comment]
> a) If not too difficult, we should let the member info panel pop out in context, without dismissing the room preview dialog.

This part was deferred from the current fire fighting, as it seemed to difficult in the time avalilable. I filed https://github.com/vector-im/riot-web/issues/9593 to track it. For the moment, the inviter was changed to not be clickable.

**Comment by jryans** [comment]
> > We also seem to have lost the ability to peek into public rooms which you're invited to? :/
> 
> When testing on /app, I was not able to peek into public rooms during an invite there either. Perhaps I am missing some detail though... Please file a separate issue with more detail if you're confident that's how it used to work.

Looks like @lampholder filed https://github.com/vector-im/riot-web/issues/9594 about this topic.

**Comment by ara4n** [comment]
> We also seem to have lost the ability to peek into public rooms which you're invited to? :/

this was a thinko - as per #9594 it'd be a misfeature if it did it automatically (as Riot/iOS does).
