### ISSUE TITLE
extract canvas data - firefox permissions

### ISSUE THREAD

**Issue by dajohi** [vector-im/riot-web#9605]
https://riot.im/app causes Firefox 66.0.2 to prompt for permission to allow 'extract canvas data'.

Do you know the cause?

**Comment by jryans** [comment]
Do you have `privacy.resistFingerprinting` set to `true` in about:config?

Do you see this prompt immediately on loading Riot?

**Comment by dajohi** [comment]
Yes to both questions.

**Comment by jryans** [comment]
We do use a `<canvas>` and read data out of it when creating image thumbnails for uploading images and videos...

But I guess it's unlikely that happens on load. Do you see any error in the Console if you deny the permission?

**Comment by jryans** [comment]
I am able to replicate the behaviour you mention by setting `privacy.resistFingerprinting`. I'm not quite sure what's trigger this on load. My first guess is some library is eagerly testing for `canvas` support by calling one of the blocked methods.

Unfortunately, there's no logging of what code triggered, so it may take some digging to find why this is happening. 😖 

Anyway, it's certainly not intentional for this to happen on load.

**Comment by jryans** [comment]
We're investigating the trigger, and I hope to have more details soon.

**Comment by jryans** [comment]
This is being triggered by the [favico.js library](https://github.com/ejci/favico.js/blob/6a3f430be559f93d96573e2a4a0116e154c11319/favico.js#L537) that we use to apply a badge to favicon when notifications come in.

We could try to delay this at least until you are logged in, but it would likely still be surprising...

We'll have to think about the best way to proceed here.

**Comment by jryans** [comment]
Firefox's existing logs weren't very helpful in diagnosing this issue, so I [filed a Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1548375) with patches to improve this for the next person.

**Comment by jryans** [comment]
https://github.com/vector-im/riot-web/pull/9616 will improve this so that the prompt doesn't appear until after logging in and receiving a notification. Unfortunately, I don't think Firefox gives the page anyway to know that it's running in resist fingerprinting mode, so it's hard to do something better here.

**Comment by dajohi** [comment]
Hey, thanks for spending the time tracking it down and improving it! :+1:

**Comment by karolyi** [comment]
I think this bug is back. I use librewolf which has rfp enabled per default, and even with the "extract canvas data" permission enabled, I get uploaded image thumbnails like this:

![image](https://user-images.githubusercontent.com/987055/195574010-ef6edfbb-f464-4a41-bbb9-8aa15f73ac0e.png)

**Comment by ara4n** [comment]
see also https://github.com/element-hq/element-web/issues/10146

**Comment by karolyi** [comment]
FYI, Firefox finally fixed this in version 141.
