### ISSUE TITLE
Login flow issues "A different user id has already been registered for this session"

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#9659]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

Start incognito session.
Visit riot.im/app
Select other server, fill in details of HS and IS, fill in registration details, trigger email sending.
Get email, open link from email (which opens in another tab)

Describe how what happens differs from what you expected.

Receive error "A different user ID has already been registered for this session"

(the original tab has now been logged in)

Log: sent/not sent?    

### Version information

For the web app:

- **Browser**: Chrome
- **OS**: linux
- **URL**: riot.im/app

**Comment by michaelkaye** [comment]
I know there used to be other behaviour here, but it didn't used to be that.

**Comment by ara4n** [comment]
I just had something very similar to this again; i think this is same as https://github.com/vector-im/riot-web/issues/9581?

**Comment by dbkr** [comment]
I don't quite get these symptoms - specifically I am getting:
![Screenshot 2019-06-12 at 16 19 40](https://user-images.githubusercontent.com/986903/59363911-ea921e00-8d2d-11e9-8de7-bb5051b950c7.png)

...which is because its forgetting the custom HS on the other side of the email so the registration just doesn't work there (but does complete in the old tab)
