### ISSUE TITLE
Message editing composer - doesn't work well with IMEs (on Firefox OS X Chinese)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9740]
![Screen Recording 2019-05-16 at 12 06 35 2019-05-16 12_08_16](https://user-images.githubusercontent.com/1922197/57849513-5f2b7880-77d3-11e9-84f7-598d567677a8.gif)

In the gif I:
- open a message for editing
- my cursor is directly adjacent to a non-whitespace character
- I start typing pinyin
- the roman characters are swallowed as I type
- pressing space to submit the chinese characters at the end doesn't actually send the characters

_However_ - it isn't broken in all cases - if you type a space character first, the roman characters are not swallowed and the chinese is submitted correctly.

**Comment by wcjwing** [comment]
Same case occured on Riot Windows 10 Simple Chinese, first character always ignore and some character is missing from IMEs randomly.

For GIF case, what I really want to input is "今天你好吗，怎么样？“
![BwVNdaHKXN](https://user-images.githubusercontent.com/43275910/62019687-91554f80-b1f2-11e9-8a13-8ae1acde1219.gif)

**Comment by jryans** [comment]
@wcjwing This issue is about the composer for edits, which is (currently) separate from the composer for normal messages. Your video above seems to show the composer for regular messages, and it's a [known issue](https://github.com/vector-im/riot-web/issues/7665) that it fails for IMEs and many other cases too.

We hope to solve https://github.com/vector-im/riot-web/issues/7665 by [replacing the regular composer with the one for edits](https://github.com/vector-im/riot-web/issues/9866), so please do check out its IME compatibility as well.

**Comment by bwindels** [comment]
@lampholder I've tried to reproduce with Firefox 68 on macOs 10.14.4 (Mojave) and all seems to work well:

![chinese](https://user-images.githubusercontent.com/274386/63526435-f0a33880-c4ee-11e9-8095-f9fe07bc90e3.gif)

Also tried on Chrome with same result.

**Comment by aaronraimist** [comment]
Related: https://github.com/vector-im/riot-web/issues/10646

**Comment by bwindels** [comment]
Assuming this is fixed, as https://github.com/vector-im/riot-web/issues/10646 is.
