### ISSUE TITLE
Getting sticker pack hangs

### ISSUE THREAD

**Issue by tgr** [vector-im/riot-web#9763]
When clicking on the emoji icon in web Riot in some channel I get this:

![matrix-stickerpack-hangs](https://user-images.githubusercontent.com/145412/57982080-6d320100-7a40-11e9-988e-80678d892430.png)

```
Request URL: https://scalar-staging.vector.im/api/widgets/assets?widget_type=m.stickerpicker&widget_id=77c8caf7-62b3-4d3b-8e28-e06a6f6467e8&filter_unpurchased=true
Request Method: GET
Status Code: 403 
Remote Address: [2606:4700:30::681f:465f]:443
cf-ray: 4d95fb2e3cce7ba6-PRG

{"message":"Forbidden","data":null}
```

**Comment by jryans** [comment]
@jaywink, maybe you can help here?

**Comment by jaywink** [comment]
Hi @tgr 

Did the issue resolve for you? If not, could you please check whether the request to `/widgets/assets` is getting a cookie `scalar_token: secretdontpasteithere` sent with the request? If not, can you check whether there is such a cookie set at all for the domain? If there is one, could you please add here the last 3 characters of it, I'll check whether it exists in the database. **DO NOT paste the whole token here**. Then please try clearing it, reload and see if that helps.

Also which Riot are you using, assuming `riot.im/develop` as per the staging url? Just tested myself and I get a 200 correctly for the stickerpicker assets for my account. I can see a lot of 403's in the logs but this would be normal and Riot should "recover" from it by requesting a new Scalar token from the backend. It's also possible for some reason this is not happening in your case, but first if you can check the token exists and is being sent.

**Comment by tgr** [comment]
I'm using https://riot.im/app/. The `scalar_token` cookie is set for the `scalar-staging.riot.im` domain (actually it's set in triplicate, for `/`, for `/scalar/api/widgets` and for `/scalar/api/widgets/id/<id>` but it's all the same cookie) but not for `scalar-staging.vector.im` so it's not getting sent.

Clearing the cookie has no effect, it's regenerated but `scalar-staging.vector.im` is not touched.

**Comment by tgr** [comment]
I get the same behavior for `/develop`, FWIW, except that the development version sends a bunch of `https://scalar-staging.vector.im/api/account?scalar_token=<token>&v=1.1` requests (no cookies sent or received) while the normal version does not use that domain other than for the stickers (`stickers.html`, `stickers-<id>.bundle.js`, the assets API cal and the spinner icon).

**Comment by jaywink** [comment]
@tgr the latter (token sent in query except for widget assets) is expected.

So the problem seems to be that after the Matrix.org security incident, when rebuilding Scalar, we decided to (stupidly) "fix" the old Scalar staging URL's to point from `scalar-staging.riot.im` to `scalar-staging.vector.im` - to make the url's consistent with the live version which is under `vector.im` as well. Later we realized this broke quite a few widgets that had been created via Scalar staging.

Could you try removing the stickerpicker widget and re-adding it back? That *should* create a new widget instance with the correct url and thus the cookies should be sent.

Let me know if this doesn't resolve the issue.

**Comment by tgr** [comment]
Thanks! I added some pack in Manage integrations > Stickerpacks and then removed it, and reloaded the app. That sort of resolved the issue - the API request is now sent to `scalar.vector.im` and answered properly.

I had trouble with the smiley icon working but only giving me a "You don't currently have any stickerpacks enabled" message, even after enabling some (the management UI did remember their enabled state). That seems to have been cookie confusion - the token cookies are now set on the `scalar.vector.im` domain, and I ended up with two different sets - one for `/` and `/scalar/api/widgets/id/<id>`, and a different one for `/scalar/api/widgets`. Deleting that latter one while keeping the others seems to have resolved the issue.

**Comment by jaywink** [comment]
Great. Sorry for the inconvenience caused by the rebuild.

I'll leave this open for a while so people searching for sticker picker issues have a better chance of seeing this. Most people should be using live widgets so this issue only affects those who have at some point created their stickerpicker against the staging scalar.
