### ISSUE TITLE
invitation by pasting blocks of mxids no longer works

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9956]
i'm sure we used to be able to bulk invite into a room by pasting space, comma or NL separated list of MXIDs. but no morer.

**Comment by lampholder** [comment]
If this did work it was a long time ago. I can well imagine that pillification was involved in the breakage.

**Comment by MurzNN** [comment]
Seems current fix is not so good, because it force converts any pasted text to user id, so if I paste only `alex` or even `a` for make autocomplete, it immediately converts this to "Unknown Address" block.
I think we need to parse pasted line, and converts to widget, only if it match mxid (or room id/alias), and stay plain text, if nothing resolved, instead of `Unknown Address` rendered block.

**Comment by t3chguy** [comment]
> I think we need to parse pasted line, and converts to rendered block, only if it match mxid (or room id/alias), and stay in plain text, if nothing resolved, instead of Unknown Address rendered block

This would yield very inconsistent behaviour, if you paste the list:

```
@valid:user
invalid_user
@valid:user
other_invalid_user
another_invalid_user
```
(without duplicates)
it'd successfully add 2 users but leave `invalid_user other_invalid_user another_invalid_user` in the autocomplete box which would fail the autocomplete

**Comment by MurzNN** [comment]
> it'd successfully add 2 users but leave invalid_user other_invalid_user another_invalid_user in the autocomplete box which would fail the autocomplete

This is not so bad, because user will see error that some users are invalid, and must remove all invalid items before use autocomplete for add new ones.

**Comment by MurzNN** [comment]
For not reopen issue already in RC, I open separate issue about pasting part of text problem: #10481
